"""
Scientific Figure Generator (matplotlib + seaborn, NOT plotly)

Produces publication-grade figures in PNG + SVG. Each figure is rendered
once and cached by a content-hash so regenerating the same data does not
re-plot. The registry covers every common scientific figure type used in
hypothesis / discovery papers:

    bar / grouped_bar / stacked_bar
    scatter / bubble
    line / multi_line
    violin / box_strip
    heatmap (correlation, hit map, pathway enrichment)
    forest_plot (effect size + CI across studies)
    survival (Kaplan-Meier approximation)
    volcano (genomic differential expression)
    roc (classifier performance)
    radar (multi-dim scoring comparison)
    lollipop (ranked effect size)
    confidence_meter (hypothesis confidence dimension chart)
    dimension_breakdown (spider chart of scoring dimensions)
    cost_breakdown (per-stage cost bar)
    evidence_landscape (paper scatter by year vs relevance)
    translational_timeline (T0-T5 roadmap with milestones)

Inputs are `FigureSpec` records so that LLMs can emit structured figure
specifications in stage outputs; the renderer is deterministic.
"""

from __future__ import annotations

import base64
import hashlib
import io
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal, Optional

from app.visualization.style import (
    apply_humanovo_style,
    humanovo_colors,
    humanovo_gradient,
)

logger = logging.getLogger(__name__)


class FigureType(str, Enum):
    BAR = "bar"
    GROUPED_BAR = "grouped_bar"
    STACKED_BAR = "stacked_bar"
    SCATTER = "scatter"
    BUBBLE = "bubble"
    LINE = "line"
    MULTI_LINE = "multi_line"
    VIOLIN = "violin"
    BOX_STRIP = "box_strip"
    HEATMAP = "heatmap"
    FOREST_PLOT = "forest_plot"
    SURVIVAL = "survival"
    VOLCANO = "volcano"
    ROC = "roc"
    RADAR = "radar"
    LOLLIPOP = "lollipop"
    CONFIDENCE_METER = "confidence_meter"
    DIMENSION_BREAKDOWN = "dimension_breakdown"
    COST_BREAKDOWN = "cost_breakdown"
    EVIDENCE_LANDSCAPE = "evidence_landscape"
    TRANSLATIONAL_TIMELINE = "translational_timeline"


@dataclass
class FigureSpec:
    """Declarative figure specification. Serializable; LLMs emit these."""
    figure_type: FigureType
    title: str
    caption: str = ""
    data: dict[str, Any] = field(default_factory=dict)
    x_label: str = ""
    y_label: str = ""
    series_labels: list[str] = field(default_factory=list)
    annotations: list[dict[str, Any]] = field(default_factory=list)
    color_scheme: Literal["palette", "gradient"] = "palette"
    figsize: tuple[float, float] = (6.4, 4.4)
    note: str = ""

    def content_hash(self) -> str:
        import json
        payload = json.dumps(
            {
                "type": self.figure_type.value,
                "title": self.title,
                "data": self.data,
                "x_label": self.x_label,
                "y_label": self.y_label,
                "series_labels": self.series_labels,
                "color_scheme": self.color_scheme,
            },
            sort_keys=True, default=str,
        )
        return hashlib.sha256(payload.encode()).hexdigest()[:16]


@dataclass
class RenderedFigure:
    spec: FigureSpec
    png_b64: str
    svg_text: str
    content_hash: str
    source_note: str = "Generated by Humanovo visualization pipeline"

    def to_dict(self) -> dict[str, Any]:
        return {
            "figure_type": self.spec.figure_type.value,
            "title": self.spec.title,
            "caption": self.spec.caption,
            "png_b64": self.png_b64,
            "svg": self.svg_text,
            "content_hash": self.content_hash,
            "source_note": self.source_note,
        }


# ---------------------------------------------------------------------------
# Core renderer
# ---------------------------------------------------------------------------


def generate_figure(spec: FigureSpec) -> RenderedFigure:
    """Render a figure per the spec. Returns PNG (base64) + SVG string.

    If matplotlib is unavailable, returns a placeholder with the spec data
    preserved so downstream consumers (paper gen) can still include a
    structured figure entry with a text description.
    """
    apply_humanovo_style()
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return _placeholder(spec)

    dispatch = {
        FigureType.BAR: _render_bar,
        FigureType.GROUPED_BAR: _render_grouped_bar,
        FigureType.STACKED_BAR: _render_stacked_bar,
        FigureType.SCATTER: _render_scatter,
        FigureType.BUBBLE: _render_bubble,
        FigureType.LINE: _render_line,
        FigureType.MULTI_LINE: _render_multi_line,
        FigureType.VIOLIN: _render_violin,
        FigureType.BOX_STRIP: _render_box_strip,
        FigureType.HEATMAP: _render_heatmap,
        FigureType.FOREST_PLOT: _render_forest_plot,
        FigureType.SURVIVAL: _render_survival,
        FigureType.VOLCANO: _render_volcano,
        FigureType.ROC: _render_roc,
        FigureType.RADAR: _render_radar,
        FigureType.LOLLIPOP: _render_lollipop,
        FigureType.CONFIDENCE_METER: _render_confidence_meter,
        FigureType.DIMENSION_BREAKDOWN: _render_dimension_breakdown,
        FigureType.COST_BREAKDOWN: _render_cost_breakdown,
        FigureType.EVIDENCE_LANDSCAPE: _render_evidence_landscape,
        FigureType.TRANSLATIONAL_TIMELINE: _render_translational_timeline,
    }

    renderer = dispatch.get(spec.figure_type)
    if renderer is None:
        return _placeholder(spec)

    fig = plt.figure(figsize=spec.figsize)
    try:
        ax = fig.add_subplot(111)
        renderer(ax, spec)
        ax.set_title(spec.title, loc="left", fontweight="bold", pad=10)
        if spec.x_label:
            ax.set_xlabel(spec.x_label)
        if spec.y_label:
            ax.set_ylabel(spec.y_label)
        for annot in spec.annotations:
            x = annot.get("x")
            y = annot.get("y")
            text = annot.get("text", "")
            if x is not None and y is not None:
                ax.annotate(
                    text, xy=(x, y),
                    xytext=(annot.get("dx", 5), annot.get("dy", 5)),
                    textcoords="offset points",
                    fontsize=8, alpha=0.85,
                )

        png = _save_png(fig)
        svg = _save_svg(fig)
    finally:
        plt.close(fig)

    return RenderedFigure(
        spec=spec,
        png_b64=png,
        svg_text=svg,
        content_hash=spec.content_hash(),
    )


# ---------------------------------------------------------------------------
# Placeholder for missing matplotlib
# ---------------------------------------------------------------------------


def _placeholder(spec: FigureSpec) -> RenderedFigure:
    description = (
        f"[Figure placeholder: {spec.figure_type.value}]\n"
        f"Title: {spec.title}\n"
        f"X: {spec.x_label} | Y: {spec.y_label}\n"
        f"Caption: {spec.caption or '(no caption)'}"
    )
    return RenderedFigure(
        spec=spec,
        png_b64="",
        svg_text=f"<svg xmlns='http://www.w3.org/2000/svg'><text>{description}</text></svg>",
        content_hash=spec.content_hash(),
        source_note="matplotlib unavailable — placeholder emitted",
    )


def _save_png(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=300)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("ascii")


def _save_svg(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="svg")
    buf.seek(0)
    return buf.read().decode("utf-8")


# ---------------------------------------------------------------------------
# Individual renderers
#
# Each renderer reads from spec.data with a documented schema and draws on
# the provided axes. Data that is missing falls back to an empty axis with
# a textual explanation — never raise.
# ---------------------------------------------------------------------------


def _palette(spec: FigureSpec, n: int) -> list[str]:
    return (humanovo_gradient(n) if spec.color_scheme == "gradient"
            else humanovo_colors(n))


def _render_bar(ax, spec: FigureSpec) -> None:
    """data = {'categories': [...], 'values': [...], 'errors': [optional]}"""
    cats = spec.data.get("categories", [])
    vals = spec.data.get("values", [])
    errs = spec.data.get("errors")
    colors = _palette(spec, len(cats))
    ax.bar(cats, vals, yerr=errs, color=colors, edgecolor="black", linewidth=0.6)
    if any(len(str(c)) > 10 for c in cats):
        ax.tick_params(axis="x", rotation=30)


def _render_grouped_bar(ax, spec: FigureSpec) -> None:
    """data = {'categories': [...], 'groups': {'name': [...], 'name2': [...]}}"""
    import numpy as np
    cats = spec.data.get("categories", [])
    groups = spec.data.get("groups", {})
    if not cats or not groups:
        return
    x = np.arange(len(cats))
    width = 0.8 / max(1, len(groups))
    for i, (name, values) in enumerate(groups.items()):
        offset = (i - (len(groups) - 1) / 2) * width
        ax.bar(x + offset, values, width=width, label=name,
               color=humanovo_colors(len(groups))[i])
    ax.set_xticks(x)
    ax.set_xticklabels(cats, rotation=20)
    ax.legend(frameon=False)


def _render_stacked_bar(ax, spec: FigureSpec) -> None:
    """data = {'categories': [...], 'layers': {'name': [...], 'name2': [...]}}"""
    import numpy as np
    cats = spec.data.get("categories", [])
    layers = spec.data.get("layers", {})
    if not cats or not layers:
        return
    x = np.arange(len(cats))
    bottom = np.zeros(len(cats))
    colors = humanovo_colors(len(layers))
    for i, (name, values) in enumerate(layers.items()):
        ax.bar(x, values, bottom=bottom, label=name, color=colors[i], edgecolor="white", linewidth=0.4)
        bottom = bottom + np.array(values)
    ax.set_xticks(x)
    ax.set_xticklabels(cats, rotation=20)
    ax.legend(frameon=False)


def _render_scatter(ax, spec: FigureSpec) -> None:
    """data = {'x': [...], 'y': [...], 'labels': [optional], 'colors': [optional]}"""
    xs = spec.data.get("x", [])
    ys = spec.data.get("y", [])
    labels = spec.data.get("labels", [])
    cols = spec.data.get("colors")
    if cols is None:
        cols = [_palette(spec, 8)[0]] * len(xs)
    ax.scatter(xs, ys, c=cols, s=45, edgecolor="#222", linewidth=0.5, alpha=0.85)
    for lab, xv, yv in zip(labels, xs, ys):
        ax.annotate(str(lab), (xv, yv), xytext=(4, 4),
                    textcoords="offset points", fontsize=7, alpha=0.75)


def _render_bubble(ax, spec: FigureSpec) -> None:
    """data = {'x': [], 'y': [], 'size': [], 'labels': [optional]}"""
    xs = spec.data.get("x", [])
    ys = spec.data.get("y", [])
    sizes = spec.data.get("size", [])
    labels = spec.data.get("labels", [])
    if not xs or not ys:
        return
    max_size = max(sizes) if sizes else 1
    normalized = [900 * s / max_size + 20 for s in (sizes or [1] * len(xs))]
    ax.scatter(xs, ys, s=normalized, alpha=0.65,
               color=_palette(spec, 8)[0], edgecolor="#222", linewidth=0.5)
    for lab, xv, yv in zip(labels, xs, ys):
        ax.annotate(str(lab), (xv, yv), xytext=(3, 3),
                    textcoords="offset points", fontsize=7)


def _render_line(ax, spec: FigureSpec) -> None:
    """data = {'x': [...], 'y': [...]}"""
    xs = spec.data.get("x", [])
    ys = spec.data.get("y", [])
    color = _palette(spec, 1)[0]
    ax.plot(xs, ys, color=color, linewidth=1.8, marker="o", markersize=4)


def _render_multi_line(ax, spec: FigureSpec) -> None:
    """data = {'x': [...], 'series': {'name': [...], 'name2': [...]}}"""
    xs = spec.data.get("x", [])
    series = spec.data.get("series", {})
    colors = humanovo_colors(len(series))
    for (name, vals), color in zip(series.items(), colors):
        ax.plot(xs, vals, label=name, color=color, linewidth=1.6, marker="o", markersize=3)
    ax.legend(frameon=False)


def _render_violin(ax, spec: FigureSpec) -> None:
    """data = {'groups': {'name': [...], 'name2': [...]}}"""
    groups = spec.data.get("groups", {})
    if not groups:
        return
    data = list(groups.values())
    labels = list(groups.keys())
    parts = ax.violinplot(data, showmedians=True)
    for i, b in enumerate(parts["bodies"]):
        b.set_facecolor(humanovo_colors(len(labels))[i])
        b.set_edgecolor("#222")
        b.set_alpha(0.85)
    ax.set_xticks(range(1, len(labels) + 1))
    ax.set_xticklabels(labels, rotation=20)


def _render_box_strip(ax, spec: FigureSpec) -> None:
    """data = {'groups': {'name': [...], ...}}"""
    try:
        import seaborn as sns
        import pandas as pd
    except ImportError:
        return _render_violin(ax, spec)
    groups = spec.data.get("groups", {})
    rows = []
    for name, vals in groups.items():
        for v in vals:
            rows.append({"group": name, "value": v})
    if not rows:
        return
    df = pd.DataFrame(rows)
    sns.boxplot(data=df, x="group", y="value", ax=ax,
                palette=humanovo_colors(len(groups)))
    sns.stripplot(data=df, x="group", y="value", ax=ax,
                  color="#222", size=3, alpha=0.55, jitter=True)


def _render_heatmap(ax, spec: FigureSpec) -> None:
    """data = {'matrix': [[...]], 'row_labels': [...], 'col_labels': [...]}"""
    try:
        import seaborn as sns
        import numpy as np
    except ImportError:
        return
    matrix = spec.data.get("matrix")
    if not matrix:
        return
    row_labels = spec.data.get("row_labels")
    col_labels = spec.data.get("col_labels")
    sns.heatmap(
        np.array(matrix), ax=ax,
        xticklabels=col_labels or True,
        yticklabels=row_labels or True,
        cmap="viridis", annot=True, fmt=".2f",
        cbar_kws={"shrink": 0.7},
    )


def _render_forest_plot(ax, spec: FigureSpec) -> None:
    """data = {'studies': [{'name': str, 'effect': float, 'ci_low': float, 'ci_high': float}, ...]}"""
    studies = spec.data.get("studies", [])
    if not studies:
        return
    names = [s["name"] for s in studies]
    effects = [s["effect"] for s in studies]
    lows = [s["ci_low"] for s in studies]
    highs = [s["ci_high"] for s in studies]
    y = list(range(len(studies)))
    ax.errorbar(effects, y, xerr=[
        [e - lo for e, lo in zip(effects, lows)],
        [hi - e for e, hi in zip(effects, highs)],
    ], fmt="o", color=_palette(spec, 1)[0], ecolor="#555", capsize=3)
    ax.axvline(x=0, color="gray", linestyle="--", linewidth=1)
    ax.set_yticks(y)
    ax.set_yticklabels(names)
    ax.invert_yaxis()


def _render_survival(ax, spec: FigureSpec) -> None:
    """data = {'times': [...], 'curves': {'name': [survival_probs], ...}}"""
    times = spec.data.get("times", [])
    curves = spec.data.get("curves", {})
    colors = humanovo_colors(len(curves))
    for (name, probs), c in zip(curves.items(), colors):
        ax.step(times, probs, where="post", label=name, color=c, linewidth=1.8)
    ax.set_ylim(0, 1.02)
    ax.legend(frameon=False)


def _render_volcano(ax, spec: FigureSpec) -> None:
    """data = {'log2fc': [...], 'neglog10p': [...], 'labels': [...]}
    Highlights significant up/down-regulated genes."""
    log2fc = spec.data.get("log2fc", [])
    neglog10p = spec.data.get("neglog10p", [])
    labels = spec.data.get("labels", [])
    if not log2fc:
        return
    colors = []
    for fc, p in zip(log2fc, neglog10p):
        if p >= 2 and fc >= 1:
            colors.append("#D55E00")
        elif p >= 2 and fc <= -1:
            colors.append("#0072B2")
        else:
            colors.append("#888")
    ax.scatter(log2fc, neglog10p, c=colors, s=25, alpha=0.75, edgecolor="none")
    ax.axhline(y=2, color="gray", linestyle=":", linewidth=0.8)
    ax.axvline(x=1, color="gray", linestyle=":", linewidth=0.8)
    ax.axvline(x=-1, color="gray", linestyle=":", linewidth=0.8)
    for lab, x, y in zip(labels, log2fc, neglog10p):
        if abs(x) >= 2 and y >= 3:
            ax.annotate(lab, (x, y), xytext=(3, 3),
                        textcoords="offset points", fontsize=7)


def _render_roc(ax, spec: FigureSpec) -> None:
    """data = {'curves': [{'name': str, 'fpr': [...], 'tpr': [...], 'auc': float}, ...]}"""
    curves = spec.data.get("curves", [])
    colors = humanovo_colors(len(curves))
    for c, color in zip(curves, colors):
        ax.plot(c.get("fpr", []), c.get("tpr", []),
                label=f"{c.get('name','')} (AUC={c.get('auc',0):.2f})",
                color=color, linewidth=1.8)
    ax.plot([0, 1], [0, 1], linestyle="--", color="#888", linewidth=1)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.02)
    ax.legend(frameon=False, loc="lower right")


def _render_radar(ax, spec: FigureSpec) -> None:
    """data = {'axes': [...], 'series': {'name': [values], ...}}"""
    import numpy as np
    axes_lbl = spec.data.get("axes", [])
    series = spec.data.get("series", {})
    if not axes_lbl or not series:
        return
    n = len(axes_lbl)
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False).tolist()
    angles += angles[:1]
    # Remove the default rectangular axes and add polar
    ax.remove()
    fig = ax.figure
    ax = fig.add_subplot(111, polar=True)
    colors = humanovo_colors(len(series))
    for (name, values), color in zip(series.items(), colors):
        vals = list(values) + [values[0]]
        ax.plot(angles, vals, label=name, color=color, linewidth=1.6)
        ax.fill(angles, vals, alpha=0.15, color=color)
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(axes_lbl, fontsize=9)
    ax.set_rlabel_position(225)
    ax.legend(loc="upper right", bbox_to_anchor=(1.3, 1.1), frameon=False, fontsize=8)


def _render_lollipop(ax, spec: FigureSpec) -> None:
    """data = {'categories': [...], 'values': [...]}"""
    cats = spec.data.get("categories", [])
    vals = spec.data.get("values", [])
    if not cats:
        return
    colors = _palette(spec, len(cats))
    y = list(range(len(cats)))
    ax.hlines(y, 0, vals, color="#bbb", linewidth=2)
    ax.plot(vals, y, "o", color=colors[0], markersize=8)
    ax.set_yticks(y)
    ax.set_yticklabels(cats)
    ax.invert_yaxis()


def _render_confidence_meter(ax, spec: FigureSpec) -> None:
    """data = {'dimensions': {'name': score(0-1), ...}}"""
    dims = spec.data.get("dimensions", {})
    if not dims:
        return
    names = list(dims.keys())
    vals = [float(dims[n]) for n in names]
    colors = humanovo_gradient(len(names))
    y = range(len(names))
    ax.barh(y, vals, color=colors, edgecolor="#222", linewidth=0.4)
    ax.set_yticks(list(y))
    ax.set_yticklabels(names)
    ax.set_xlim(0, 1.0)
    ax.invert_yaxis()
    for i, v in enumerate(vals):
        ax.text(v + 0.01, i, f"{v:.2f}", va="center", fontsize=8)


def _render_dimension_breakdown(ax, spec: FigureSpec) -> None:
    """data = {'dimensions': {'name': score, ...}}"""
    return _render_radar(ax, FigureSpec(
        figure_type=FigureType.RADAR,
        title=spec.title,
        x_label=spec.x_label,
        y_label=spec.y_label,
        data={
            "axes": list(spec.data.get("dimensions", {}).keys()),
            "series": {"Score": list(spec.data.get("dimensions", {}).values())},
        },
    ))


def _render_cost_breakdown(ax, spec: FigureSpec) -> None:
    """data = {'stages': [str], 'cost_usd': [float]}"""
    stages = spec.data.get("stages", [])
    costs = spec.data.get("cost_usd", [])
    colors = humanovo_gradient(len(stages))
    ax.bar(stages, costs, color=colors, edgecolor="black", linewidth=0.4)
    ax.tick_params(axis="x", rotation=30)
    for i, c in enumerate(costs):
        ax.text(i, c + 0.002, f"${c:.3f}", ha="center", fontsize=7)


def _render_evidence_landscape(ax, spec: FigureSpec) -> None:
    """data = {'year': [...], 'relevance': [...], 'pmid': [...]}"""
    years = spec.data.get("year", [])
    rel = spec.data.get("relevance", [])
    pmids = spec.data.get("pmid", [])
    if not years:
        return
    ax.scatter(years, rel, s=30, alpha=0.75,
               c=_palette(spec, 1)[0], edgecolor="#222", linewidth=0.4)
    for pm, y, r in zip(pmids, years, rel):
        if r >= 0.8:
            ax.annotate(str(pm), (y, r), xytext=(3, 3),
                        textcoords="offset points", fontsize=6)


def _render_translational_timeline(ax, spec: FigureSpec) -> None:
    """data = {'phases': [{'name': str, 'start': int, 'end': int, 'status': str}, ...]}"""
    phases = spec.data.get("phases", [])
    if not phases:
        return
    colors = humanovo_gradient(len(phases))
    for i, p in enumerate(phases):
        start = p.get("start", 0)
        end = p.get("end", start + 1)
        ax.barh(i, end - start, left=start, color=colors[i],
                edgecolor="#222", linewidth=0.5)
        ax.text((start + end) / 2, i, p.get("name", ""),
                ha="center", va="center", fontsize=8, color="white", fontweight="bold")
    ax.set_yticks(list(range(len(phases))))
    ax.set_yticklabels([p.get("name", "") for p in phases])
    ax.invert_yaxis()
