"""
Research Paper Generation Service — v7 (Eight-Model Discovery Pipeline)

Generates FDA/R&D-grade, fully AI-driven research papers from discovery results.

Key features:
- ALL sections generated by LLMs — maxed out token capacity per model
- 8 discovery models:
  Bedrock:     Constant AI Explorer     (32K out, synthesis + exploration)
  Azure AI:    Grok-4-1-Fast       (fast reasoning + molecular mechanisms)
  Azure AI:    Mistral-Large-3     (32K out, critical analysis + validation)
  Azure OpenAI: GPT-4o            (16K out, editorial synthesis, GA 2024-11-20)
  Azure AI:    Cohere Command A    (4K out, 256K context, RAG literature review)
  Azure OpenAI: o3-mini           (reasoning + QA validation, 2.5M TPM / 250 RPM, GA)
  Azure OpenAI: GPT-4.1           (general purpose + introduction, 50K TPM / 50 RPM, GA)
  Azure OpenAI: GPT-4.1           (abstract + deep analysis, 50K TPM / 50 RPM, GA)
- FDA/R&D grade output: cover page, TOC, numbered citations, references
- Content includes: flowcharts, mechanism diagrams, formulas, tables
- Dynamic Table of Contents with section anchors
- Plotly-based interactive charts (JSON specs for frontend rendering)
- Real citation validation via PubMed API (no hallucinated DOIs)
- 12-15+ page minimum output using all published substances
- 30-minute hard timeout with failure on exceed
- Low temperature (0.15-0.3) for factual accuracy — NO HALLUCINATION
- top_p = 0.9 across all models for controlled diversity
- Phase 4: QA Validation (o3-mini) + Editorial Review (GPT-4o) + Reasoning Review (o3-mini) + Analytical Review (GPT-4.1)

All content is real-time AI generated. Zero hardcoded templates.
"""

import asyncio
import json
import time
from datetime import datetime
from typing import Any, Optional
from uuid import uuid4

from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)

# Maximum paper generation time: 30 minutes
PAPER_GENERATION_TIMEOUT_SECONDS = 1800


class ResearchPaper:
    """A generated research paper from discovery results."""

    def __init__(
        self,
        disease: str,
        discovery_type: str,
        hypotheses: list[dict[str, Any]],
        stats: dict[str, Any],
        external_factors: list[dict[str, Any]] = None,
    ):
        self.id = str(uuid4())
        self.disease = disease
        self.discovery_type = discovery_type
        self.hypotheses = hypotheses
        self.stats = stats
        self.external_factors = external_factors or []
        self.created_at = datetime.utcnow()
        self.sections: dict[str, str] = {}
        self.references: list[dict[str, str]] = []
        self.tables: list[dict[str, Any]] = []
        self.figures: list[dict[str, Any]] = []
        self.toc: list[dict[str, Any]] = []
        self.plotly_figures: list[dict[str, Any]] = []
        self.generation_time_seconds: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "disease": self.disease,
            "discovery_type": self.discovery_type,
            "created_at": self.created_at.isoformat(),
            "toc": self.toc,
            "sections": self.sections,
            "references": self.references,
            "tables": self.tables,
            "figures": self.figures,
            "plotly_figures": self.plotly_figures,
            "metadata": {
                "total_hypotheses": len(self.hypotheses),
                "total_agents": self.stats.get("total_agents", 0),
                "runtime_seconds": self.stats.get("runtime_seconds", 0),
                "best_confidence": self.stats.get("current_best_confidence", 0),
                "models_used": self.stats.get("models_active", []),
                "external_factors_count": len(self.external_factors),
                "generation_time_seconds": self.generation_time_seconds,
            },
        }


class CitationValidator:
    """Validates citations against PubMed to prevent hallucinated DOIs."""

    def __init__(self):
        self._validated_cache: dict[str, dict] = {}

    async def search_pubmed(self, query: str, max_results: int = 3) -> list[dict[str, str]]:
        """Search PubMed for real citations matching a query."""
        try:
            import aiohttp
            base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
            email = settings.PUBMED_EMAIL

            # Search for PMIDs
            search_url = f"{base_url}/esearch.fcgi"
            params = {
                "db": "pubmed",
                "term": query,
                "retmax": max_results,
                "retmode": "json",
                "email": email,
            }

            async with aiohttp.ClientSession() as session:
                async with session.get(search_url, params=params, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                    if resp.status != 200:
                        return []
                    data = await resp.json()
                    pmids = data.get("esearchresult", {}).get("idlist", [])

                if not pmids:
                    return []

                # Fetch citation details
                fetch_url = f"{base_url}/esummary.fcgi"
                fetch_params = {
                    "db": "pubmed",
                    "id": ",".join(pmids),
                    "retmode": "json",
                    "email": email,
                }

                async with session.get(fetch_url, params=fetch_params, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                    if resp.status != 200:
                        return []
                    summary = await resp.json()

                citations = []
                results = summary.get("result", {})
                for pmid in pmids:
                    article = results.get(pmid, {})
                    if not article or pmid == "uids":
                        continue

                    authors_list = article.get("authors", [])
                    first_author = authors_list[0]["name"] if authors_list else "Unknown"
                    et_al = " et al." if len(authors_list) > 1 else ""

                    year = article.get("pubdate", "")[:4]
                    title = article.get("title", "")
                    journal = article.get("fulljournalname", article.get("source", ""))
                    doi_ids = [eid for eid in article.get("articleids", []) if eid.get("idtype") == "doi"]
                    doi = doi_ids[0]["value"] if doi_ids else ""

                    citation = {
                        "pmid": pmid,
                        "text": f"{first_author}{et_al} ({year}). {title} {journal}.",
                        "doi": f"https://doi.org/{doi}" if doi else "",
                        "title": title,
                        "year": year,
                        "journal": journal,
                        "verified": True,
                    }
                    citations.append(citation)
                    self._validated_cache[pmid] = citation

                return citations

        except Exception as e:
            logger.warning(f"PubMed search failed for '{query}': {e}")
            return []

    async def validate_and_collect_citations(
        self, disease: str, hypotheses: list[dict[str, Any]], external_factors: list[dict[str, Any]],
    ) -> list[dict[str, str]]:
        """Collect real, validated citations for the paper across multiple topics."""
        all_citations = []
        seen_pmids = set()

        # Build search queries from paper content
        queries = [
            f"{disease} treatment therapy",
            f"{disease} pathophysiology mechanisms",
            f"{disease} clinical trials 2024 2025",
            f"multi-model AI drug discovery",
            f"large language models biomedical research",
        ]

        # Add hypothesis-specific queries
        for h in hypotheses[:10]:
            title = h.get("title", "")
            if title:
                queries.append(f"{disease} {title[:60]}")

        # Add external factor queries
        factor_names = [f.get("name", "") for f in external_factors[:5] if f.get("name")]
        for name in factor_names:
            queries.append(f"{name} {disease} therapeutic effect")

        # Run PubMed searches in parallel batches
        tasks = [self.search_pubmed(q, max_results=2) for q in queries]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        ref_id = 1
        for result in results:
            if isinstance(result, Exception):
                continue
            for citation in result:
                pmid = citation.get("pmid", "")
                if pmid and pmid not in seen_pmids:
                    seen_pmids.add(pmid)
                    citation["id"] = str(ref_id)
                    all_citations.append(citation)
                    ref_id += 1

        logger.info(f"Validated {len(all_citations)} real citations from PubMed")
        return all_citations


class PaperGenerationService:
    """
    Generates fully AI-driven research papers using all 4 models in parallel.
    No template fallbacks — every section is LLM-generated.
    """

    def __init__(self):
        self._llm = None
        self._citation_validator = CitationValidator()

    async def _get_llm(self):
        if self._llm is None:
            try:
                from app.agents.discovery_orchestrator import MultiModelLLM, TokenPool
                pool = TokenPool()
                self._llm = MultiModelLLM(pool)
                await self._llm.initialize()
            except Exception as e:
                logger.error(f"LLM initialization failed for paper generation: {e}")
                raise RuntimeError(f"LLM required for paper generation but unavailable: {e}")
        return self._llm

    async def generate_paper(
        self,
        disease: str,
        discovery_type: str,
        hypotheses: list[dict[str, Any]],
        stats: dict[str, Any],
        external_factors: list[dict[str, Any]] = None,
    ) -> ResearchPaper:
        """Generate a full research paper. Fails if exceeds 30-minute timeout."""
        start_time = time.time()

        paper = ResearchPaper(
            disease=disease,
            discovery_type=discovery_type,
            hypotheses=hypotheses,
            stats=stats,
            external_factors=external_factors,
        )

        try:
            await asyncio.wait_for(
                self._generate_all_sections(paper),
                timeout=PAPER_GENERATION_TIMEOUT_SECONDS,
            )
        except asyncio.TimeoutError:
            elapsed = time.time() - start_time
            raise RuntimeError(
                f"Paper generation exceeded 30-minute timeout ({elapsed:.0f}s elapsed). "
                f"Completed sections: {list(paper.sections.keys())}"
            )

        paper.generation_time_seconds = time.time() - start_time
        logger.info(
            f"Generated research paper '{paper.sections.get('title', 'Untitled')}' "
            f"in {paper.generation_time_seconds:.1f}s with {len(paper.tables)} tables, "
            f"{len(paper.plotly_figures)} Plotly figures, {len(paper.references)} verified references"
        )
        return paper

    async def _generate_all_sections(self, paper: ResearchPaper) -> None:
        """Generate all paper content using 6 models in 4 parallel phases."""
        llm = await self._get_llm()
        from app.agents.discovery_orchestrator import ModelType

        # Build rich hypothesis context for all models
        hyp_context = self._build_hypothesis_context(paper)
        substance_context = self._build_substance_context(paper)

        # Phase 1: Parallel generation of independent sections across 6 models
        # Constant AI Explorer: Title | GPT-4.1: Abstract, Intro | Constant AI Explorer: Methods | Cohere: Disease Background, Literature Review
        phase1_tasks = {
            "title": self._generate_title_ai(llm, paper),
            "abstract": self._generate_abstract_ai(llm, paper, hyp_context),
            "introduction": self._generate_introduction_ai(llm, paper, hyp_context),
            "disease_background": self._generate_disease_background_ai(llm, paper),
            "literature_review": self._generate_literature_review_ai(llm, paper, hyp_context),
            "methods": self._generate_methods_ai(llm, paper),
            "citations": self._citation_validator.validate_and_collect_citations(
                paper.disease, paper.hypotheses, paper.external_factors,
            ),
        }

        phase1_results = await asyncio.gather(
            *[asyncio.create_task(coro) for coro in phase1_tasks.values()],
            return_exceptions=True,
        )

        for (key, _), result in zip(phase1_tasks.items(), phase1_results):
            if isinstance(result, Exception):
                logger.error(f"Phase 1 section '{key}' failed: {result}")
                raise RuntimeError(f"Paper generation failed: section '{key}' error: {result}")
            if key == "citations":
                paper.references = result
            else:
                paper.sections[key] = result

        # Phase 2: Context-dependent sections (use phase 1 content)
        # Constant AI Explorer: Results | Grok-Fast: Molecular Mechanisms | Mistral: External Factors
        phase2_tasks = {
            "results_overview": self._generate_results_overview_ai(llm, paper, hyp_context),
            "hypothesis_analyses": self._generate_hypothesis_deep_analyses(llm, paper),
            "external_factors_analysis": self._generate_external_factors_ai(llm, paper, substance_context),
            "molecular_mechanisms": self._generate_molecular_mechanisms_ai(llm, paper, hyp_context),
            "translational_roadmap": self._generate_translational_roadmap_ai(llm, paper, hyp_context),
        }

        phase2_results = await asyncio.gather(
            *[asyncio.create_task(coro) for coro in phase2_tasks.values()],
            return_exceptions=True,
        )

        for (key, _), result in zip(phase2_tasks.items(), phase2_results):
            if isinstance(result, Exception):
                logger.error(f"Phase 2 section '{key}' failed: {result}")
                raise RuntimeError(f"Paper generation failed: section '{key}' error: {result}")
            paper.sections[key] = result

        # Phase 2.5: Embedding grounding — validate all generated content
        try:
            from app.rag.grounding import get_grounding_engine
            grounder = get_grounding_engine()
            await grounder.initialize()

            # Ingest all generated section content as evidence for cross-validation
            all_content = "\n\n".join(paper.sections.values())
            await grounder.ingest_evidence(all_content)

            # Ground each section's claims against the evidence pool
            for idx, (section_key, section_text) in enumerate(paper.sections.items()):
                try:
                    grounding_result = await grounder.ground_stage_output(
                        stage_output=section_text,
                        stage_num=idx,
                    )
                    if grounding_result:
                        logger.info(f"[EMBEDDING] Paper section '{section_key}' grounded: "
                                    f"score={getattr(grounding_result, 'overall_score', 'N/A')}")
                except Exception as ge:
                    logger.warning(f"[EMBEDDING] Section '{section_key}' grounding failed (non-fatal): {ge}")

            logger.info(f"[EMBEDDING] Paper grounding validation complete for {len(paper.sections)} sections")
        except Exception as e:
            logger.warning(f"[EMBEDDING] Paper grounding phase failed (non-fatal): {e}")

        # Phase 3: Synthesis sections + visualizations
        # GPT-4o: Discussion, Conclusion | Mistral: Limitations | Plotly + Tables
        phase3_tasks = {
            "discussion": self._generate_discussion_ai(llm, paper, hyp_context),
            "limitations_future": self._generate_limitations_future_ai(llm, paper),
            "conclusion": self._generate_conclusion_ai(llm, paper, hyp_context),
            "plotly_figures": self._generate_plotly_figures(paper),
            "tables": self._generate_tables(paper),
        }

        phase3_results = await asyncio.gather(
            *[asyncio.create_task(coro) for coro in phase3_tasks.values()],
            return_exceptions=True,
        )

        for (key, _), result in zip(phase3_tasks.items(), phase3_results):
            if isinstance(result, Exception):
                logger.error(f"Phase 3 section '{key}' failed: {result}")
                raise RuntimeError(f"Paper generation failed: section '{key}' error: {result}")
            if key == "plotly_figures":
                paper.plotly_figures = result
            elif key == "tables":
                paper.tables = result
            else:
                paper.sections[key] = result

        # Phase 4: QA Validation + Editorial Review + Reasoning Review + Analytical Review
        phase4_tasks = {
            "qa_validation": self._generate_qa_validation(llm, paper),
            "editorial_review": self._generate_editorial_review(llm, paper),
            "reasoning_review": self._generate_reasoning_review(llm, paper),
            "analytical_review": self._generate_analytical_review(llm, paper),
        }

        phase4_results = await asyncio.gather(
            *[asyncio.create_task(coro) for coro in phase4_tasks.values()],
            return_exceptions=True,
        )

        for (key, _), result in zip(phase4_tasks.items(), phase4_results):
            if isinstance(result, Exception):
                # Phase 4 is non-fatal — log but don't crash
                logger.warning(f"Phase 4 '{key}' failed (non-fatal): {result}")
            else:
                paper.sections[key] = result

        # Build dynamic TOC from generated sections
        paper.toc = self._build_dynamic_toc(paper)

    def _build_hypothesis_context(self, paper: ResearchPaper) -> str:
        """Build a rich context string from all hypotheses for LLM prompts."""
        lines = []
        for i, h in enumerate(paper.hypotheses[:20], 1):
            conf = h.get("confidence", 0)
            entry = (
                f"Hypothesis {i}: {h.get('title', 'Untitled')}\n"
                f"  Confidence: {conf:.1%} | Model: {h.get('model_used', 'unknown')}\n"
                f"  Mechanism: {h.get('mechanism', 'Not specified')}\n"
                f"  Description: {h.get('description', 'N/A')}\n"
                f"  Validated: {'Yes' if h.get('validated') else 'No'}"
            )
            # Include evidence and risks if available
            evidence = h.get("evidence_summary", [])
            if evidence:
                entry += f"\n  Evidence: {'; '.join(str(e)[:100] for e in evidence[:3])}"
            risks = h.get("risks", [])
            if risks:
                entry += f"\n  Risks: {'; '.join(str(r)[:100] for r in risks[:3])}"
            validation_steps = h.get("validation_steps", [])
            if validation_steps:
                entry += f"\n  Next Steps: {'; '.join(str(v)[:100] for v in validation_steps[:3])}"
            lines.append(entry)
        return "\n\n".join(lines)

    def _build_substance_context(self, paper: ResearchPaper) -> str:
        """Build context from external factors/substances."""
        if not paper.external_factors:
            return "No external factors specified."

        by_category: dict[str, list] = {}
        for f in paper.external_factors:
            cat = f.get("category", "other")
            by_category.setdefault(cat, []).append(f)

        lines = []
        for cat, factors in by_category.items():
            names = [f.get("name", "Unknown") for f in factors]
            lines.append(f"{cat.title()}: {', '.join(names)}")

        return "\n".join(lines)

    # =========================================================================
    # AI-Generated Sections — Each uses a specific model for its strengths
    # =========================================================================

    async def _generate_title_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        top_hyp = paper.hypotheses[0] if paper.hypotheses else {}
        type_label = {
            "cure": "Therapeutic Strategies",
            "prevention": "Prevention Strategies",
            "treatment": "Therapeutic Strategies",
            "biomarker": "Biomarker Discovery",
            "drug_repurposing": "Drug Repurposing Candidates",
            "combination_therapy": "Combination Therapy Approaches",
        }.get(paper.discovery_type, "Therapeutic Strategies")

        prompt = f"""Generate a precise, FDA/R&D publication-ready title for a research paper.

Disease: {paper.disease}
Discovery type: {type_label}
Top finding: {top_hyp.get('title', 'Multi-model AI discovery')}
Total hypotheses: {len(paper.hypotheses)}
Models used: 8-model AI pipeline (Constant AI Explorer, GPT-4.1, Mistral-Large-3, GPT-4o, Cohere Command A, o3-mini, Grok-4-1-Fast, GPT-4.1)

Return ONLY the title text, no quotes, no explanation. The title should be concise (under 200 characters), scientifically precise, and reflect the multi-model AI approach. Format as: "Title — by Humanovo"."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.2, max_tokens=500)

    async def _generate_abstract_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a comprehensive scientific abstract (350-450 words) for an FDA/R&D-grade research paper.

Disease under investigation: {paper.disease}
Discovery type: {paper.discovery_type}
Total hypotheses generated: {len(paper.hypotheses)}
Best confidence achieved: {paper.stats.get('current_best_confidence', 0):.1%}
Total agents deployed: {paper.stats.get('total_agents', 0)}
Models used: 8-model pipeline — Constant AI Explorer (exploration + synthesis), GPT-4.1 (abstract + introduction), Mistral-Large-3 (critical analysis), GPT-4o (editorial synthesis), Cohere Command A (RAG literature review), o3-mini (QA validation + reasoning), Grok-4-1-Fast (molecular mechanisms), GPT-4.1 (analytical review)
Runtime: {paper.stats.get('runtime_seconds', 0):.0f} seconds
External factors analyzed: {len(paper.external_factors)}
High confidence discoveries (>=70%): {paper.stats.get('high_confidence_discoveries', 0)}

Top 5 hypotheses:
{chr(10).join(f"- {h.get('title','N/A')} (confidence: {h.get('confidence',0):.1%})" for h in paper.hypotheses[:5])}

Structure the abstract with these labeled sections:
Background: (disease context and need for AI-driven discovery)
Methods: (multi-model parallel agent system, knowledge graph exploration, external factor simulation)
Results: (key findings, confidence levels, novel mechanisms identified)
Conclusions: (significance, translational potential, next steps)

IMPORTANT: This is an FDA/R&D-grade document. Be scientifically precise, cite specific molecular targets, pathways, and mechanisms. Do NOT hallucinate any data or statistics — only report what is provided above. Write in formal academic style."""

        return await llm.generate(ModelType.GPT_41, prompt, temperature=0.2, max_tokens=16_384)

    async def _generate_introduction_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a comprehensive Introduction section (800-1200 words) for a research paper about AI-driven discovery of {paper.discovery_type} strategies for {paper.disease}.

This must cover ALL of the following in depth:

1. DISEASE EPIDEMIOLOGY AND BURDEN (200+ words)
   - Global prevalence, incidence, mortality statistics for {paper.disease}
   - Economic burden and quality of life impact
   - Current demographic trends

2. CURRENT THERAPEUTIC LANDSCAPE (200+ words)
   - Existing approved treatments and their mechanisms
   - Standard of care protocols
   - Key limitations: efficacy gaps, resistance, side effects, cost

3. AI AND MULTI-MODEL SYSTEMS IN DRUG DISCOVERY (200+ words)
   - Evolution from single-model to multi-model AI systems
   - Advantages of parallel reasoning with diverse architectures
   - Recent breakthroughs in AI-assisted drug discovery
   - How our 8-model approach (Constant AI Explorer for synthesis, GPT-4.1 for abstract/introduction, Mistral-Large-3 for critical analysis, GPT-4o for editorial synthesis, Cohere Command A for literature RAG, o3-mini for QA validation, Grok-4-1-Fast for molecular mechanisms, GPT-4.1 for analytical review) advances the field

4. ROLE OF EXTERNAL FACTORS (150+ words)
   - Nutrients, chemicals, drugs, natural compounds, trace elements in disease modulation
   - Why holistic factor analysis matters
   - External factors analyzed: {self._build_substance_context(paper)}

5. STUDY OBJECTIVES (100+ words)
   - Specific aims of this investigation
   - How {paper.stats.get('total_agents', 0)} agents were deployed
   - What makes this approach novel

IMPORTANT: This is an FDA/R&D-grade document. Include specific molecular formulas where relevant (e.g., C₂₁H₃₀O₂ for progesterone). Reference specific receptor types (e.g., NMDA, GABA-A, TLR4). Do NOT hallucinate — only state facts that are well-established in biomedical literature.

Write in formal academic style with clear paragraph transitions. Use specific scientific terminology. Do NOT include section headers — write flowing paragraphs."""

        return await llm.generate(ModelType.GPT_41, prompt, temperature=0.2, max_tokens=16_384)

    async def _generate_disease_background_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a detailed Disease Background section (600-800 words) for {paper.disease}.

Cover in depth:
1. PATHOPHYSIOLOGY: Molecular and cellular mechanisms driving {paper.disease}
   - Key genes, proteins, and signaling pathways involved
   - Cellular processes disrupted (apoptosis, metabolism, immune evasion, etc.)
   - Tissue and organ-level effects

2. GENETIC LANDSCAPE: Known genetic associations
   - Key mutations, polymorphisms, and risk variants
   - Epigenetic modifications relevant to disease
   - Pharmacogenomic considerations

3. ENVIRONMENTAL AND LIFESTYLE FACTORS
   - Known risk factors and protective factors
   - Nutrient deficiencies or excesses linked to disease
   - Chemical exposures and their mechanisms

4. BIOMARKERS AND DIAGNOSIS
   - Current diagnostic approaches
   - Known biomarkers and their limitations
   - Emerging diagnostic technologies

IMPORTANT: This is an FDA/R&D-grade document. Include specific gene names (e.g., TP53, BRCA1, EGFR), protein names, pathway identifiers (e.g., PI3K/AKT/mTOR, MAPK/ERK, Wnt/β-catenin). Include molecular formulas for key compounds. Do NOT hallucinate — only state well-established biomedical facts.

Write in formal academic style. Be scientifically precise. Do NOT use section headers — write flowing paragraphs with logical transitions."""

        return await llm.generate(ModelType.COHERE_COMMAND_A, prompt, temperature=0.2, max_tokens=4_096)

    async def _generate_literature_review_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        """Generate literature review using Cohere Command A (256K context, RAG-optimized)."""
        from app.agents.discovery_orchestrator import ModelType

        top_hyps = paper.hypotheses[:10]
        prompt = f"""Write a comprehensive Literature Review section (800-1200 words) for an FDA/R&D-grade research paper on {paper.disease}.

This section should synthesize the existing body of published research relevant to the hypotheses generated by the AI discovery pipeline.

DISEASE: {paper.disease}
DISCOVERY TYPE: {paper.discovery_type}

TOP HYPOTHESES TO CONTEXTUALIZE:
{chr(10).join(f"- {h.get('title','N/A')} (confidence: {h.get('confidence',0):.1%}, mechanism: {h.get('mechanism','N/A')})" for h in top_hyps)}

EXTERNAL FACTORS ANALYZED:
{self._build_substance_context(paper)}

Cover ALL of the following areas in depth:

1. EXISTING THERAPEUTIC APPROACHES (200+ words)
   - Current standard of care for {paper.disease}
   - Recent clinical trial results (Phase I-III) for novel therapies
   - Approved drugs and their mechanisms of action
   - Treatment gaps and unmet medical needs

2. RELEVANT MOLECULAR TARGETS (200+ words)
   - Key targets identified in recent literature that align with our hypotheses
   - Receptor families, kinases, transcription factors under investigation
   - Comparison of target validation status across studies

3. AI IN BIOMEDICAL DISCOVERY (200+ words)
   - Recent publications on AI/ML-driven drug discovery
   - Multi-model and ensemble approaches in computational biology
   - Knowledge graph-based discovery methods
   - Comparison of AI-generated hypotheses vs. traditional approaches

4. EXTERNAL FACTOR INTERACTIONS (200+ words)
   - Published evidence for nutrient-disease interactions
   - Natural compound studies relevant to {paper.disease}
   - Drug-nutrient interaction literature
   - Epidemiological studies on environmental factors

IMPORTANT GUIDELINES:
- Reference specific published studies by first author and year where possible
- Include journal names and key findings for major references
- Organize by theme, not chronologically
- Identify gaps in current literature that this study addresses
- Do NOT hallucinate citations — only reference well-established findings
- Write in formal academic style with flowing paragraphs"""

        return await llm.generate(ModelType.COHERE_COMMAND_A, prompt, temperature=0.2, max_tokens=4_096)

    async def _generate_methods_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        agents_by_role = paper.stats.get("agents_by_role", {})
        token_stats = paper.stats.get("token_pool_stats", {})

        ext_factors_summary = ""
        if paper.external_factors:
            categories = {}
            for f in paper.external_factors:
                cat = f.get("category", "other")
                categories.setdefault(cat, []).append(f.get("name", "Unknown"))
            ext_lines = [f"  {cat}: {', '.join(names)}" for cat, names in categories.items()]
            ext_factors_summary = "\n".join(ext_lines)

        prompt = f"""Write a comprehensive Methods section (1000-1400 words) for a research paper about multi-model AI discovery.

PLATFORM DETAILS:
- Platform: Humanovo Multi-Model Discovery System
- Total agents: {paper.stats.get('total_agents', 0)}
- Agent roles and distribution: {json.dumps(agents_by_role)}
- Batch size: {settings.TOKEN_POOL_AGENT_BATCH_SIZE} agents per dispatch cycle

MODELS USED (describe each architecture and role):
1. Constant AI Explorer — Exploration + synthesis, 200K context, temperature 0.2-0.4
2. GPT-4.1 (via Azure OpenAI) — Abstract and introduction generation, 16K output, temperature 0.2
3. Mistral-Large-3 (via Azure AI) — Critical analysis + validation, 32K output, temperature 0.2-0.3
4. GPT-4o (via Azure OpenAI) — Editorial synthesis + review, 131K context → 16K output, temperature 0.25
5. Cohere Command A (via Azure AI) — RAG literature review, 256K context → 4K output, temperature 0.2
6. o3-mini (via Azure OpenAI) — QA validation pass, deep reasoning, temperature 0.15
7. o3-mini (OpenAI, via Azure OpenAI) — Deep reasoning review, 2.5M TPM / 250 RPM, temperature 0.2
8. GPT-4.1 (OpenAI, via Azure OpenAI) — Analytical review, 50K TPM / 50 RPM, temperature 0.25

TOKEN POOL MANAGEMENT:
- Max concurrent requests per model: {settings.TOKEN_POOL_MAX_CONCURRENT_REQUESTS}
- Global rate limit: {settings.TOKEN_POOL_MAX_TOKENS_PER_MINUTE:,} tokens/minute
- Backoff strategy: exponential with base {settings.TOKEN_POOL_RETRY_BACKOFF_BASE}

KNOWLEDGE GRAPH:
- Entities explored from Neo4j biological knowledge graph
- Neighborhood depth: 2 hops, 50 connections per entity
- Synthetic fallback graph with genes, proteins, drugs, nutrients, pathways

AGENT ARCHITECTURE:
- Explorer agents (40%): Broad pathway discovery
- Reasoner agents (25%): Deep causal chain analysis
- Validator agents (15%): Evidence quality verification
- Synthesizer agents (10%): Cross-hypothesis integration
- Critic agents (10%): Flaw and risk identification

EXTERNAL FACTORS SIMULATED:
{ext_factors_summary if ext_factors_summary else "All relevant nutrients, chemicals, drugs, compounds, elements analyzed"}

CONFIDENCE SCORING FORMULA:
- Direct clinical evidence: weight 0.40
- Mechanistic plausibility: weight 0.25
- Preclinical evidence: weight 0.20
- Computational predictions: weight 0.10
- Expert consensus: weight 0.05

PAPER GENERATION:
- All sections generated by AI models in parallel (no templates)
- Citations validated against PubMed API in real-time
- Plotly visualizations generated from actual data
- 30-minute hard timeout on generation

IMPORTANT: This is an FDA/R&D-grade methods section. Include:
- Exact model identifiers and API versions
- Precise temperature and top_p parameters for each model
- Token pool configuration numbers
- Confidence scoring formula with exact weights
- Do NOT include ASCII art flowcharts — pipeline diagrams are rendered as SVG figures separately
- Describe the pipeline architecture in detailed scientific prose instead

Write as formal Methods text. Use subsections with ### headers for: Multi-Model Discovery Platform, Agent Architecture, Token Pool Management, Knowledge Graph Integration, External Factor Simulation, Confidence Scoring, Research Paper Generation. Be technically precise. Do NOT hallucinate parameters — use only the values provided."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.15, max_tokens=32_768)

    async def _generate_results_overview_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write the Results Overview section (400-600 words) for a research paper.

Discovery run statistics:
- Disease: {paper.disease}
- Total agents: {paper.stats.get('total_agents', 0)}
- Pathways explored: {paper.stats.get('paths_explored', 0):,}
- Runtime: {paper.stats.get('runtime_seconds', 0):.0f} seconds
- Total hypotheses generated: {len(paper.hypotheses)}
- High confidence (>=70%): {paper.stats.get('high_confidence_discoveries', 0)}
- Best confidence: {paper.stats.get('current_best_confidence', 0):.1%}
- Models active: {', '.join(paper.stats.get('models_active', []))}

Token pool usage: {json.dumps(paper.stats.get('token_pool_stats', {}))}
Learning memory stats: {json.dumps(paper.stats.get('learning_stats', {}))}

Summarize the overall discovery results:
1. Scale of exploration (paths, agents, runtime)
2. Distribution of confidence scores across hypotheses
3. Performance comparison across models
4. Learning system effectiveness (low-value paths skipped, high-value amplified)
5. Token efficiency across models

Write in formal results style. Report numbers precisely. No interpretation — save that for Discussion."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.25, max_tokens=32_768)

    async def _generate_hypothesis_deep_analyses(self, llm, paper: ResearchPaper) -> str:
        """Generate detailed analysis of each hypothesis using different models in parallel."""
        from app.agents.discovery_orchestrator import ModelType

        analyses = []
        # Distribute hypotheses across discovery models for diverse analysis perspectives
        model_cycle = [ModelType.CLAUDE_OPUS, ModelType.GPT_41, ModelType.MISTRAL_LARGE_3]

        async def analyze_single(idx: int, hyp: dict) -> str:
            model = model_cycle[idx % len(model_cycle)]
            prompt = f"""Write a detailed FDA/R&D-grade scientific analysis (400-600 words) for this hypothesis about {paper.disease}:

Hypothesis: {hyp.get('title', 'Untitled')}
Description: {hyp.get('description', 'N/A')}
Mechanism: {hyp.get('mechanism', 'Not specified')}
Confidence: {hyp.get('confidence', 0):.1%}
Model used for discovery: {hyp.get('model_used', 'unknown')}
External factor interactions: {json.dumps(hyp.get('external_factors', []))}

Cover in your analysis:
1. Scientific rationale and biological plausibility with specific pathway references
2. Detailed mechanism of action at molecular level — describe the full signaling cascade in scientific prose:
   drug/compound binding to target receptor, signaling cascade activation, transcription factor regulation,
   downstream gene expression changes, cellular response, and therapeutic phenotype
3. Existing supporting evidence from literature (reference specific studies)
4. Potential therapeutic modalities (small molecule, biologic, gene therapy, etc.)
5. Key risks, toxicity concerns, and off-target effects
6. Required experimental validation steps (in vitro, in vivo, clinical phases)
7. Patient population considerations and stratification
8. Comparison with existing treatments for {paper.disease}

Include for EACH hypothesis:
- Molecular formula of key compounds (e.g., C₂₁H₃₀O₂)
- IC50/Ki/Kd values where known (e.g., IC₅₀ = 2.3 nM)
- Dose-response relationship description
- Do NOT use ASCII art or text diagrams — describe pathways in prose with specific gene/protein names

IMPORTANT: Do NOT hallucinate data. Only state well-established biomedical facts.

Write as formal FDA/R&D-grade scientific text. Be specific, not generic."""

            return await llm.generate(model, prompt, temperature=0.2, max_tokens=65_536)

        # Process in batches of 4 (one per model)
        for batch_start in range(0, min(len(paper.hypotheses), 20), 4):
            batch = paper.hypotheses[batch_start:batch_start + 4]
            batch_tasks = [
                analyze_single(batch_start + i, h)
                for i, h in enumerate(batch)
            ]
            batch_results = await asyncio.gather(*batch_tasks, return_exceptions=True)
            for i, result in enumerate(batch_results):
                idx = batch_start + i
                hyp = paper.hypotheses[idx]
                if isinstance(result, Exception):
                    analyses.append(
                        f"### Hypothesis {idx + 1}: {hyp.get('title', 'Untitled')}\n\n"
                        f"**Confidence**: {hyp.get('confidence', 0):.1%} | "
                        f"**Model**: {hyp.get('model_used', 'unknown')}\n\n"
                        f"Analysis generation encountered an error: {result}\n\n"
                        f"**Mechanism**: {hyp.get('mechanism', 'Not specified')}\n\n"
                        f"{hyp.get('description', 'No description available.')}"
                    )
                else:
                    analyses.append(
                        f"### Hypothesis {idx + 1}: {hyp.get('title', 'Untitled')}\n\n"
                        f"**Confidence**: {hyp.get('confidence', 0):.1%} | "
                        f"**Model**: {hyp.get('model_used', 'unknown')} | "
                        f"**Validated**: {'Yes' if hyp.get('validated') else 'Pending'}\n\n"
                        f"{result}"
                    )

        return "\n\n---\n\n".join(analyses)

    async def _generate_external_factors_ai(self, llm, paper: ResearchPaper, substance_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        if not paper.external_factors:
            prompt = f"""Write a section (400-600 words) about the role of external factors in {paper.disease} treatment.

Since no specific external factors were configured for this run, discuss:
1. Key nutrients known to affect {paper.disease} (vitamins, minerals, amino acids)
2. Natural compounds with evidence for {paper.disease} (curcumin, resveratrol, quercetin, EGCG, etc.)
3. Environmental chemicals and their disease-modulating effects
4. Drug-nutrient and drug-drug interactions relevant to treatment
5. Trace elements and their roles in disease pathways

IMPORTANT: Do NOT hallucinate. Only state well-established biomedical facts. Include specific compound formulas and mechanisms.
Write as formal scientific text with specific examples and mechanisms."""

            return await llm.generate(ModelType.MISTRAL_LARGE_3, prompt, temperature=0.2, max_tokens=32_768)

        prompt = f"""Write a comprehensive External Factors Analysis section (600-1000 words) for a {paper.disease} research paper.

External factors analyzed in this study:
{substance_context}

Full factor details:
{json.dumps([{k: v for k, v in f.items()} for f in paper.external_factors[:30]], indent=2)}

For each category of factors, write a detailed analysis covering:
1. **Mechanism of interaction** with {paper.disease} pathways
2. **Synergistic effects** when combined with identified therapeutic hypotheses
3. **Antagonistic effects** that could reduce treatment efficacy
4. **Dosing considerations** and therapeutic windows
5. **Drug-nutrient interactions** and contraindications
6. **Evidence quality** for each factor's therapeutic role

Organize by category (Nutrients, Compounds, Drugs, Chemicals, Elements).

Include for each factor:
- Molecular formula and structure description (e.g., Curcumin: C₂₁H₂₀O₆, MW: 368.38)
- Mechanism of action described in prose: target receptor/enzyme, signaling pathway, cellular effect, downstream gene expression
- Known dosing ranges from literature (e.g., therapeutic window: 500-2000 mg/day)
- Drug-factor interactions described in scientific detail

IMPORTANT: Do NOT hallucinate. Only state well-established biomedical facts.
Write as formal FDA/R&D-grade scientific text. Be specific about molecular mechanisms."""

        return await llm.generate(ModelType.MISTRAL_LARGE_3, prompt, temperature=0.2, max_tokens=32_768)

    async def _generate_molecular_mechanisms_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        top_hyps = paper.hypotheses[:5]
        prompt = f"""Write a detailed Molecular Mechanisms section (600-800 words) for a {paper.disease} research paper.

Based on the top hypotheses:
{chr(10).join(f"- {h.get('title','N/A')}: {h.get('mechanism','N/A')}" for h in top_hyps)}

Describe in scientific detail:
1. The key molecular pathways implicated across all top hypotheses
2. How identified targets (genes, proteins, receptors) relate to disease pathogenesis
3. Signaling cascades that could be therapeutically modulated
4. Cross-talk between pathways identified by different hypotheses
5. How external factors (nutrients, compounds) interact with these molecular mechanisms
6. Potential resistance mechanisms and how to overcome them
7. Biomarker opportunities arising from these mechanisms

Describe all pathways in detailed scientific prose (do NOT use ASCII art or text-based diagrams — figures are rendered as SVGs separately).

Include in your prose:
- Chemical formulas for key compounds (e.g., C₂₁H₃₀O₂, IC₅₀ = 2.3 nM)
- Receptor binding descriptions: ligand-receptor complex formation and downstream signaling
- Enzyme kinetics values: Km, Kd, IC50, Ki where well-established in literature
- Feedback loop descriptions showing positive/negative regulation
- Cross-pathway interaction descriptions with specific gene/protein names

IMPORTANT: Do NOT hallucinate. Only state well-established biomedical facts. Use specific gene/protein names (with UniProt/HGNC identifiers where possible), pathway identifiers, and molecular interactions.

Write as formal FDA/R&D-grade scientific text. No headers — flowing paragraphs."""

        return await llm.generate(ModelType.GROK_FAST, prompt, temperature=0.15, max_tokens=32_768)

    async def _generate_translational_roadmap_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        """Generate comprehensive T0-T5 translational roadmap section."""
        from app.agents.discovery_orchestrator import ModelType

        # Extract any existing translational data from hypotheses
        roadmap_data = ""
        for h in paper.hypotheses[:3]:
            roadmap = h.get("translational_roadmap", {})
            if roadmap and isinstance(roadmap, dict):
                phases = roadmap.get("phases", {})
                if phases:
                    roadmap_data += f"\nHypothesis: {h.get('title', 'N/A')}\n"
                    for phase_key, phase_val in phases.items():
                        if isinstance(phase_val, dict):
                            roadmap_data += f"  {phase_key}: {phase_val.get('title', '')} — {phase_val.get('description', '')[:200]}\n"

        top_hyps = paper.hypotheses[:5]
        prompt = f"""Write a comprehensive Translational Roadmap section (1500-2500 words) for a {paper.disease} research paper.

This section covers the complete bench-to-bedside translational spectrum (T0-T5) for the top discovery hypotheses.

Top hypotheses:
{chr(10).join(f"- {h.get('title','N/A')}: {h.get('mechanism','N/A')[:200]}" for h in top_hyps)}

{f"Existing translational data from pipeline:{chr(10)}{roadmap_data}" if roadmap_data else ""}

Write DETAILED content for EACH of the following 6 translational phases:

## T0: Basic Research & Target Validation (300+ words)
- Target identification and validation experiments
- In vitro/in vivo proof-of-concept studies
- Mechanism elucidation experiments
- Key assays and model systems required
- Include specific experimental protocols and expected outcomes

## T1: Translation to Humans — Preclinical Development (300+ words)
- IND-enabling studies and GLP toxicology
- Drug formulation and delivery optimization
- Pharmacokinetic/pharmacodynamic (PK/PD) modeling
- Biomarker development for patient selection
- Regulatory pre-IND meeting strategy

## T2: Translation to Patients — Clinical Trials (300+ words)
- Phase I/II/III trial design with specific endpoints
- Patient stratification and enrollment criteria
- Adaptive trial design considerations
- Safety monitoring and DSMB plan
- Companion diagnostic development

## T3: Translation to Practice — Clinical Implementation (200+ words)
- Clinical practice guideline development
- Provider education and training programs
- Clinical decision support integration
- Health system implementation strategy
- Outcomes measurement framework

## T4: Translation to Community — Population Health (200+ words)
- Community-based implementation programs
- Health equity and access considerations
- Real-world evidence generation plan
- Patient advocacy and engagement
- Pharmacovigilance and post-market surveillance

## T5: Global Impact (200+ words)
- International regulatory strategy (EMA, PMDA, etc.)
- LMIC adaptation and technology transfer
- Global health policy recommendations
- Pandemic/endemic preparedness applications
- Global access and pricing strategy

For each phase include:
- Timeline estimates with milestones
- Budget estimates
- Key risks and mitigation strategies
- Success criteria and go/no-go decision points
- Specific regulatory requirements

Use headers (##, ###) for each phase. Include tables for timelines and budgets.
Write as formal publication-grade scientific text. Be specific to {paper.disease}.
IMPORTANT: Do NOT hallucinate. Base all recommendations on established translational science frameworks."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.25, max_tokens=32_768)

    async def _generate_discussion_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        top_titles = [h.get("title", "N/A") for h in paper.hypotheses[:5]]
        prompt = f"""Write a comprehensive Discussion section (800-1200 words) for a research paper about AI-driven discovery for {paper.disease}.

Key findings to discuss:
- Top hypotheses: {', '.join(top_titles)}
- Best confidence achieved: {paper.stats.get('current_best_confidence', 0):.1%}
- Total hypotheses: {len(paper.hypotheses)}
- Models used: 8-model pipeline (Constant AI Explorer, GPT-4.1, Mistral-Large-3, GPT-4o, Cohere Command A, o3-mini, Grok-4-1-Fast, GPT-4.1)
- External factors analyzed: {len(paper.external_factors)}
- Paths explored: {paper.stats.get('paths_explored', 0):,}

Cover ALL of the following:

1. SIGNIFICANCE OF FINDINGS (200+ words)
   - What these discoveries mean for {paper.disease} treatment
   - How they compare to existing therapeutic approaches
   - Novel mechanisms identified that were not previously known

2. MULTI-MODEL ADVANTAGE (200+ words)
   - How different models contributed different insights
   - Complementary reasoning perspectives
   - Value of parallel agent architecture vs. single-model approaches

3. EXTERNAL FACTOR INSIGHTS (150+ words)
   - Novel nutrient-disease interactions discovered
   - Drug repurposing opportunities from external factor analysis
   - Synergistic combinations identified

4. COMPARISON WITH EXISTING LITERATURE (200+ words)
   - How findings align with or diverge from published research
   - Novel contributions beyond state of the art
   - Validation status of key claims

5. TRANSLATIONAL POTENTIAL (150+ words)
   - Path from AI hypothesis to clinical application
   - Recommended experimental validations
   - Timeline and feasibility considerations

IMPORTANT: Do NOT hallucinate. Base discussion on the provided data only.
Write in formal FDA/R&D-grade academic discussion style. Be balanced — acknowledge both strengths and weaknesses."""

        return await llm.generate(ModelType.GPT_4O_AZURE, prompt, temperature=0.25, max_tokens=16_384)

    async def _generate_limitations_future_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a Limitations and Future Directions section (500-700 words) for a research paper on AI-driven {paper.disease} discovery.

Current study parameters:
- {paper.stats.get('total_agents', 0)} agents across 8 models (Constant AI Explorer, GPT-4.1, Mistral-Large-3, GPT-4o, Cohere Command A, o3-mini, Grok-4-1-Fast, GPT-4.1)
- {len(paper.hypotheses)} hypotheses generated
- {paper.stats.get('paths_explored', 0):,} paths explored
- Runtime: {paper.stats.get('runtime_seconds', 0):.0f} seconds

Cover honestly and thoroughly:

LIMITATIONS:
1. AI-generated hypotheses require experimental validation
2. Confidence scores are model-dependent and may not reflect true clinical probability
3. Knowledge graph completeness and currency limitations
4. Token pool constraints at maximum agent scale
5. Potential biases in training data of underlying models
6. Lack of wet-lab integration in current pipeline
7. External factor interactions are computationally predicted, not experimentally verified

FUTURE DIRECTIONS:
1. Integration with automated wet-lab systems for hypothesis validation
2. Expansion of knowledge graph with real-time literature monitoring
3. Addition of protein structure prediction (AlphaFold integration)
4. Multi-omics data integration (genomics, proteomics, metabolomics)
5. Clinical trial design automation based on top hypotheses
6. Federated learning across multiple institutions
7. Real-time patient data integration for personalized discovery

IMPORTANT: Do NOT hallucinate. Be honest about limitations.
Write as formal FDA/R&D-grade scientific text."""

        return await llm.generate(ModelType.MISTRAL_LARGE_3, prompt, temperature=0.25, max_tokens=32_768)

    async def _generate_conclusion_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a strong Conclusion section (300-400 words) for a research paper on AI-driven {paper.disease} discovery.

Summarize:
- {paper.stats.get('total_agents', 0)} parallel agents across 8 LLMs (Constant AI Explorer, GPT-4.1, Mistral-Large-3, GPT-4o, Cohere Command A, o3-mini, Grok-4-1-Fast, GPT-4.1) identified {len(paper.hypotheses)} hypotheses
- Best confidence: {paper.stats.get('current_best_confidence', 0):.1%}
- Top finding: {paper.hypotheses[0].get('title', 'N/A') if paper.hypotheses else 'N/A'}
- {len(paper.external_factors)} external factors integrated
- Multi-model approach with token pool management enabled unprecedented scale

End with:
1. The key take-away message for the scientific community
2. The most actionable finding for translational researchers
3. The broader implications for AI-driven drug discovery

Be concise, impactful, and forward-looking. Avoid repeating the abstract."""

        return await llm.generate(ModelType.GPT_4O_AZURE, prompt, temperature=0.3, max_tokens=16_384)

    # =========================================================================
    # Phase 4: QA Validation + Editorial Review + Reasoning Review + Analytical Review
    # =========================================================================

    async def _generate_qa_validation(self, llm, paper: ResearchPaper) -> str:
        """QA validation pass using o3-mini (reasoning model)."""
        from app.agents.discovery_orchestrator import ModelType

        # Gather key section summaries for QA review
        sections_summary = []
        for key in ["abstract", "introduction", "methods", "results_overview", "discussion", "conclusion"]:
            content = paper.sections.get(key, "")
            if content:
                # Truncate each section to stay within model input limits
                sections_summary.append(f"[{key.upper()}]: {content[:2000]}")

        prompt = f"""You are a scientific QA reviewer for an FDA/R&D-grade research paper about {paper.disease}.

Review the following paper sections for quality, accuracy, and consistency:

{chr(10).join(sections_summary)}

Total hypotheses: {len(paper.hypotheses)}
Best confidence: {paper.stats.get('current_best_confidence', 0):.1%}
PubMed-verified references: {len(paper.references)}

Perform the following QA checks:

1. INTERNAL CONSISTENCY
   - Do the results match what is claimed in the abstract?
   - Are statistics consistent across sections?
   - Are model names and parameters consistent?

2. SCIENTIFIC ACCURACY FLAGS
   - Flag any claims that appear unsupported or overstated
   - Note any missing caveats or qualifications
   - Check that confidence scores are reported consistently

3. COMPLETENESS CHECK
   - Are all key aspects of the disease covered?
   - Are methods adequately described for reproducibility?
   - Are limitations honestly addressed?

4. RECOMMENDATIONS
   - Specific improvements for each section
   - Missing content that should be added
   - Sections that need strengthening

Write your QA report as a structured assessment with clear findings and actionable recommendations. Be concise and specific."""

        return await llm.generate(ModelType.O3_MINI, prompt, temperature=0.15, max_tokens=16_384)

    async def _generate_editorial_review(self, llm, paper: ResearchPaper) -> str:
        """Editorial review using GPT-4o (editorial synthesis, cross-validation)."""
        from app.agents.discovery_orchestrator import ModelType

        # Build executive summary from all sections
        section_keys = list(paper.sections.keys())
        total_content_length = sum(len(v) for v in paper.sections.values())

        prompt = f"""You are a senior scientific editor reviewing an FDA/R&D-grade research paper about {paper.disease}.

PAPER OVERVIEW:
- Disease: {paper.disease}
- Discovery type: {paper.discovery_type}
- Sections completed: {', '.join(section_keys)}
- Total content: ~{total_content_length // 4:,} tokens across {len(section_keys)} sections
- References: {len(paper.references)} PubMed-verified citations
- Hypotheses: {len(paper.hypotheses)} (best confidence: {paper.stats.get('current_best_confidence', 0):.1%})
- Models used: Constant AI Explorer, GPT-4.1, Mistral-Large-3, GPT-4o, Cohere Command A, o3-mini, Grok-4-1-Fast, GPT-4.1

ABSTRACT (for context):
{paper.sections.get('abstract', 'Not yet generated')[:3000]}

TOP 5 HYPOTHESES:
{chr(10).join(f"- {h.get('title','N/A')} ({h.get('confidence',0):.1%})" for h in paper.hypotheses[:5])}

Write an Editorial Summary that includes:

1. EXECUTIVE SUMMARY (100 words)
   - Key takeaway from this research
   - Most significant finding

2. CROSS-MODEL VALIDATION ASSESSMENT (150 words)
   - How findings from different models corroborate each other
   - Divergent findings that warrant further investigation
   - Overall confidence in the multi-model approach

3. TRANSLATIONAL READINESS SCORE (100 words)
   - Rate the top 3 hypotheses on a 1-5 scale for translational readiness
   - Identify the most clinic-ready finding
   - Suggest immediate next steps for each

4. PUBLICATION READINESS (100 words)
   - Overall quality assessment
   - Sections that are publication-ready vs. need revision
   - Recommended target journals

Write as a professional editorial assessment. Be concise and actionable."""

        return await llm.generate(ModelType.GPT_4O_AZURE, prompt, temperature=0.25, max_tokens=16_384)

    async def _generate_reasoning_review(self, llm, paper: ResearchPaper) -> str:
        """Deep reasoning review using o3-mini (OpenAI reasoning model, 2.5M TPM)."""
        from app.agents.discovery_orchestrator import ModelType

        sections_summary = []
        for key in ["abstract", "methods", "results_overview", "discussion"]:
            content = paper.sections.get(key, "")
            if content:
                sections_summary.append(f"[{key.upper()}]: {content[:3000]}")

        prompt = f"""You are a rigorous scientific reasoning reviewer for an FDA/R&D-grade research paper about {paper.disease}.

Apply step-by-step logical reasoning to evaluate the following paper sections:

{chr(10).join(sections_summary)}

Hypotheses analyzed: {len(paper.hypotheses)}
Best confidence: {paper.stats.get('current_best_confidence', 0):.1%}

Perform a DEEP REASONING review:

1. LOGICAL CHAIN VALIDATION
   - Trace each major claim back to its evidence
   - Identify any logical gaps or unsupported inferences
   - Check that conclusions follow from premises

2. MECHANISTIC COHERENCE
   - Verify that proposed mechanisms are biologically plausible
   - Check pathway connections for logical consistency
   - Flag any contradictions between hypotheses

3. STATISTICAL REASONING
   - Evaluate whether confidence scores are justified
   - Check for potential confounders not addressed
   - Assess whether sample sizes and effect sizes are reasonable

4. CAUSAL vs. CORRELATIONAL
   - Flag claims that conflate correlation with causation
   - Identify where stronger causal evidence is needed
   - Suggest experimental designs to establish causality

Write a structured reasoning assessment with clear logical analysis."""

        return await llm.generate(ModelType.O3_MINI, prompt, temperature=0.0, max_tokens=100_000)

    async def _generate_analytical_review(self, llm, paper: ResearchPaper) -> str:
        """Analytical review using GPT-4.1 (latest GPT model, 50K TPM)."""
        from app.agents.discovery_orchestrator import ModelType

        section_keys = list(paper.sections.keys())
        total_content_length = sum(len(v) for v in paper.sections.values())

        prompt = f"""You are a senior research analyst reviewing an FDA/R&D-grade research paper about {paper.disease}.

PAPER OVERVIEW:
- Disease: {paper.disease}
- Discovery type: {paper.discovery_type}
- Sections completed: {', '.join(section_keys)}
- Total content: ~{total_content_length // 4:,} tokens across {len(section_keys)} sections
- References: {len(paper.references)} PubMed-verified citations
- Hypotheses: {len(paper.hypotheses)} (best confidence: {paper.stats.get('current_best_confidence', 0):.1%})

TOP 5 HYPOTHESES:
{chr(10).join(f"- {h.get('title','N/A')} ({h.get('confidence',0):.1%})" for h in paper.hypotheses[:5])}

Provide a comprehensive ANALYTICAL REVIEW:

1. CROSS-HYPOTHESIS ANALYSIS (200 words)
   - Identify synergies between top hypotheses
   - Map overlapping molecular targets and pathways
   - Propose combination strategies

2. COMPETITIVE LANDSCAPE (150 words)
   - Position findings against current clinical trials
   - Identify potential first-in-class opportunities
   - Flag areas with heavy existing competition

3. RISK ASSESSMENT (150 words)
   - Drug resistance mechanisms
   - Safety concerns and off-target effects
   - Regulatory hurdles for each approach

4. PRIORITIZED RECOMMENDATIONS (100 words)
   - Rank top 3 hypotheses by clinical feasibility
   - Recommend immediate next experiments
   - Suggest optimal development pathway

Write as a professional analytical assessment. Be data-driven and actionable."""

        return await llm.generate(ModelType.GPT_41, prompt, temperature=0.25, max_tokens=32_768)

    # =========================================================================
    # Plotly Figures — Interactive chart specifications for frontend
    # =========================================================================

    async def _generate_plotly_figures(self, paper: ResearchPaper) -> list[dict[str, Any]]:
        """Generate Plotly JSON specifications for interactive visualizations."""
        figures = []

        # Figure 1: Hypothesis Confidence Distribution (bar chart)
        confidences = [h.get("confidence", 0) for h in paper.hypotheses]
        titles = [h.get("title", f"H{i+1}")[:40] for i, h in enumerate(paper.hypotheses[:20])]
        models = [h.get("model_used", "unknown") for h in paper.hypotheses[:20]]

        model_colors = {
            "constant_ai_explorer": "#FF6B35",
            "gpt_41": "#14B8A6",
            "mistral_large_3": "#A855F7",
            "gpt_4o_azure": "#10B981",
            "cohere_command_a": "#F59E0B",
            "grok_fast": "#EC4899",
            "o3_mini": "#3B82F6",
            "gpt_41": "#14B8A6",
            "o3_mini": "#3B82F6",
        }
        colors = [model_colors.get(m, "#6B7280") for m in models]

        figures.append({
            "id": "fig_confidence_bar",
            "caption": "Figure 1. Hypothesis Confidence Scores by Discovery Model",
            "type": "plotly",
            "spec": {
                "data": [{
                    "type": "bar",
                    "x": titles,
                    "y": [c * 100 for c in confidences[:20]],
                    "marker": {"color": colors},
                    "text": [f"{c:.1%}" for c in confidences[:20]],
                    "textposition": "outside",
                    "hovertemplate": "<b>%{x}</b><br>Confidence: %{y:.1f}%<br>Model: %{customdata}<extra></extra>",
                    "customdata": models,
                }],
                "layout": {
                    "title": {"text": f"Top Hypotheses for {paper.disease}", "font": {"size": 16}},
                    "xaxis": {"title": "Hypothesis", "tickangle": -45},
                    "yaxis": {"title": "Confidence (%)", "range": [0, 105]},
                    "template": "plotly_dark",
                    "height": 500,
                    "margin": {"b": 150},
                },
            },
        })

        # Figure 2: Confidence Distribution Histogram
        buckets = {"<30%": 0, "30-50%": 0, "50-70%": 0, "70-90%": 0, ">=90%": 0}
        for c in confidences:
            if c < 0.3:
                buckets["<30%"] += 1
            elif c < 0.5:
                buckets["30-50%"] += 1
            elif c < 0.7:
                buckets["50-70%"] += 1
            elif c < 0.9:
                buckets["70-90%"] += 1
            else:
                buckets[">=90%"] += 1

        figures.append({
            "id": "fig_confidence_dist",
            "caption": "Figure 2. Distribution of Confidence Scores Across All Hypotheses",
            "type": "plotly",
            "spec": {
                "data": [{
                    "type": "bar",
                    "x": list(buckets.keys()),
                    "y": list(buckets.values()),
                    "marker": {
                        "color": ["#EF4444", "#F97316", "#EAB308", "#22C55E", "#10B981"],
                    },
                    "text": list(buckets.values()),
                    "textposition": "outside",
                }],
                "layout": {
                    "title": {"text": "Confidence Score Distribution", "font": {"size": 16}},
                    "xaxis": {"title": "Confidence Range"},
                    "yaxis": {"title": "Number of Hypotheses"},
                    "template": "plotly_dark",
                    "height": 400,
                },
            },
        })

        # Figure 3: Model Performance Comparison (grouped bar)
        token_stats = paper.stats.get("token_pool_stats", {})
        requests = token_stats.get("requests_per_model", {})
        errors = token_stats.get("errors_per_model", {})
        model_names = ["constant_ai_explorer", "gpt_41", "mistral_large_3", "gpt_4o_azure", "cohere_command_a", "grok_fast", "o3_mini", "gpt_41"]
        display_names = ["Constant AI Explorer", "GPT-4.1", "Mistral-Large-3", "GPT-4o", "Cohere Command A", "Grok-4-1-Fast", "o3-mini", "GPT-4.1"]

        figures.append({
            "id": "fig_model_performance",
            "caption": "Figure 3. Model Performance Comparison: Requests vs Errors",
            "type": "plotly",
            "spec": {
                "data": [
                    {
                        "type": "bar",
                        "name": "Requests",
                        "x": display_names,
                        "y": [requests.get(m, 0) for m in model_names],
                        "marker": {"color": "#3B82F6"},
                    },
                    {
                        "type": "bar",
                        "name": "Errors",
                        "x": display_names,
                        "y": [errors.get(m, 0) for m in model_names],
                        "marker": {"color": "#EF4444"},
                    },
                ],
                "layout": {
                    "title": {"text": "Model Usage and Error Rates", "font": {"size": 16}},
                    "barmode": "group",
                    "xaxis": {"title": "Model"},
                    "yaxis": {"title": "Count"},
                    "template": "plotly_dark",
                    "height": 400,
                },
            },
        })

        # Figure 4: Agent Role Distribution (pie chart)
        agents_by_role = paper.stats.get("agents_by_role", {})
        if agents_by_role:
            figures.append({
                "id": "fig_agent_roles",
                "caption": "Figure 4. Agent Distribution by Role",
                "type": "plotly",
                "spec": {
                    "data": [{
                        "type": "pie",
                        "labels": [r.title() for r in agents_by_role.keys()],
                        "values": list(agents_by_role.values()),
                        "hole": 0.4,
                        "marker": {
                            "colors": ["#FF6B35", "#4ECDC4", "#A855F7", "#3B82F6", "#EAB308"],
                        },
                        "textinfo": "label+percent",
                    }],
                    "layout": {
                        "title": {"text": "Agent Role Distribution", "font": {"size": 16}},
                        "template": "plotly_dark",
                        "height": 400,
                    },
                },
            })

        # Figure 5: External Factors by Category (treemap)
        if paper.external_factors:
            factor_labels = []
            factor_parents = []
            factor_values = []

            categories = {}
            for f in paper.external_factors:
                cat = f.get("category", "other").title()
                categories.setdefault(cat, []).append(f.get("name", "Unknown"))

            factor_labels.append("External Factors")
            factor_parents.append("")
            factor_values.append(0)

            for cat, names in categories.items():
                factor_labels.append(cat)
                factor_parents.append("External Factors")
                factor_values.append(len(names))
                for name in names:
                    factor_labels.append(name)
                    factor_parents.append(cat)
                    factor_values.append(1)

            figures.append({
                "id": "fig_external_factors",
                "caption": "Figure 5. External Factors Analyzed by Category",
                "type": "plotly",
                "spec": {
                    "data": [{
                        "type": "treemap",
                        "labels": factor_labels,
                        "parents": factor_parents,
                        "values": factor_values,
                        "textinfo": "label+value",
                        "marker": {"colorscale": "Viridis"},
                    }],
                    "layout": {
                        "title": {"text": "External Factor Categories", "font": {"size": 16}},
                        "template": "plotly_dark",
                        "height": 500,
                    },
                },
            })

        # Figure 6: Discovery Pipeline Flowchart (Mermaid — kept for compatibility)
        figures.append({
            "id": "fig_pipeline",
            "caption": "Figure 6. Humanovo Eight-Model Discovery Pipeline",
            "type": "mermaid",
            "spec": (
                "graph TD\n"
                f"    A[Disease: {paper.disease}] --> B[Knowledge Graph]\n"
                "    B --> C{Agent Distribution}\n"
                "    C --> D[Constant AI Explorer<br/>Explorer + Synthesizer]\n"
                "    C --> E[GPT-4.1<br/>Abstract &amp; Introduction]\n"
                "    C --> F[Mistral-Large-3<br/>Critical Analyst]\n"
                "    C --> G1[GPT-4o<br/>Editorial Synthesis]\n"
                "    C --> G2[Cohere Command A<br/>Literature RAG]\n"
                "    C --> G3[o3-mini<br/>QA Validation]\n"
                "    C --> G4[o3-mini<br/>Deep Reasoning]\n"
                "    C --> G5[GPT-4.1<br/>Analytical Review]\n"
                "    D --> H[Hypothesis Pool]\n"
                "    E --> H\n"
                "    F --> H\n"
                "    G1 --> H\n"
                "    G2 --> H\n"
                "    G3 --> H\n"
                "    G4 --> H\n"
                "    G5 --> H\n"
                "    H --> I{Confidence >= Target?}\n"
                "    I -->|Yes| J[Paper Generation<br/>8 Models · 4 Phases]\n"
                "    I -->|No| K[Continue + Learn]\n"
                "    K --> C\n"
                "    L[External Factors] --> H\n"
                "    J --> M[PubMed Citation<br/>Validation]\n"
                "    J --> N[QA Validation<br/>o3-mini]\n"
                "    J --> P[Editorial Review<br/>GPT-4o]\n"
                "    J --> Q[Reasoning Review<br/>o3-mini]\n"
                "    J --> R[Analytical Review<br/>GPT-4.1]\n"
                "    M --> O[FDA/R&D Grade Paper]\n"
                "    N --> O\n"
                "    P --> O\n"
                "    Q --> O\n"
                "    R --> O"
            ),
        })

        return figures

    # =========================================================================
    # Tables
    # =========================================================================

    async def _generate_tables(self, paper: ResearchPaper) -> list[dict[str, Any]]:
        """Generate data tables for the paper."""
        tables = []

        # Table 1: Top hypotheses with rich detail
        hyp_rows = []
        for i, h in enumerate(paper.hypotheses[:20], 1):
            hyp_rows.append({
                "rank": i,
                "title": h.get("title", "Untitled"),
                "confidence": f"{h.get('confidence', 0):.1%}",
                "model": h.get("model_used", "unknown"),
                "mechanism": (h.get("mechanism", "N/A"))[:100],
                "validated": "Yes" if h.get("validated") else "Pending",
            })

        tables.append({
            "id": "table_hypotheses",
            "caption": f"Table 1. Top {len(hyp_rows)} Discovery Hypotheses for {paper.disease}",
            "columns": ["Rank", "Hypothesis", "Confidence", "Model", "Mechanism", "Validated"],
            "rows": hyp_rows,
        })

        # Table 2: Model performance
        token_stats = paper.stats.get("token_pool_stats", {})
        model_rows = []
        for model_name, display in [
            ("constant_ai_explorer", "Constant AI Explorer"),
            ("gpt_41", "GPT-4.1"),
            ("mistral_large_3", "Mistral-Large-3"),
            ("gpt_4o_azure", "GPT-4o"),
            ("cohere_command_a", "Cohere Command A"),
            ("grok_fast", "Grok-4-1-Fast"),
            ("o3_mini", "o3-mini"),
            ("gpt_41", "GPT-4.1"),
        ]:
            reqs = token_stats.get("requests_per_model", {}).get(model_name, 0)
            tokens = token_stats.get("tokens_per_model", {}).get(model_name, 0)
            errs = token_stats.get("errors_per_model", {}).get(model_name, 0)
            success_rate = f"{((reqs - errs) / max(reqs, 1)) * 100:.1f}%" if reqs > 0 else "N/A"
            model_rows.append({
                "model": display,
                "requests": reqs,
                "tokens_used": f"{tokens:,}",
                "errors": errs,
                "success_rate": success_rate,
            })

        tables.append({
            "id": "table_models",
            "caption": "Table 2. Multi-Model Performance Comparison",
            "columns": ["Model", "Requests", "Tokens Used", "Errors", "Success Rate"],
            "rows": model_rows,
        })

        # Table 3: External factors
        if paper.external_factors:
            factor_rows = []
            for f in paper.external_factors[:30]:
                factor_rows.append({
                    "name": f.get("name", "Unknown"),
                    "category": f.get("category", "unknown").title(),
                    "interaction": f.get("interaction", "To be determined"),
                })
            tables.append({
                "id": "table_factors",
                "caption": "Table 3. External Factors Analyzed",
                "columns": ["Factor", "Category", "Known Interaction"],
                "rows": factor_rows,
            })

        # Table 4: Hypothesis diversity metrics
        if len(paper.hypotheses) >= 5:
            model_counts = {}
            for h in paper.hypotheses:
                m = h.get("model_used", "unknown")
                model_counts[m] = model_counts.get(m, 0) + 1

            diversity_rows = []
            for model, count in model_counts.items():
                confs = [h.get("confidence", 0) for h in paper.hypotheses if h.get("model_used") == model]
                avg_conf = sum(confs) / len(confs) if confs else 0
                diversity_rows.append({
                    "model": model,
                    "hypotheses_generated": count,
                    "avg_confidence": f"{avg_conf:.1%}",
                    "max_confidence": f"{max(confs):.1%}" if confs else "N/A",
                    "min_confidence": f"{min(confs):.1%}" if confs else "N/A",
                })

            tables.append({
                "id": "table_diversity",
                "caption": "Table 4. Hypothesis Diversity by Model",
                "columns": ["Model", "Hypotheses Generated", "Avg Confidence", "Max Confidence", "Min Confidence"],
                "rows": diversity_rows,
            })

        return tables

    # =========================================================================
    # Dynamic Table of Contents
    # =========================================================================

    def _build_dynamic_toc(self, paper: ResearchPaper) -> list[dict[str, Any]]:
        """Build a fully dynamic TOC from generated sections."""
        toc = []
        section_order = [
            ("title", "Title Page", 0),
            ("abstract", "Abstract", 0),
            ("introduction", "Introduction", 0),
            ("disease_background", "Disease Background", 1),
            ("literature_review", "Literature Review", 0),
            ("methods", "Methods", 0),
            ("results_overview", "Results Overview", 0),
            ("hypothesis_analyses", "Detailed Hypothesis Analyses", 1),
            ("molecular_mechanisms", "Molecular Mechanisms", 1),
            ("translational_roadmap", "Translational Roadmap (T0-T5)", 0),
            ("external_factors_analysis", "External Factors Analysis", 0),
            ("discussion", "Discussion", 0),
            ("limitations_future", "Limitations and Future Directions", 1),
            ("conclusion", "Conclusion", 0),
            ("qa_validation", "QA Validation Report", 1),
            ("editorial_review", "Editorial Review", 1),
            ("reasoning_review", "Reasoning Review", 1),
            ("analytical_review", "Analytical Review", 1),
        ]

        idx = 1
        for section_key, display_name, depth in section_order:
            if section_key in paper.sections and paper.sections[section_key]:
                toc.append({
                    "id": f"section-{section_key}",
                    "label": display_name,
                    "section_key": section_key,
                    "depth": depth,
                    "index": idx,
                })
                idx += 1

        # Add tables and figures to TOC
        if paper.tables:
            toc.append({"id": "section-tables", "label": "Tables", "section_key": "tables", "depth": 0, "index": idx})
            idx += 1
        if paper.plotly_figures:
            toc.append({"id": "section-figures", "label": "Figures", "section_key": "figures", "depth": 0, "index": idx})
            idx += 1
        if paper.references:
            toc.append({"id": "section-references", "label": "References", "section_key": "references", "depth": 0, "index": idx})

        return toc

    # =========================================================================
    # Markdown Export
    # =========================================================================

    def paper_to_html(self, paper: ResearchPaper) -> str:
        """Convert a research paper to a self-contained, professionally formatted HTML document.

        Produces an FDA/R&D-grade HTML page with:
        - Cover page with title, "by Humanovo", date, model info
        - Indexed table of contents with numbered sections
        - Professional typography (system fonts, proper spacing, colors)
        - Numbered citations [1], [2], etc. with PubMed verification
        - Formatted tables with zebra striping
        - Code/diagram blocks preserved in monospace
        - Mermaid diagram code blocks
        - Responsive layout for the iframe viewer
        """
        import html as html_mod
        import re

        title = html_mod.escape(paper.sections.get('title', 'Untitled Research Paper'))
        date_str = paper.created_at.strftime('%B %d, %Y at %H:%M UTC')
        models = "Constant AI Explorer, GPT-4.1, Mistral-Large-3, GPT-4o, Cohere Command A, o3-mini, Grok-4-1-Fast, GPT-4.1"

        def _md_to_html(text: str) -> str:
            """Convert basic markdown formatting to HTML."""
            t = html_mod.escape(text)
            # Bold **text**
            t = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', t)
            # Italic *text*
            t = re.sub(r'\*(.+?)\*', r'<em>\1</em>', t)
            # Inline code `text`
            t = re.sub(r'`(.+?)`', r'<code>\1</code>', t)
            return t

        def _section_to_html(content: str) -> str:
            """Convert section content (markdown-ish) to HTML paragraphs."""
            blocks = content.split('\n\n')
            parts = []
            for block in blocks:
                block = block.strip()
                if not block:
                    continue
                if block.startswith('#### '):
                    parts.append(f'<h4>{_md_to_html(block[5:])}</h4>')
                elif block.startswith('### '):
                    parts.append(f'<h3>{_md_to_html(block[4:])}</h3>')
                elif block.startswith('## '):
                    parts.append(f'<h2>{_md_to_html(block[3:])}</h2>')
                elif block.startswith('---'):
                    parts.append('<hr/>')
                elif _is_diagram(block):
                    parts.append(f'<pre class="diagram">{html_mod.escape(block)}</pre>')
                elif block.startswith('- ') or block.startswith('* '):
                    items = []
                    for line in block.split('\n'):
                        line = line.strip()
                        if line.startswith('- ') or line.startswith('* '):
                            items.append(f'<li>{_md_to_html(line[2:])}</li>')
                        elif line:
                            items.append(f'<li>{_md_to_html(line)}</li>')
                    parts.append(f'<ul>{"".join(items)}</ul>')
                else:
                    parts.append(f'<p>{_md_to_html(block)}</p>')
            return '\n'.join(parts)

        def _is_diagram(text: str) -> bool:
            arrow_chars = text.count('→') + text.count('←') + text.count('↓') + text.count('↑')
            pipe_chars = text.count('│') + text.count('┌') + text.count('└') + text.count('├')
            box_chars = text.count('[') + text.count(']')
            if arrow_chars >= 2 or pipe_chars >= 2:
                return True
            if box_chars >= 4 and arrow_chars >= 1:
                return True
            indent_lines = sum(1 for line in text.split('\n') if line.startswith('    '))
            total_lines = max(len(text.split('\n')), 1)
            if indent_lines >= 3 and indent_lines / total_lines > 0.5:
                return True
            return False

        # Build HTML
        h = []
        h.append(f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
:root {{
  --primary: #0f1b2d;
  --accent: #e94560;
  --text: #1a1a2e;
  --text-light: #4a4a6a;
  --text-muted: #888;
  --bg: #ffffff;
  --bg-alt: #f4f6f9;
  --border: #d0d5dd;
  --table-header: #0f1b2d;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
  font-family: 'Georgia', 'Times New Roman', serif;
  color: var(--text);
  background: var(--bg);
  line-height: 1.7;
  font-size: 11pt;
}}
.page {{ max-width: 8.5in; margin: 0 auto; padding: 0.75in; }}

/* ---- Cover Page ---- */
.cover {{
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 2in 1in;
  page-break-after: always;
}}
.cover .accent-line {{
  width: 200px;
  height: 3px;
  background: var(--accent);
  margin: 0 auto 2rem;
}}
.cover h1 {{
  font-size: 26pt;
  color: var(--primary);
  line-height: 1.3;
  margin-bottom: 0.5rem;
  font-weight: 700;
}}
.cover .disease {{
  font-size: 20pt;
  color: var(--accent);
  font-weight: 700;
  margin: 0.5rem 0 1.5rem;
}}
.cover .divider {{
  width: 70%;
  height: 1px;
  background: var(--border);
  margin: 0 auto 1.5rem;
}}
.cover .brand {{
  font-size: 20pt;
  color: var(--primary);
  font-weight: 700;
  margin-bottom: 0.25rem;
}}
.cover .subtitle {{
  font-size: 13pt;
  color: var(--text-light);
  margin-bottom: 0.25rem;
}}
.cover .grade {{
  font-size: 11pt;
  color: var(--accent);
  font-weight: 700;
  margin-bottom: 1.5rem;
}}
.cover .models {{
  font-size: 9pt;
  color: var(--text-muted);
  margin-bottom: 1rem;
}}
.cover .meta {{
  font-size: 10pt;
  color: var(--text-muted);
  margin-bottom: 0.25rem;
}}
.cover-table {{
  margin: 1.5rem auto 0;
  border-collapse: collapse;
  font-size: 9pt;
  font-family: 'Helvetica Neue', Arial, sans-serif;
}}
.cover-table th {{
  background: var(--table-header);
  color: white;
  padding: 6px 16px;
  text-align: left;
  font-weight: 600;
}}
.cover-table td {{
  padding: 5px 16px;
  border: 1px solid var(--border);
}}
.cover-table tr:nth-child(even) td {{ background: var(--bg-alt); }}

/* ---- TOC ---- */
.toc {{ page-break-after: always; }}
.toc h2 {{
  font-size: 18pt;
  color: var(--primary);
  border-bottom: 2px solid var(--accent);
  padding-bottom: 6px;
  margin-bottom: 1rem;
}}
.toc-entry {{
  font-family: 'Helvetica Neue', Arial, sans-serif;
  font-size: 11pt;
  padding: 4px 0;
  color: var(--text);
}}
.toc-entry a {{
  color: var(--text);
  text-decoration: none;
}}
.toc-entry a:hover {{ color: var(--accent); }}
.toc-entry.sub {{ padding-left: 24px; font-size: 10pt; color: var(--text-light); }}

/* ---- Section headings ---- */
h2.section-heading {{
  font-size: 17pt;
  color: var(--primary);
  border-bottom: 2px solid var(--accent);
  padding-bottom: 6px;
  margin: 2rem 0 1rem;
  page-break-after: avoid;
}}
h3 {{
  font-size: 13pt;
  color: #1a3a5c;
  margin: 1.5rem 0 0.5rem;
  font-weight: 700;
}}
h4 {{
  font-size: 11pt;
  color: #2a5a8c;
  margin: 1rem 0 0.5rem;
  font-weight: 700;
}}

/* ---- Body ---- */
p {{ margin-bottom: 0.75rem; text-align: justify; }}
ul, ol {{ margin: 0.5rem 0 0.75rem 1.5rem; }}
li {{ margin-bottom: 0.3rem; }}
strong {{ font-weight: 700; }}
em {{ font-style: italic; }}
code {{
  font-family: 'Courier New', Courier, monospace;
  background: var(--bg-alt);
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 0.9em;
}}
hr {{
  border: none;
  border-top: 1px solid var(--border);
  margin: 1.5rem 0;
}}

/* ---- Diagrams / code blocks ---- */
pre.diagram {{
  font-family: 'Courier New', Courier, monospace;
  font-size: 9pt;
  line-height: 1.4;
  background: var(--bg-alt);
  border: 1px solid var(--border);
  border-left: 3px solid var(--accent);
  padding: 12px 16px;
  margin: 1rem 0;
  overflow-x: auto;
  white-space: pre;
  border-radius: 4px;
}}

/* ---- Tables ---- */
.data-table {{
  width: 100%;
  border-collapse: collapse;
  font-family: 'Helvetica Neue', Arial, sans-serif;
  font-size: 9pt;
  margin: 0.75rem 0 1.5rem;
}}
.data-table th {{
  background: var(--table-header);
  color: white;
  padding: 7px 10px;
  text-align: left;
  font-weight: 600;
  font-size: 8.5pt;
}}
.data-table td {{
  padding: 5px 10px;
  border: 1px solid var(--border);
  vertical-align: top;
}}
.data-table tr:nth-child(even) td {{ background: var(--bg-alt); }}
.table-caption {{
  font-size: 9pt;
  color: var(--text-light);
  text-align: center;
  font-style: italic;
  margin-bottom: 1.5rem;
}}

/* ---- References ---- */
.ref-entry {{
  font-size: 9pt;
  line-height: 1.5;
  margin-bottom: 4px;
  padding-left: 2em;
  text-indent: -2em;
  font-family: 'Helvetica Neue', Arial, sans-serif;
}}
.ref-id {{ font-weight: 700; }}
.ref-verified {{
  color: #16a34a;
  font-weight: 600;
  font-size: 8pt;
}}

/* ---- Footer ---- */
.doc-footer {{
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 2px solid var(--accent);
  text-align: center;
  font-size: 8pt;
  color: var(--text-muted);
  font-family: 'Helvetica Neue', Arial, sans-serif;
}}

@media print {{
  body {{ font-size: 10pt; }}
  .page {{ padding: 0; }}
  .cover {{ min-height: auto; padding: 1in; }}
}}
</style>
</head>
<body>
''')

        # ---- Cover Page ----
        h.append('<div class="cover">')
        h.append('<div class="accent-line"></div>')
        h.append(f'<h1>{title}</h1>')
        h.append(f'<div class="disease">{html_mod.escape(paper.disease)}</div>')
        h.append('<div class="divider"></div>')
        h.append('<div class="brand">by Humanovo</div>')
        h.append('<div class="subtitle">Multi-Model AI Discovery Platform</div>')
        h.append('<div class="grade">FDA/R&amp;D-Grade Research Document</div>')
        h.append(f'<div class="models">{html_mod.escape(models)}</div>')
        h.append(f'<div class="meta">{date_str}</div>')
        h.append(f'<div class="meta">{len(paper.hypotheses)} Hypotheses &bull; '
                 f'Generation time: {paper.generation_time_seconds:.1f}s &bull; '
                 f'All citations PubMed-verified</div>')

        # Config table
        h.append('<table class="cover-table">')
        h.append('<tr><th>Parameter</th><th>Value</th></tr>')
        config = [
            ('Disease Focus', paper.disease),
            ('Discovery Type', paper.discovery_type.replace('_', ' ').title()),
            ('Total Hypotheses', str(len(paper.hypotheses))),
            ('Best Confidence', f"{paper.stats.get('current_best_confidence', 0):.1%}"),
            ('AI Models', '8 (see above)'),
            ('References', f"{len(paper.references)} PubMed-verified"),
        ]
        for param, val in config:
            h.append(f'<tr><td><strong>{html_mod.escape(param)}</strong></td>'
                     f'<td>{html_mod.escape(val)}</td></tr>')
        h.append('</table>')
        h.append('</div>')  # end cover

        h.append('<div class="page">')

        # ---- Table of Contents ----
        h.append('<div class="toc">')
        h.append('<h2>Table of Contents</h2>')
        for entry in paper.toc:
            depth = entry.get("depth", 0)
            cls = "toc-entry sub" if depth > 0 else "toc-entry"
            label = html_mod.escape(entry["label"])
            anchor = entry["id"]
            idx = entry["index"]
            h.append(f'<div class="{cls}"><a href="#{anchor}">{idx}. {label}</a></div>')
        h.append('</div>')  # end toc

        # ---- Sections ----
        section_headers = {
            "abstract": "Abstract",
            "introduction": "Introduction",
            "disease_background": "Disease Background",
            "literature_review": "Literature Review",
            "methods": "Methods",
            "results_overview": "Results",
            "hypothesis_analyses": "Detailed Hypothesis Analyses",
            "molecular_mechanisms": "Molecular Mechanisms",
            "external_factors_analysis": "External Factors Analysis",
            "discussion": "Discussion",
            "limitations_future": "Limitations and Future Directions",
            "conclusion": "Conclusion",
            "qa_validation": "QA Validation Report",
            "editorial_review": "Editorial Review",
            "reasoning_review": "Reasoning Review",
            "analytical_review": "Analytical Review",
        }

        sec_idx = 0
        for key, header in section_headers.items():
            content = paper.sections.get(key, "")
            if not content:
                continue
            sec_idx += 1
            anchor_id = f"section-{key}"
            h.append(f'<a id="{anchor_id}"></a>')
            if not content.strip().startswith("##"):
                h.append(f'<h2 class="section-heading">{sec_idx}. {html_mod.escape(header)}</h2>')
            h.append(_section_to_html(content))

        # ---- Tables ----
        if paper.tables:
            h.append('<a id="section-tables"></a>')
            h.append('<h2 class="section-heading">Tables</h2>')
            for table in paper.tables:
                caption = html_mod.escape(table["caption"])
                cols = table["columns"]
                h.append(f'<table class="data-table">')
                h.append('<thead><tr>')
                for c in cols:
                    h.append(f'<th>{html_mod.escape(c)}</th>')
                h.append('</tr></thead><tbody>')
                for row in table["rows"]:
                    h.append('<tr>')
                    for c in cols:
                        key_name = c.lower().replace(" ", "_")
                        val = row.get(key_name, "")
                        if val == "":
                            val = row.get(c.lower(), "")
                        h.append(f'<td>{html_mod.escape(str(val))}</td>')
                    h.append('</tr>')
                h.append('</tbody></table>')
                h.append(f'<div class="table-caption">{caption}</div>')

        # ---- Plotly / Mermaid figures ----
        if paper.plotly_figures:
            h.append('<a id="section-figures"></a>')
            h.append('<h2 class="section-heading">Figures</h2>')
            for fig in paper.plotly_figures:
                caption = html_mod.escape(fig["caption"])
                h.append(f'<h3>{caption}</h3>')
                if fig["type"] == "mermaid":
                    h.append(f'<pre class="diagram">{html_mod.escape(fig["spec"])}</pre>')
                elif fig["type"] == "plotly":
                    h.append(f'<pre class="diagram">{html_mod.escape(json.dumps(fig["spec"], indent=2))}</pre>')

        # ---- References ----
        if paper.references:
            h.append('<a id="section-references"></a>')
            h.append('<h2 class="section-heading">References</h2>')
            for ref in paper.references:
                ref_id = ref.get("id", "")
                text = html_mod.escape(ref.get("text", ""))
                doi = ref.get("doi", "")
                pmid = ref.get("pmid", "")
                verified = ref.get("verified", False)
                line = f'<div class="ref-entry"><span class="ref-id">[{ref_id}]</span> {text}'
                if doi:
                    safe_doi = html_mod.escape(doi)
                    line += f' DOI: <a href="{safe_doi}" target="_blank">{safe_doi}</a>'
                if pmid:
                    line += f' PMID: {html_mod.escape(pmid)}'
                if verified:
                    line += ' <span class="ref-verified">[PubMed Verified]</span>'
                line += '</div>'
                h.append(line)

        # ---- Footer ----
        h.append('<div class="doc-footer">')
        h.append(f'Generated by <strong>Humanovo</strong> &mdash; FDA/R&amp;D-Grade AI Discovery Platform<br/>')
        h.append(f'{date_str} &bull; 8 Models &bull; '
                 f'{len(paper.references)} PubMed-Verified References<br/>')
        h.append('CONFIDENTIAL &mdash; FOR AUTHORIZED USE ONLY')
        h.append('</div>')

        h.append('</div>')  # end page
        h.append('</body></html>')

        return '\n'.join(h)

    def paper_to_markdown(self, paper: ResearchPaper) -> str:
        """Convert a research paper to HTML format (legacy name kept for API compat)."""
        return self.paper_to_html(paper)


# Singleton
_paper_service: Optional[PaperGenerationService] = None


def get_paper_service() -> PaperGenerationService:
    global _paper_service
    if _paper_service is None:
        _paper_service = PaperGenerationService()
    return _paper_service
