"""
Research Paper Generation Service — v5 (Three-Model Discovery Pipeline)

Generates FDA/R&D-grade, fully AI-driven research papers from discovery results.

Key features:
- ALL sections generated by LLMs — maxed out token capacity per model
- 3 discovery models:
  Bedrock: Claude Opus 4.6 (32K out, synthesis + exploration)
  Azure AI: DeepSeek-R1-0528 (64K out, deep reasoning + chain-of-thought)
  Azure AI: Mistral-Large-3 (32K out, critical analysis + validation)
- FDA/R&D grade output: cover page, TOC, numbered citations, references
- Content includes: flowcharts, mechanism diagrams, formulas, tables
- Dynamic Table of Contents with section anchors
- Plotly-based interactive charts (JSON specs for frontend rendering)
- Real citation validation via PubMed API (no hallucinated DOIs)
- 12-15+ page minimum output using all published substances
- 30-minute hard timeout with failure on exceed
- Low temperature (0.15-0.3) for factual accuracy — NO HALLUCINATION
- top_p = 0.9 across all models for controlled diversity

All content is real-time AI generated. Zero hardcoded templates.
"""

import asyncio
import json
import time
from datetime import datetime
from typing import Any, Optional
from uuid import uuid4

from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)

# Maximum paper generation time: 30 minutes
PAPER_GENERATION_TIMEOUT_SECONDS = 1800


class ResearchPaper:
    """A generated research paper from discovery results."""

    def __init__(
        self,
        disease: str,
        discovery_type: str,
        hypotheses: list[dict[str, Any]],
        stats: dict[str, Any],
        external_factors: list[dict[str, Any]] = None,
    ):
        self.id = str(uuid4())
        self.disease = disease
        self.discovery_type = discovery_type
        self.hypotheses = hypotheses
        self.stats = stats
        self.external_factors = external_factors or []
        self.created_at = datetime.utcnow()
        self.sections: dict[str, str] = {}
        self.references: list[dict[str, str]] = []
        self.tables: list[dict[str, Any]] = []
        self.figures: list[dict[str, Any]] = []
        self.toc: list[dict[str, Any]] = []
        self.plotly_figures: list[dict[str, Any]] = []
        self.generation_time_seconds: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "disease": self.disease,
            "discovery_type": self.discovery_type,
            "created_at": self.created_at.isoformat(),
            "toc": self.toc,
            "sections": self.sections,
            "references": self.references,
            "tables": self.tables,
            "figures": self.figures,
            "plotly_figures": self.plotly_figures,
            "metadata": {
                "total_hypotheses": len(self.hypotheses),
                "total_agents": self.stats.get("total_agents", 0),
                "runtime_seconds": self.stats.get("runtime_seconds", 0),
                "best_confidence": self.stats.get("current_best_confidence", 0),
                "models_used": self.stats.get("models_active", []),
                "external_factors_count": len(self.external_factors),
                "generation_time_seconds": self.generation_time_seconds,
            },
        }


class CitationValidator:
    """Validates citations against PubMed to prevent hallucinated DOIs."""

    def __init__(self):
        self._validated_cache: dict[str, dict] = {}

    async def search_pubmed(self, query: str, max_results: int = 3) -> list[dict[str, str]]:
        """Search PubMed for real citations matching a query."""
        try:
            import aiohttp
            base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
            email = settings.PUBMED_EMAIL

            # Search for PMIDs
            search_url = f"{base_url}/esearch.fcgi"
            params = {
                "db": "pubmed",
                "term": query,
                "retmax": max_results,
                "retmode": "json",
                "email": email,
            }

            async with aiohttp.ClientSession() as session:
                async with session.get(search_url, params=params, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                    if resp.status != 200:
                        return []
                    data = await resp.json()
                    pmids = data.get("esearchresult", {}).get("idlist", [])

                if not pmids:
                    return []

                # Fetch citation details
                fetch_url = f"{base_url}/esummary.fcgi"
                fetch_params = {
                    "db": "pubmed",
                    "id": ",".join(pmids),
                    "retmode": "json",
                    "email": email,
                }

                async with session.get(fetch_url, params=fetch_params, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                    if resp.status != 200:
                        return []
                    summary = await resp.json()

                citations = []
                results = summary.get("result", {})
                for pmid in pmids:
                    article = results.get(pmid, {})
                    if not article or pmid == "uids":
                        continue

                    authors_list = article.get("authors", [])
                    first_author = authors_list[0]["name"] if authors_list else "Unknown"
                    et_al = " et al." if len(authors_list) > 1 else ""

                    year = article.get("pubdate", "")[:4]
                    title = article.get("title", "")
                    journal = article.get("fulljournalname", article.get("source", ""))
                    doi_ids = [eid for eid in article.get("articleids", []) if eid.get("idtype") == "doi"]
                    doi = doi_ids[0]["value"] if doi_ids else ""

                    citation = {
                        "pmid": pmid,
                        "text": f"{first_author}{et_al} ({year}). {title} {journal}.",
                        "doi": f"https://doi.org/{doi}" if doi else "",
                        "title": title,
                        "year": year,
                        "journal": journal,
                        "verified": True,
                    }
                    citations.append(citation)
                    self._validated_cache[pmid] = citation

                return citations

        except Exception as e:
            logger.warning(f"PubMed search failed for '{query}': {e}")
            return []

    async def validate_and_collect_citations(
        self, disease: str, hypotheses: list[dict[str, Any]], external_factors: list[dict[str, Any]],
    ) -> list[dict[str, str]]:
        """Collect real, validated citations for the paper across multiple topics."""
        all_citations = []
        seen_pmids = set()

        # Build search queries from paper content
        queries = [
            f"{disease} treatment therapy",
            f"{disease} pathophysiology mechanisms",
            f"{disease} clinical trials 2024 2025",
            f"multi-model AI drug discovery",
            f"large language models biomedical research",
        ]

        # Add hypothesis-specific queries
        for h in hypotheses[:10]:
            title = h.get("title", "")
            if title:
                queries.append(f"{disease} {title[:60]}")

        # Add external factor queries
        factor_names = [f.get("name", "") for f in external_factors[:5] if f.get("name")]
        for name in factor_names:
            queries.append(f"{name} {disease} therapeutic effect")

        # Run PubMed searches in parallel batches
        tasks = [self.search_pubmed(q, max_results=2) for q in queries]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        ref_id = 1
        for result in results:
            if isinstance(result, Exception):
                continue
            for citation in result:
                pmid = citation.get("pmid", "")
                if pmid and pmid not in seen_pmids:
                    seen_pmids.add(pmid)
                    citation["id"] = str(ref_id)
                    all_citations.append(citation)
                    ref_id += 1

        logger.info(f"Validated {len(all_citations)} real citations from PubMed")
        return all_citations


class PaperGenerationService:
    """
    Generates fully AI-driven research papers using all 4 models in parallel.
    No template fallbacks — every section is LLM-generated.
    """

    def __init__(self):
        self._llm = None
        self._citation_validator = CitationValidator()

    async def _get_llm(self):
        if self._llm is None:
            try:
                from app.agents.discovery_orchestrator import MultiModelLLM, TokenPool
                pool = TokenPool()
                self._llm = MultiModelLLM(pool)
                await self._llm.initialize()
            except Exception as e:
                logger.error(f"LLM initialization failed for paper generation: {e}")
                raise RuntimeError(f"LLM required for paper generation but unavailable: {e}")
        return self._llm

    async def generate_paper(
        self,
        disease: str,
        discovery_type: str,
        hypotheses: list[dict[str, Any]],
        stats: dict[str, Any],
        external_factors: list[dict[str, Any]] = None,
    ) -> ResearchPaper:
        """Generate a full research paper. Fails if exceeds 30-minute timeout."""
        start_time = time.time()

        paper = ResearchPaper(
            disease=disease,
            discovery_type=discovery_type,
            hypotheses=hypotheses,
            stats=stats,
            external_factors=external_factors,
        )

        try:
            await asyncio.wait_for(
                self._generate_all_sections(paper),
                timeout=PAPER_GENERATION_TIMEOUT_SECONDS,
            )
        except asyncio.TimeoutError:
            elapsed = time.time() - start_time
            raise RuntimeError(
                f"Paper generation exceeded 30-minute timeout ({elapsed:.0f}s elapsed). "
                f"Completed sections: {list(paper.sections.keys())}"
            )

        paper.generation_time_seconds = time.time() - start_time
        logger.info(
            f"Generated research paper '{paper.sections.get('title', 'Untitled')}' "
            f"in {paper.generation_time_seconds:.1f}s with {len(paper.tables)} tables, "
            f"{len(paper.plotly_figures)} Plotly figures, {len(paper.references)} verified references"
        )
        return paper

    async def _generate_all_sections(self, paper: ResearchPaper) -> None:
        """Generate all paper content using multiple models in parallel."""
        llm = await self._get_llm()
        from app.agents.discovery_orchestrator import ModelType

        # Build rich hypothesis context for all models
        hyp_context = self._build_hypothesis_context(paper)
        substance_context = self._build_substance_context(paper)

        # Phase 1: Parallel generation of independent sections across all 4 models
        phase1_tasks = {
            "title": self._generate_title_ai(llm, paper),
            "abstract": self._generate_abstract_ai(llm, paper, hyp_context),
            "introduction": self._generate_introduction_ai(llm, paper, hyp_context),
            "disease_background": self._generate_disease_background_ai(llm, paper),
            "methods": self._generate_methods_ai(llm, paper),
            "citations": self._citation_validator.validate_and_collect_citations(
                paper.disease, paper.hypotheses, paper.external_factors,
            ),
        }

        phase1_results = await asyncio.gather(
            *[asyncio.create_task(coro) for coro in phase1_tasks.values()],
            return_exceptions=True,
        )

        for (key, _), result in zip(phase1_tasks.items(), phase1_results):
            if isinstance(result, Exception):
                logger.error(f"Phase 1 section '{key}' failed: {result}")
                raise RuntimeError(f"Paper generation failed: section '{key}' error: {result}")
            if key == "citations":
                paper.references = result
            else:
                paper.sections[key] = result

        # Phase 2: Sections that depend on phase 1 content (use full context)
        phase2_tasks = {
            "results_overview": self._generate_results_overview_ai(llm, paper, hyp_context),
            "hypothesis_analyses": self._generate_hypothesis_deep_analyses(llm, paper),
            "external_factors_analysis": self._generate_external_factors_ai(llm, paper, substance_context),
            "molecular_mechanisms": self._generate_molecular_mechanisms_ai(llm, paper, hyp_context),
        }

        phase2_results = await asyncio.gather(
            *[asyncio.create_task(coro) for coro in phase2_tasks.values()],
            return_exceptions=True,
        )

        for (key, _), result in zip(phase2_tasks.items(), phase2_results):
            if isinstance(result, Exception):
                logger.error(f"Phase 2 section '{key}' failed: {result}")
                raise RuntimeError(f"Paper generation failed: section '{key}' error: {result}")
            paper.sections[key] = result

        # Phase 3: Discussion, Conclusion, and figures (depend on results)
        phase3_tasks = {
            "discussion": self._generate_discussion_ai(llm, paper, hyp_context),
            "limitations_future": self._generate_limitations_future_ai(llm, paper),
            "conclusion": self._generate_conclusion_ai(llm, paper, hyp_context),
            "plotly_figures": self._generate_plotly_figures(paper),
            "tables": self._generate_tables(paper),
        }

        phase3_results = await asyncio.gather(
            *[asyncio.create_task(coro) for coro in phase3_tasks.values()],
            return_exceptions=True,
        )

        for (key, _), result in zip(phase3_tasks.items(), phase3_results):
            if isinstance(result, Exception):
                logger.error(f"Phase 3 section '{key}' failed: {result}")
                raise RuntimeError(f"Paper generation failed: section '{key}' error: {result}")
            if key == "plotly_figures":
                paper.plotly_figures = result
            elif key == "tables":
                paper.tables = result
            else:
                paper.sections[key] = result

        # Build dynamic TOC from generated sections
        paper.toc = self._build_dynamic_toc(paper)

    def _build_hypothesis_context(self, paper: ResearchPaper) -> str:
        """Build a rich context string from all hypotheses for LLM prompts."""
        lines = []
        for i, h in enumerate(paper.hypotheses[:20], 1):
            conf = h.get("confidence", 0)
            lines.append(
                f"Hypothesis {i}: {h.get('title', 'Untitled')}\n"
                f"  Confidence: {conf:.1%} | Model: {h.get('model_used', 'unknown')}\n"
                f"  Mechanism: {h.get('mechanism', 'Not specified')}\n"
                f"  Description: {h.get('description', 'N/A')}\n"
                f"  Validated: {'Yes' if h.get('validated') else 'No'}"
            )
        return "\n\n".join(lines)

    def _build_substance_context(self, paper: ResearchPaper) -> str:
        """Build context from external factors/substances."""
        if not paper.external_factors:
            return "No external factors specified."

        by_category: dict[str, list] = {}
        for f in paper.external_factors:
            cat = f.get("category", "other")
            by_category.setdefault(cat, []).append(f)

        lines = []
        for cat, factors in by_category.items():
            names = [f.get("name", "Unknown") for f in factors]
            lines.append(f"{cat.title()}: {', '.join(names)}")

        return "\n".join(lines)

    # =========================================================================
    # AI-Generated Sections — Each uses a specific model for its strengths
    # =========================================================================

    async def _generate_title_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        top_hyp = paper.hypotheses[0] if paper.hypotheses else {}
        type_label = {
            "cure": "Therapeutic Strategies",
            "prevention": "Prevention Strategies",
            "treatment": "Therapeutic Strategies",
            "biomarker": "Biomarker Discovery",
            "drug_repurposing": "Drug Repurposing Candidates",
            "combination_therapy": "Combination Therapy Approaches",
        }.get(paper.discovery_type, "Therapeutic Strategies")

        prompt = f"""Generate a precise, FDA/R&D publication-ready title for a research paper.

Disease: {paper.disease}
Discovery type: {type_label}
Top finding: {top_hyp.get('title', 'Multi-model AI discovery')}
Total hypotheses: {len(paper.hypotheses)}
Models used: Claude Opus 4.6, DeepSeek-R1-0528, Mistral-Large-3

Return ONLY the title text, no quotes, no explanation. The title should be concise (under 200 characters), scientifically precise, and reflect the multi-model AI approach. Format as: "Title — by Humanovo"."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.2, max_tokens=500)

    async def _generate_abstract_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a comprehensive scientific abstract (350-450 words) for an FDA/R&D-grade research paper.

Disease under investigation: {paper.disease}
Discovery type: {paper.discovery_type}
Total hypotheses generated: {len(paper.hypotheses)}
Best confidence achieved: {paper.stats.get('current_best_confidence', 0):.1%}
Total agents deployed: {paper.stats.get('total_agents', 0)}
Models used: Claude Opus 4.6 (exploration + synthesis), DeepSeek-R1-0528 (chain-of-thought reasoning), Mistral-Large-3 (critical analysis)
Runtime: {paper.stats.get('runtime_seconds', 0):.0f} seconds
External factors analyzed: {len(paper.external_factors)}
High confidence discoveries (>=70%): {paper.stats.get('high_confidence_discoveries', 0)}

Top 5 hypotheses:
{chr(10).join(f"- {h.get('title','N/A')} (confidence: {h.get('confidence',0):.1%})" for h in paper.hypotheses[:5])}

Structure the abstract with these labeled sections:
Background: (disease context and need for AI-driven discovery)
Methods: (multi-model parallel agent system, knowledge graph exploration, external factor simulation)
Results: (key findings, confidence levels, novel mechanisms identified)
Conclusions: (significance, translational potential, next steps)

IMPORTANT: This is an FDA/R&D-grade document. Be scientifically precise, cite specific molecular targets, pathways, and mechanisms. Do NOT hallucinate any data or statistics — only report what is provided above. Write in formal academic style."""

        return await llm.generate(ModelType.DEEPSEEK_R1_0528, prompt, temperature=0.2, max_tokens=8_000)

    async def _generate_introduction_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a comprehensive Introduction section (800-1200 words) for a research paper about AI-driven discovery of {paper.discovery_type} strategies for {paper.disease}.

This must cover ALL of the following in depth:

1. DISEASE EPIDEMIOLOGY AND BURDEN (200+ words)
   - Global prevalence, incidence, mortality statistics for {paper.disease}
   - Economic burden and quality of life impact
   - Current demographic trends

2. CURRENT THERAPEUTIC LANDSCAPE (200+ words)
   - Existing approved treatments and their mechanisms
   - Standard of care protocols
   - Key limitations: efficacy gaps, resistance, side effects, cost

3. AI AND MULTI-MODEL SYSTEMS IN DRUG DISCOVERY (200+ words)
   - Evolution from single-model to multi-model AI systems
   - Advantages of parallel reasoning with diverse architectures
   - Recent breakthroughs in AI-assisted drug discovery
   - How our 3-model approach (Claude Opus 4.6 for synthesis, DeepSeek-R1-0528 for reasoning, Mistral-Large-3 for critical analysis) advances the field

4. ROLE OF EXTERNAL FACTORS (150+ words)
   - Nutrients, chemicals, drugs, natural compounds, trace elements in disease modulation
   - Why holistic factor analysis matters
   - External factors analyzed: {self._build_substance_context(paper)}

5. STUDY OBJECTIVES (100+ words)
   - Specific aims of this investigation
   - How {paper.stats.get('total_agents', 0)} agents were deployed
   - What makes this approach novel

IMPORTANT: This is an FDA/R&D-grade document. Include specific molecular formulas where relevant (e.g., C₂₁H₃₀O₂ for progesterone). Reference specific receptor types (e.g., NMDA, GABA-A, TLR4). Do NOT hallucinate — only state facts that are well-established in biomedical literature.

Write in formal academic style with clear paragraph transitions. Use specific scientific terminology. Do NOT include section headers — write flowing paragraphs."""

        return await llm.generate(ModelType.DEEPSEEK_R1_0528, prompt, temperature=0.2, max_tokens=16_000)

    async def _generate_disease_background_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a detailed Disease Background section (600-800 words) for {paper.disease}.

Cover in depth:
1. PATHOPHYSIOLOGY: Molecular and cellular mechanisms driving {paper.disease}
   - Key genes, proteins, and signaling pathways involved
   - Cellular processes disrupted (apoptosis, metabolism, immune evasion, etc.)
   - Tissue and organ-level effects

2. GENETIC LANDSCAPE: Known genetic associations
   - Key mutations, polymorphisms, and risk variants
   - Epigenetic modifications relevant to disease
   - Pharmacogenomic considerations

3. ENVIRONMENTAL AND LIFESTYLE FACTORS
   - Known risk factors and protective factors
   - Nutrient deficiencies or excesses linked to disease
   - Chemical exposures and their mechanisms

4. BIOMARKERS AND DIAGNOSIS
   - Current diagnostic approaches
   - Known biomarkers and their limitations
   - Emerging diagnostic technologies

IMPORTANT: This is an FDA/R&D-grade document. Include specific gene names (e.g., TP53, BRCA1, EGFR), protein names, pathway identifiers (e.g., PI3K/AKT/mTOR, MAPK/ERK, Wnt/β-catenin). Include molecular formulas for key compounds. Do NOT hallucinate — only state well-established biomedical facts.

Write in formal academic style. Be scientifically precise. Do NOT use section headers — write flowing paragraphs with logical transitions."""

        return await llm.generate(ModelType.MISTRAL_LARGE_3, prompt, temperature=0.2, max_tokens=16_000)

    async def _generate_methods_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        agents_by_role = paper.stats.get("agents_by_role", {})
        token_stats = paper.stats.get("token_pool_stats", {})

        ext_factors_summary = ""
        if paper.external_factors:
            categories = {}
            for f in paper.external_factors:
                cat = f.get("category", "other")
                categories.setdefault(cat, []).append(f.get("name", "Unknown"))
            ext_lines = [f"  {cat}: {', '.join(names)}" for cat, names in categories.items()]
            ext_factors_summary = "\n".join(ext_lines)

        prompt = f"""Write a comprehensive Methods section (1000-1400 words) for a research paper about multi-model AI discovery.

PLATFORM DETAILS:
- Platform: Humanovo Multi-Model Discovery System
- Total agents: {paper.stats.get('total_agents', 0)}
- Agent roles and distribution: {json.dumps(agents_by_role)}
- Batch size: {settings.TOKEN_POOL_AGENT_BATCH_SIZE} agents per dispatch cycle

MODELS USED (describe each architecture and role):
1. Claude Opus 4.6 (Anthropic, via AWS Bedrock) — Exploration + synthesis, 200K context, temperature 0.2-0.4
2. DeepSeek-R1-0528 (via Azure AI) — Deep chain-of-thought reasoning, 64K output, temperature 0.15-0.2
3. Mistral-Large-3 (via Azure AI) — Critical analysis + validation, 32K output, temperature 0.2-0.3

TOKEN POOL MANAGEMENT:
- Max concurrent requests per model: {settings.TOKEN_POOL_MAX_CONCURRENT_REQUESTS}
- Global rate limit: {settings.TOKEN_POOL_MAX_TOKENS_PER_MINUTE:,} tokens/minute
- Backoff strategy: exponential with base {settings.TOKEN_POOL_RETRY_BACKOFF_BASE}

KNOWLEDGE GRAPH:
- Entities explored from Neo4j biological knowledge graph
- Neighborhood depth: 2 hops, 50 connections per entity
- Synthetic fallback graph with genes, proteins, drugs, nutrients, pathways

AGENT ARCHITECTURE:
- Explorer agents (40%): Broad pathway discovery
- Reasoner agents (25%): Deep causal chain analysis
- Validator agents (15%): Evidence quality verification
- Synthesizer agents (10%): Cross-hypothesis integration
- Critic agents (10%): Flaw and risk identification

EXTERNAL FACTORS SIMULATED:
{ext_factors_summary if ext_factors_summary else "All relevant nutrients, chemicals, drugs, compounds, elements analyzed"}

CONFIDENCE SCORING FORMULA:
- Direct clinical evidence: weight 0.40
- Mechanistic plausibility: weight 0.25
- Preclinical evidence: weight 0.20
- Computational predictions: weight 0.10
- Expert consensus: weight 0.05

PAPER GENERATION:
- All sections generated by AI models in parallel (no templates)
- Citations validated against PubMed API in real-time
- Plotly visualizations generated from actual data
- 30-minute hard timeout on generation

IMPORTANT: This is an FDA/R&D-grade methods section. Include:
- Exact model identifiers and API versions
- Precise temperature and top_p parameters for each model
- Token pool configuration numbers
- Confidence scoring formula with exact weights
- Include a text-based flowchart of the pipeline using ASCII art:

    Input Disease → Knowledge Graph Exploration → Agent Distribution
         ↓                    ↓                        ↓
    Claude Opus 4.6    DeepSeek-R1-0528         Mistral-Large-3
    (Explorer/Synth)   (Reasoner)               (Critic/Validator)
         ↓                    ↓                        ↓
         └──────────→ Hypothesis Pool ←────────────────┘
                           ↓
                  Confidence Scoring → Paper Generation

Write as formal Methods text. Use subsections with ### headers for: Multi-Model Discovery Platform, Agent Architecture, Token Pool Management, Knowledge Graph Integration, External Factor Simulation, Confidence Scoring, Research Paper Generation. Be technically precise. Do NOT hallucinate parameters — use only the values provided."""

        return await llm.generate(ModelType.DEEPSEEK_R1_0528, prompt, temperature=0.15, max_tokens=16_000)

    async def _generate_results_overview_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write the Results Overview section (400-600 words) for a research paper.

Discovery run statistics:
- Disease: {paper.disease}
- Total agents: {paper.stats.get('total_agents', 0)}
- Pathways explored: {paper.stats.get('paths_explored', 0):,}
- Runtime: {paper.stats.get('runtime_seconds', 0):.0f} seconds
- Total hypotheses generated: {len(paper.hypotheses)}
- High confidence (>=70%): {paper.stats.get('high_confidence_discoveries', 0)}
- Best confidence: {paper.stats.get('current_best_confidence', 0):.1%}
- Models active: {', '.join(paper.stats.get('models_active', []))}

Token pool usage: {json.dumps(paper.stats.get('token_pool_stats', {}))}
Learning memory stats: {json.dumps(paper.stats.get('learning_stats', {}))}

Summarize the overall discovery results:
1. Scale of exploration (paths, agents, runtime)
2. Distribution of confidence scores across hypotheses
3. Performance comparison across models
4. Learning system effectiveness (low-value paths skipped, high-value amplified)
5. Token efficiency across models

Write in formal results style. Report numbers precisely. No interpretation — save that for Discussion."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.25, max_tokens=16_000)

    async def _generate_hypothesis_deep_analyses(self, llm, paper: ResearchPaper) -> str:
        """Generate detailed analysis of each hypothesis using different models in parallel."""
        from app.agents.discovery_orchestrator import ModelType

        analyses = []
        # Distribute hypotheses across discovery models for diverse analysis perspectives
        model_cycle = [ModelType.CLAUDE_OPUS, ModelType.DEEPSEEK_R1_0528, ModelType.MISTRAL_LARGE_3]

        async def analyze_single(idx: int, hyp: dict) -> str:
            model = model_cycle[idx % len(model_cycle)]
            prompt = f"""Write a detailed FDA/R&D-grade scientific analysis (400-600 words) for this hypothesis about {paper.disease}:

Hypothesis: {hyp.get('title', 'Untitled')}
Description: {hyp.get('description', 'N/A')}
Mechanism: {hyp.get('mechanism', 'Not specified')}
Confidence: {hyp.get('confidence', 0):.1%}
Model used for discovery: {hyp.get('model_used', 'unknown')}
External factor interactions: {json.dumps(hyp.get('external_factors', []))}

Cover in your analysis:
1. Scientific rationale and biological plausibility with specific pathway references
2. Detailed mechanism of action at molecular level — include a text-based mechanism diagram:
   [Ligand] → [Receptor] → [Signaling Cascade] → [Transcription Factor] → [Gene Expression] → [Phenotype]
3. Existing supporting evidence from literature (reference specific studies)
4. Potential therapeutic modalities (small molecule, biologic, gene therapy, etc.)
5. Key risks, toxicity concerns, and off-target effects
6. Required experimental validation steps (in vitro, in vivo, clinical phases)
7. Patient population considerations and stratification
8. Comparison with existing treatments for {paper.disease}

Include any relevant molecular formulas (e.g., IC50 values, binding affinities in nM/μM).
IMPORTANT: Do NOT hallucinate data. Only state well-established biomedical facts.

Write as formal FDA/R&D-grade scientific text. Be specific, not generic."""

            return await llm.generate(model, prompt, temperature=0.2, max_tokens=8_000)

        # Process in batches of 4 (one per model)
        for batch_start in range(0, min(len(paper.hypotheses), 20), 4):
            batch = paper.hypotheses[batch_start:batch_start + 4]
            batch_tasks = [
                analyze_single(batch_start + i, h)
                for i, h in enumerate(batch)
            ]
            batch_results = await asyncio.gather(*batch_tasks, return_exceptions=True)
            for i, result in enumerate(batch_results):
                idx = batch_start + i
                hyp = paper.hypotheses[idx]
                if isinstance(result, Exception):
                    analyses.append(
                        f"### Hypothesis {idx + 1}: {hyp.get('title', 'Untitled')}\n\n"
                        f"**Confidence**: {hyp.get('confidence', 0):.1%} | "
                        f"**Model**: {hyp.get('model_used', 'unknown')}\n\n"
                        f"Analysis generation encountered an error: {result}\n\n"
                        f"**Mechanism**: {hyp.get('mechanism', 'Not specified')}\n\n"
                        f"{hyp.get('description', 'No description available.')}"
                    )
                else:
                    analyses.append(
                        f"### Hypothesis {idx + 1}: {hyp.get('title', 'Untitled')}\n\n"
                        f"**Confidence**: {hyp.get('confidence', 0):.1%} | "
                        f"**Model**: {hyp.get('model_used', 'unknown')} | "
                        f"**Validated**: {'Yes' if hyp.get('validated') else 'Pending'}\n\n"
                        f"{result}"
                    )

        return "\n\n---\n\n".join(analyses)

    async def _generate_external_factors_ai(self, llm, paper: ResearchPaper, substance_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        if not paper.external_factors:
            prompt = f"""Write a section (400-600 words) about the role of external factors in {paper.disease} treatment.

Since no specific external factors were configured for this run, discuss:
1. Key nutrients known to affect {paper.disease} (vitamins, minerals, amino acids)
2. Natural compounds with evidence for {paper.disease} (curcumin, resveratrol, quercetin, EGCG, etc.)
3. Environmental chemicals and their disease-modulating effects
4. Drug-nutrient and drug-drug interactions relevant to treatment
5. Trace elements and their roles in disease pathways

IMPORTANT: Do NOT hallucinate. Only state well-established biomedical facts. Include specific compound formulas and mechanisms.
Write as formal scientific text with specific examples and mechanisms."""

            return await llm.generate(ModelType.MISTRAL_LARGE_3, prompt, temperature=0.2, max_tokens=16_000)

        prompt = f"""Write a comprehensive External Factors Analysis section (600-1000 words) for a {paper.disease} research paper.

External factors analyzed in this study:
{substance_context}

Full factor details:
{json.dumps([{k: v for k, v in f.items()} for f in paper.external_factors[:30]], indent=2)}

For each category of factors, write a detailed analysis covering:
1. **Mechanism of interaction** with {paper.disease} pathways
2. **Synergistic effects** when combined with identified therapeutic hypotheses
3. **Antagonistic effects** that could reduce treatment efficacy
4. **Dosing considerations** and therapeutic windows
5. **Drug-nutrient interactions** and contraindications
6. **Evidence quality** for each factor's therapeutic role

Organize by category (Nutrients, Compounds, Drugs, Chemicals, Elements).

Include for each factor:
- Molecular formula and structure description
- Mechanism of action text diagram: [Factor] → [Target] → [Pathway] → [Effect]
- Known dosing ranges from literature

IMPORTANT: Do NOT hallucinate. Only state well-established biomedical facts.
Write as formal FDA/R&D-grade scientific text. Be specific about molecular mechanisms."""

        return await llm.generate(ModelType.MISTRAL_LARGE_3, prompt, temperature=0.2, max_tokens=16_000)

    async def _generate_molecular_mechanisms_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        top_hyps = paper.hypotheses[:5]
        prompt = f"""Write a detailed Molecular Mechanisms section (600-800 words) for a {paper.disease} research paper.

Based on the top hypotheses:
{chr(10).join(f"- {h.get('title','N/A')}: {h.get('mechanism','N/A')}" for h in top_hyps)}

Describe in scientific detail:
1. The key molecular pathways implicated across all top hypotheses
2. How identified targets (genes, proteins, receptors) relate to disease pathogenesis
3. Signaling cascades that could be therapeutically modulated
4. Cross-talk between pathways identified by different hypotheses
5. How external factors (nutrients, compounds) interact with these molecular mechanisms
6. Potential resistance mechanisms and how to overcome them
7. Biomarker opportunities arising from these mechanisms

Include text-based pathway diagrams where relevant, for example:

    Growth Factor → RTK → RAS → RAF → MEK → ERK → Transcription
                                        ↓
                              PI3K → AKT → mTOR → Protein Synthesis

Include relevant kinetic parameters (Km, Kd, IC50) where well-established.
IMPORTANT: Do NOT hallucinate. Only state well-established biomedical facts. Use specific gene/protein names (with UniProt/HGNC identifiers where possible), pathway identifiers, and molecular interactions.

Write as formal FDA/R&D-grade scientific text. No headers — flowing paragraphs."""

        return await llm.generate(ModelType.DEEPSEEK_R1_0528, prompt, temperature=0.15, max_tokens=32_000)

    async def _generate_discussion_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        top_titles = [h.get("title", "N/A") for h in paper.hypotheses[:5]]
        prompt = f"""Write a comprehensive Discussion section (800-1200 words) for a research paper about AI-driven discovery for {paper.disease}.

Key findings to discuss:
- Top hypotheses: {', '.join(top_titles)}
- Best confidence achieved: {paper.stats.get('current_best_confidence', 0):.1%}
- Total hypotheses: {len(paper.hypotheses)}
- Models used: Claude Opus 4.6, DeepSeek-R1-0528, Mistral-Large-3
- External factors analyzed: {len(paper.external_factors)}
- Paths explored: {paper.stats.get('paths_explored', 0):,}

Cover ALL of the following:

1. SIGNIFICANCE OF FINDINGS (200+ words)
   - What these discoveries mean for {paper.disease} treatment
   - How they compare to existing therapeutic approaches
   - Novel mechanisms identified that were not previously known

2. MULTI-MODEL ADVANTAGE (200+ words)
   - How different models contributed different insights
   - Complementary reasoning perspectives
   - Value of parallel agent architecture vs. single-model approaches

3. EXTERNAL FACTOR INSIGHTS (150+ words)
   - Novel nutrient-disease interactions discovered
   - Drug repurposing opportunities from external factor analysis
   - Synergistic combinations identified

4. COMPARISON WITH EXISTING LITERATURE (200+ words)
   - How findings align with or diverge from published research
   - Novel contributions beyond state of the art
   - Validation status of key claims

5. TRANSLATIONAL POTENTIAL (150+ words)
   - Path from AI hypothesis to clinical application
   - Recommended experimental validations
   - Timeline and feasibility considerations

IMPORTANT: Do NOT hallucinate. Base discussion on the provided data only.
Write in formal FDA/R&D-grade academic discussion style. Be balanced — acknowledge both strengths and weaknesses."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.25, max_tokens=32_000)

    async def _generate_limitations_future_ai(self, llm, paper: ResearchPaper) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a Limitations and Future Directions section (500-700 words) for a research paper on AI-driven {paper.disease} discovery.

Current study parameters:
- {paper.stats.get('total_agents', 0)} agents across 3 models (Claude Opus 4.6, DeepSeek-R1-0528, Mistral-Large-3)
- {len(paper.hypotheses)} hypotheses generated
- {paper.stats.get('paths_explored', 0):,} paths explored
- Runtime: {paper.stats.get('runtime_seconds', 0):.0f} seconds

Cover honestly and thoroughly:

LIMITATIONS:
1. AI-generated hypotheses require experimental validation
2. Confidence scores are model-dependent and may not reflect true clinical probability
3. Knowledge graph completeness and currency limitations
4. Token pool constraints at maximum agent scale
5. Potential biases in training data of underlying models
6. Lack of wet-lab integration in current pipeline
7. External factor interactions are computationally predicted, not experimentally verified

FUTURE DIRECTIONS:
1. Integration with automated wet-lab systems for hypothesis validation
2. Expansion of knowledge graph with real-time literature monitoring
3. Addition of protein structure prediction (AlphaFold integration)
4. Multi-omics data integration (genomics, proteomics, metabolomics)
5. Clinical trial design automation based on top hypotheses
6. Federated learning across multiple institutions
7. Real-time patient data integration for personalized discovery

IMPORTANT: Do NOT hallucinate. Be honest about limitations.
Write as formal FDA/R&D-grade scientific text."""

        return await llm.generate(ModelType.MISTRAL_LARGE_3, prompt, temperature=0.25, max_tokens=16_000)

    async def _generate_conclusion_ai(self, llm, paper: ResearchPaper, hyp_context: str) -> str:
        from app.agents.discovery_orchestrator import ModelType

        prompt = f"""Write a strong Conclusion section (300-400 words) for a research paper on AI-driven {paper.disease} discovery.

Summarize:
- {paper.stats.get('total_agents', 0)} parallel agents across 3 LLMs (Claude Opus, DeepSeek-R1-0528, Mistral-Large-3) identified {len(paper.hypotheses)} hypotheses
- Best confidence: {paper.stats.get('current_best_confidence', 0):.1%}
- Top finding: {paper.hypotheses[0].get('title', 'N/A') if paper.hypotheses else 'N/A'}
- {len(paper.external_factors)} external factors integrated
- Multi-model approach with token pool management enabled unprecedented scale

End with:
1. The key take-away message for the scientific community
2. The most actionable finding for translational researchers
3. The broader implications for AI-driven drug discovery

Be concise, impactful, and forward-looking. Avoid repeating the abstract."""

        return await llm.generate(ModelType.CLAUDE_OPUS, prompt, temperature=0.3, max_tokens=8_000)

    # =========================================================================
    # Plotly Figures — Interactive chart specifications for frontend
    # =========================================================================

    async def _generate_plotly_figures(self, paper: ResearchPaper) -> list[dict[str, Any]]:
        """Generate Plotly JSON specifications for interactive visualizations."""
        figures = []

        # Figure 1: Hypothesis Confidence Distribution (bar chart)
        confidences = [h.get("confidence", 0) for h in paper.hypotheses]
        titles = [h.get("title", f"H{i+1}")[:40] for i, h in enumerate(paper.hypotheses[:20])]
        models = [h.get("model_used", "unknown") for h in paper.hypotheses[:20]]

        model_colors = {
            "claude_opus": "#FF6B35",
            "deepseek_r1_0528": "#4ECDC4",
            "mistral_large_3": "#A855F7",
            "deepseek_r1": "#4ECDC4",
        }
        colors = [model_colors.get(m, "#6B7280") for m in models]

        figures.append({
            "id": "fig_confidence_bar",
            "caption": "Figure 1. Hypothesis Confidence Scores by Discovery Model",
            "type": "plotly",
            "spec": {
                "data": [{
                    "type": "bar",
                    "x": titles,
                    "y": [c * 100 for c in confidences[:20]],
                    "marker": {"color": colors},
                    "text": [f"{c:.1%}" for c in confidences[:20]],
                    "textposition": "outside",
                    "hovertemplate": "<b>%{x}</b><br>Confidence: %{y:.1f}%<br>Model: %{customdata}<extra></extra>",
                    "customdata": models,
                }],
                "layout": {
                    "title": {"text": f"Top Hypotheses for {paper.disease}", "font": {"size": 16}},
                    "xaxis": {"title": "Hypothesis", "tickangle": -45},
                    "yaxis": {"title": "Confidence (%)", "range": [0, 105]},
                    "template": "plotly_dark",
                    "height": 500,
                    "margin": {"b": 150},
                },
            },
        })

        # Figure 2: Confidence Distribution Histogram
        buckets = {"<30%": 0, "30-50%": 0, "50-70%": 0, "70-90%": 0, ">=90%": 0}
        for c in confidences:
            if c < 0.3:
                buckets["<30%"] += 1
            elif c < 0.5:
                buckets["30-50%"] += 1
            elif c < 0.7:
                buckets["50-70%"] += 1
            elif c < 0.9:
                buckets["70-90%"] += 1
            else:
                buckets[">=90%"] += 1

        figures.append({
            "id": "fig_confidence_dist",
            "caption": "Figure 2. Distribution of Confidence Scores Across All Hypotheses",
            "type": "plotly",
            "spec": {
                "data": [{
                    "type": "bar",
                    "x": list(buckets.keys()),
                    "y": list(buckets.values()),
                    "marker": {
                        "color": ["#EF4444", "#F97316", "#EAB308", "#22C55E", "#10B981"],
                    },
                    "text": list(buckets.values()),
                    "textposition": "outside",
                }],
                "layout": {
                    "title": {"text": "Confidence Score Distribution", "font": {"size": 16}},
                    "xaxis": {"title": "Confidence Range"},
                    "yaxis": {"title": "Number of Hypotheses"},
                    "template": "plotly_dark",
                    "height": 400,
                },
            },
        })

        # Figure 3: Model Performance Comparison (grouped bar)
        token_stats = paper.stats.get("token_pool_stats", {})
        requests = token_stats.get("requests_per_model", {})
        errors = token_stats.get("errors_per_model", {})
        model_names = ["claude_opus", "deepseek_r1_0528", "mistral_large_3"]
        display_names = ["Claude Opus 4.6", "DeepSeek-R1-0528", "Mistral-Large-3"]

        figures.append({
            "id": "fig_model_performance",
            "caption": "Figure 3. Model Performance Comparison: Requests vs Errors",
            "type": "plotly",
            "spec": {
                "data": [
                    {
                        "type": "bar",
                        "name": "Requests",
                        "x": display_names,
                        "y": [requests.get(m, 0) for m in model_names],
                        "marker": {"color": "#3B82F6"},
                    },
                    {
                        "type": "bar",
                        "name": "Errors",
                        "x": display_names,
                        "y": [errors.get(m, 0) for m in model_names],
                        "marker": {"color": "#EF4444"},
                    },
                ],
                "layout": {
                    "title": {"text": "Model Usage and Error Rates", "font": {"size": 16}},
                    "barmode": "group",
                    "xaxis": {"title": "Model"},
                    "yaxis": {"title": "Count"},
                    "template": "plotly_dark",
                    "height": 400,
                },
            },
        })

        # Figure 4: Agent Role Distribution (pie chart)
        agents_by_role = paper.stats.get("agents_by_role", {})
        if agents_by_role:
            figures.append({
                "id": "fig_agent_roles",
                "caption": "Figure 4. Agent Distribution by Role",
                "type": "plotly",
                "spec": {
                    "data": [{
                        "type": "pie",
                        "labels": [r.title() for r in agents_by_role.keys()],
                        "values": list(agents_by_role.values()),
                        "hole": 0.4,
                        "marker": {
                            "colors": ["#FF6B35", "#4ECDC4", "#A855F7", "#3B82F6", "#EAB308"],
                        },
                        "textinfo": "label+percent",
                    }],
                    "layout": {
                        "title": {"text": "Agent Role Distribution", "font": {"size": 16}},
                        "template": "plotly_dark",
                        "height": 400,
                    },
                },
            })

        # Figure 5: External Factors by Category (treemap)
        if paper.external_factors:
            factor_labels = []
            factor_parents = []
            factor_values = []

            categories = {}
            for f in paper.external_factors:
                cat = f.get("category", "other").title()
                categories.setdefault(cat, []).append(f.get("name", "Unknown"))

            factor_labels.append("External Factors")
            factor_parents.append("")
            factor_values.append(0)

            for cat, names in categories.items():
                factor_labels.append(cat)
                factor_parents.append("External Factors")
                factor_values.append(len(names))
                for name in names:
                    factor_labels.append(name)
                    factor_parents.append(cat)
                    factor_values.append(1)

            figures.append({
                "id": "fig_external_factors",
                "caption": "Figure 5. External Factors Analyzed by Category",
                "type": "plotly",
                "spec": {
                    "data": [{
                        "type": "treemap",
                        "labels": factor_labels,
                        "parents": factor_parents,
                        "values": factor_values,
                        "textinfo": "label+value",
                        "marker": {"colorscale": "Viridis"},
                    }],
                    "layout": {
                        "title": {"text": "External Factor Categories", "font": {"size": 16}},
                        "template": "plotly_dark",
                        "height": 500,
                    },
                },
            })

        # Figure 6: Discovery Pipeline Flowchart (Mermaid — kept for compatibility)
        figures.append({
            "id": "fig_pipeline",
            "caption": "Figure 6. Humanovo Multi-Model Discovery Pipeline",
            "type": "mermaid",
            "spec": (
                "graph TD\n"
                f"    A[Disease: {paper.disease}] --> B[Knowledge Graph]\n"
                "    B --> C{Agent Distribution}\n"
                "    C --> D[Claude Opus 4.6<br/>Explorer + Synthesizer]\n"
                "    C --> E[DeepSeek-R1-0528<br/>Chain-of-Thought Reasoner]\n"
                "    C --> F[Mistral-Large-3<br/>Critical Analyst]\n"
                "    D --> H[Hypothesis Pool]\n"
                "    E --> H\n"
                "    F --> H\n"
                "    H --> I{Confidence >= Target?}\n"
                "    I -->|Yes| J[Paper Generation<br/>3 Models Parallel]\n"
                "    I -->|No| K[Continue + Learn]\n"
                "    K --> C\n"
                "    L[External Factors] --> H\n"
                "    J --> M[PubMed Citation<br/>Validation]\n"
                "    J --> N[Plotly<br/>Visualizations]\n"
                "    M --> O[FDA/R&D Grade Paper]"
            ),
        })

        return figures

    # =========================================================================
    # Tables
    # =========================================================================

    async def _generate_tables(self, paper: ResearchPaper) -> list[dict[str, Any]]:
        """Generate data tables for the paper."""
        tables = []

        # Table 1: Top hypotheses with rich detail
        hyp_rows = []
        for i, h in enumerate(paper.hypotheses[:20], 1):
            hyp_rows.append({
                "rank": i,
                "title": h.get("title", "Untitled"),
                "confidence": f"{h.get('confidence', 0):.1%}",
                "model": h.get("model_used", "unknown"),
                "mechanism": (h.get("mechanism", "N/A"))[:100],
                "validated": "Yes" if h.get("validated") else "Pending",
            })

        tables.append({
            "id": "table_hypotheses",
            "caption": f"Table 1. Top {len(hyp_rows)} Discovery Hypotheses for {paper.disease}",
            "columns": ["Rank", "Hypothesis", "Confidence", "Model", "Mechanism", "Validated"],
            "rows": hyp_rows,
        })

        # Table 2: Model performance
        token_stats = paper.stats.get("token_pool_stats", {})
        model_rows = []
        for model_name, display in [
            ("claude_opus", "Claude Opus 4.6"),
            ("deepseek_r1_0528", "DeepSeek-R1-0528"),
            ("mistral_large_3", "Mistral-Large-3"),
        ]:
            reqs = token_stats.get("requests_per_model", {}).get(model_name, 0)
            tokens = token_stats.get("tokens_per_model", {}).get(model_name, 0)
            errs = token_stats.get("errors_per_model", {}).get(model_name, 0)
            success_rate = f"{((reqs - errs) / max(reqs, 1)) * 100:.1f}%" if reqs > 0 else "N/A"
            model_rows.append({
                "model": display,
                "requests": reqs,
                "tokens_used": f"{tokens:,}",
                "errors": errs,
                "success_rate": success_rate,
            })

        tables.append({
            "id": "table_models",
            "caption": "Table 2. Multi-Model Performance Comparison",
            "columns": ["Model", "Requests", "Tokens Used", "Errors", "Success Rate"],
            "rows": model_rows,
        })

        # Table 3: External factors
        if paper.external_factors:
            factor_rows = []
            for f in paper.external_factors[:30]:
                factor_rows.append({
                    "name": f.get("name", "Unknown"),
                    "category": f.get("category", "unknown").title(),
                    "interaction": f.get("interaction", "To be determined"),
                })
            tables.append({
                "id": "table_factors",
                "caption": "Table 3. External Factors Analyzed",
                "columns": ["Factor", "Category", "Known Interaction"],
                "rows": factor_rows,
            })

        # Table 4: Hypothesis diversity metrics
        if len(paper.hypotheses) >= 5:
            model_counts = {}
            for h in paper.hypotheses:
                m = h.get("model_used", "unknown")
                model_counts[m] = model_counts.get(m, 0) + 1

            diversity_rows = []
            for model, count in model_counts.items():
                confs = [h.get("confidence", 0) for h in paper.hypotheses if h.get("model_used") == model]
                avg_conf = sum(confs) / len(confs) if confs else 0
                diversity_rows.append({
                    "model": model,
                    "hypotheses_generated": count,
                    "avg_confidence": f"{avg_conf:.1%}",
                    "max_confidence": f"{max(confs):.1%}" if confs else "N/A",
                    "min_confidence": f"{min(confs):.1%}" if confs else "N/A",
                })

            tables.append({
                "id": "table_diversity",
                "caption": "Table 4. Hypothesis Diversity by Model",
                "columns": ["Model", "Hypotheses Generated", "Avg Confidence", "Max Confidence", "Min Confidence"],
                "rows": diversity_rows,
            })

        return tables

    # =========================================================================
    # Dynamic Table of Contents
    # =========================================================================

    def _build_dynamic_toc(self, paper: ResearchPaper) -> list[dict[str, Any]]:
        """Build a fully dynamic TOC from generated sections."""
        toc = []
        section_order = [
            ("title", "Title Page", 0),
            ("abstract", "Abstract", 0),
            ("introduction", "Introduction", 0),
            ("disease_background", "Disease Background", 1),
            ("methods", "Methods", 0),
            ("results_overview", "Results Overview", 0),
            ("hypothesis_analyses", "Detailed Hypothesis Analyses", 1),
            ("molecular_mechanisms", "Molecular Mechanisms", 1),
            ("external_factors_analysis", "External Factors Analysis", 0),
            ("discussion", "Discussion", 0),
            ("limitations_future", "Limitations and Future Directions", 1),
            ("conclusion", "Conclusion", 0),
        ]

        idx = 1
        for section_key, display_name, depth in section_order:
            if section_key in paper.sections and paper.sections[section_key]:
                toc.append({
                    "id": f"section-{section_key}",
                    "label": display_name,
                    "section_key": section_key,
                    "depth": depth,
                    "index": idx,
                })
                idx += 1

        # Add tables and figures to TOC
        if paper.tables:
            toc.append({"id": "section-tables", "label": "Tables", "section_key": "tables", "depth": 0, "index": idx})
            idx += 1
        if paper.plotly_figures:
            toc.append({"id": "section-figures", "label": "Figures", "section_key": "figures", "depth": 0, "index": idx})
            idx += 1
        if paper.references:
            toc.append({"id": "section-references", "label": "References", "section_key": "references", "depth": 0, "index": idx})

        return toc

    # =========================================================================
    # Markdown Export
    # =========================================================================

    def paper_to_markdown(self, paper: ResearchPaper) -> str:
        """Convert a research paper to Markdown format with TOC."""
        md = []

        # Title
        md.append(f"# {paper.sections.get('title', 'Untitled Research Paper')}\n")
        md.append(f"*Generated by Humanovo Multi-Model Discovery Platform — {paper.created_at.strftime('%Y-%m-%d %H:%M UTC')}*\n")
        md.append(f"*Generation time: {paper.generation_time_seconds:.1f}s | "
                   f"Models: Claude Opus 4.6, DeepSeek-R1-0528, Mistral-Large-3 | "
                   f"All citations PubMed-verified*\n")
        md.append("---\n")

        # Table of Contents
        md.append("## Table of Contents\n")
        for entry in paper.toc:
            indent = "  " * entry.get("depth", 0)
            label = entry["label"]
            anchor = entry["id"]
            md.append(f"{indent}- [{entry['index']}. {label}](#{anchor})")
        md.append("\n---\n")

        # Sections
        section_headers = {
            "abstract": "Abstract",
            "introduction": "Introduction",
            "disease_background": "Disease Background",
            "methods": "Methods",
            "results_overview": "Results",
            "hypothesis_analyses": "Detailed Hypothesis Analyses",
            "molecular_mechanisms": "Molecular Mechanisms",
            "external_factors_analysis": "External Factors Analysis",
            "discussion": "Discussion",
            "limitations_future": "Limitations and Future Directions",
            "conclusion": "Conclusion",
        }

        for key, header in section_headers.items():
            content = paper.sections.get(key, "")
            if content:
                anchor_id = f"section-{key}"
                md.append(f"\n<a id=\"{anchor_id}\"></a>\n")
                if not content.strip().startswith("##"):
                    md.append(f"## {header}\n")
                md.append(content + "\n")

        # Tables
        if paper.tables:
            md.append("\n<a id=\"section-tables\"></a>\n")
            md.append("## Tables\n")
            for table in paper.tables:
                md.append(f"\n### {table['caption']}\n")
                cols = table["columns"]
                md.append("| " + " | ".join(cols) + " |")
                md.append("| " + " | ".join(["---"] * len(cols)) + " |")
                for row in table["rows"]:
                    values = []
                    for c in cols:
                        key = c.lower().replace(" ", "_")
                        val = row.get(key, "")
                        if val == "":
                            # Try direct column name
                            val = row.get(c.lower(), "")
                        values.append(str(val))
                    if all(v == "" for v in values):
                        values = [str(v) for v in row.values()]
                    md.append("| " + " | ".join(values) + " |")
                md.append("")

        # Plotly figures (as JSON code blocks for frontend rendering)
        if paper.plotly_figures:
            md.append("\n<a id=\"section-figures\"></a>\n")
            md.append("## Figures\n")
            for fig in paper.plotly_figures:
                md.append(f"\n### {fig['caption']}\n")
                if fig["type"] == "plotly":
                    md.append(f"```plotly\n{json.dumps(fig['spec'], indent=2)}\n```\n")
                elif fig["type"] == "mermaid":
                    md.append(f"```mermaid\n{fig['spec']}\n```\n")

        # References
        if paper.references:
            md.append("\n<a id=\"section-references\"></a>\n")
            md.append("## References\n")
            for ref in paper.references:
                doi_link = f" DOI: [{ref['doi']}]({ref['doi']})" if ref.get("doi") else ""
                pmid_link = f" PMID: {ref['pmid']}" if ref.get("pmid") else ""
                verified = " [Verified]" if ref.get("verified") else ""
                md.append(f"[{ref['id']}] {ref['text']}{doi_link}{pmid_link}{verified}\n")

        return "\n".join(md)


# Singleton
_paper_service: Optional[PaperGenerationService] = None


def get_paper_service() -> PaperGenerationService:
    global _paper_service
    if _paper_service is None:
        _paper_service = PaperGenerationService()
    return _paper_service
