import { useState, useEffect, useCallback, useRef } from 'react'
import {
  FiCheckCircle,
  FiPlay,
  FiPause,
  FiSquare,
  FiRefreshCw,
  FiTarget,
  FiSettings,
  FiChevronDown,
  FiChevronUp,
  FiAward,
  FiFileText,
  FiPlus,
  FiX,
  FiDownload,
  FiSend,
} from 'react-icons/fi'
import clsx from 'clsx'
import { persistGet, persistSet, logActivity } from '../utils/persistence'

// Types
type OrchestratorState = 'idle' | 'running' | 'paused' | 'stopping'

interface OrchestratorStats {
  state: OrchestratorState
  total_agents: number
  active_agents: number
  hypotheses_found: number
  paths_explored: number
  high_confidence_discoveries: number
  current_best_confidence: number
  runtime_seconds: number
  current_round?: number
  total_rounds?: number
  agents_by_role: Record<string, number>
  models_active?: string[]
  token_pool_stats?: {
    global_tokens_used: number
    requests_per_model: Record<string, number>
    errors_per_model: Record<string, number>
  }
  learning_stats: {
    total_explored: number
    low_value_paths: number
    high_value_paths: number
    avg_relation_score: number
  }
}

interface Hypothesis {
  id: string
  title: string
  description: string
  mechanism: string
  confidence: number
  validated: boolean
  external_factors?: Array<Record<string, string>>
  created_at?: string
}

interface ExternalFactor {
  name: string
  category: 'nutrient' | 'chemical' | 'drug' | 'compound' | 'element'
  interaction: string
}

interface DiscoveryConfig {
  disease: string
  discoveryType: 'cure' | 'prevention' | 'treatment' | 'biomarker' | 'drug_repurposing'
  focusEntities: string[]
  maxAgents: number
  targetConfidence: number
  externalFactors: ExternalFactor[]
}

const discoveryTypes = [
  { value: 'cure', label: 'Cure Discovery', description: 'Find curative treatments' },
  { value: 'prevention', label: 'Prevention Strategy', description: 'Prevent disease onset' },
  { value: 'treatment', label: 'Treatment Options', description: 'Manage symptoms and progression' },
  { value: 'biomarker', label: 'Biomarker Discovery', description: 'Early detection markers' },
  { value: 'drug_repurposing', label: 'Drug Repurposing', description: 'Existing drugs for new uses' },
]

const factorCategories = ['nutrient', 'chemical', 'drug', 'compound', 'element'] as const

const API_BASE = '/api/v1'

// Auto-generate tags from hypothesis content
function generateHypothesisTags(hypothesis: Hypothesis, disease: string, discoveryType: string): string[] {
  const tags: string[] = []
  if (disease) tags.push(disease.toLowerCase())
  tags.push(discoveryType)
  if (hypothesis.confidence >= 0.8) tags.push('high-confidence')
  else if (hypothesis.confidence >= 0.6) tags.push('medium-confidence')
  else tags.push('low-confidence')
  if (hypothesis.validated) tags.push('validated')
  if (hypothesis.external_factors && hypothesis.external_factors.length > 0) tags.push('external-factors')
  // Extract keywords from title
  const keywords = (hypothesis.title || '').toLowerCase().split(/\s+/)
  const bioTerms = ['gene', 'protein', 'pathway', 'receptor', 'inhibitor', 'mutation', 'therapy', 'immune', 'target', 'compound', 'enzyme', 'kinase', 'antibody', 'biomarker']
  for (const word of keywords) {
    if (bioTerms.some(t => word.includes(t)) && !tags.includes(word)) tags.push(word)
  }
  return tags.slice(0, 8)
}

// Save hypothesis to project library
function saveHypothesisToProject(hypothesis: Hypothesis, disease: string, discoveryType: string) {
  // Get existing projects
  const projects = persistGet<Array<{
    id: string; name: string; description?: string; disease_focus?: string;
    research_question?: string; tags: string[]; hypothesis_count: number;
    evidence_count: number; status: string; created_at: string; updated_at: string;
  }>>('projects', [])

  // Find or create project for this disease
  let project = projects.find(p => p.disease_focus?.toLowerCase() === disease.toLowerCase())
  if (!project) {
    project = {
      id: `proj-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name: `${disease} — ${discoveryType.charAt(0).toUpperCase() + discoveryType.slice(1)} Research`,
      description: `AI-driven ${discoveryType} discovery for ${disease}. Hypotheses generated by humanovo's multi-model parallel agent system.`,
      disease_focus: disease,
      research_question: `What are the most promising ${discoveryType} approaches for ${disease}?`,
      tags: [disease.toLowerCase(), discoveryType, 'ai-generated'],
      hypothesis_count: 0,
      evidence_count: 0,
      status: 'active',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
    projects.unshift(project)
    logActivity({ type: 'project', action: 'created', title: `Auto-created project: ${project.name}`, metadata: { source: 'discovery' } })
  }

  // Get existing saved hypotheses
  const savedHypotheses = persistGet<Array<{
    id: string; title: string; description: string; mechanism: string;
    confidence: number; tags: string[]; disease: string; discovery_type: string;
    project_id: string; created_at: string;
  }>>('hypotheses', [])

  // Check if this hypothesis is already saved
  if (savedHypotheses.some(h => h.id === hypothesis.id)) return

  // Save hypothesis with AI-filled metadata
  const tags = generateHypothesisTags(hypothesis, disease, discoveryType)
  savedHypotheses.unshift({
    id: hypothesis.id,
    title: hypothesis.title,
    description: hypothesis.description,
    mechanism: hypothesis.mechanism,
    confidence: hypothesis.confidence,
    tags,
    disease,
    discovery_type: discoveryType,
    project_id: project.id,
    created_at: hypothesis.created_at || new Date().toISOString(),
  })

  // Update project counts
  project.hypothesis_count = savedHypotheses.filter(h => h.project_id === project.id).length
  project.updated_at = new Date().toISOString()

  // Persist
  persistSet('hypotheses', savedHypotheses.slice(0, 200))
  persistSet('projects', projects)
  logActivity({
    type: 'hypothesis',
    action: 'created',
    title: `Discovered: ${hypothesis.title}`,
    project: project.name,
    metadata: { confidence: hypothesis.confidence, disease, tags },
  })
}

export default function Agents() {
  // Orchestrator state
  const [state, setState] = useState<OrchestratorState>('idle')
  const [stats, setStats] = useState<OrchestratorStats | null>(null)
  const [hypotheses, setHypotheses] = useState<Hypothesis[]>([])
  const [selectedHypothesis, setSelectedHypothesis] = useState<Hypothesis | null>(null)

  // AI pipeline connection status (real check, not mock)
  const [aiConnected, setAiConnected] = useState<boolean | null>(null)
  const [connectedAgents, setConnectedAgents] = useState(0)
  const [totalAgents, setTotalAgents] = useState(4)

  // Paper generation
  const [generatingPaper, setGeneratingPaper] = useState(false)
  const [paperMarkdown, setPaperMarkdown] = useState<string | null>(null)

  // Configuration
  const [config, setConfig] = useState<DiscoveryConfig>({
    disease: '',
    discoveryType: 'cure',
    focusEntities: [],
    maxAgents: 1000,
    targetConfidence: 0.95,
    externalFactors: [],
  })
  const [focusEntityInput, setFocusEntityInput] = useState('')
  const [showConfig, setShowConfig] = useState(true)
  const [showFactors, setShowFactors] = useState(false)

  // External factor input
  const [factorName, setFactorName] = useState('')
  const [factorCategory, setFactorCategory] = useState<ExternalFactor['category']>('nutrient')
  const [factorInteraction, setFactorInteraction] = useState('')

  // Polling ref for persistent updates
  const pollRef = useRef<number | null>(null)
  const failCountRef = useRef(0)

  // Fetch status from backend (real connection check)
  // Only mark disconnected after 3+ consecutive failures to avoid flicker
  const fetchStatus = useCallback(async () => {
    try {
      const response = await fetch(`${API_BASE}/orchestrator/status`)
      if (response.ok) {
        failCountRef.current = 0
        // Mark connected FIRST — 200 OK means the backend is alive.
        // Do this before response.json() so a body-parsing error can't block it.
        setAiConnected(true)
        try {
          const data = await response.json()
          setState(data.state || 'idle')
          if (data.stats) setStats(data.stats)
          if (data.top_hypotheses && data.top_hypotheses.length > 0) {
            setHypotheses(prev => {
              const existingIds = new Set(prev.map(h => h.id))
              const incoming = data.top_hypotheses.filter((h: Hypothesis) => !existingIds.has(h.id))
              if (incoming.length === 0) return prev
              // Auto-save new hypotheses to project library
              for (const h of incoming) {
                saveHypothesisToProject(h, config.disease, config.discoveryType)
              }
              return [...incoming, ...prev].sort((a: Hypothesis, b: Hypothesis) => b.confidence - a.confidence).slice(0, 100)
            })
          }
        } catch {
          // Body parse failed but connection is still alive (200 OK)
        }
      } else {
        failCountRef.current++
        if (failCountRef.current >= 3) setAiConnected(false)
      }
    } catch {
      failCountRef.current++
      if (failCountRef.current >= 3) setAiConnected(false)
    }
  }, [config.disease, config.discoveryType])

  // Check AI health on mount (returns connected count, never model names)
  useEffect(() => {
    const checkHealth = async () => {
      try {
        const response = await fetch(`${API_BASE}/orchestrator/health`)
        if (response.ok) {
          const data = await response.json()
          setConnectedAgents(data.connected_count || 0)
          setTotalAgents(data.total_models || 4)
          // Don't override aiConnected here — status polling handles that.
          // Health check only updates model counts.
        }
      } catch {
        // Health check failed, status polling will still set aiConnected
      }
    }
    checkHealth()
  }, [])

  // Poll for updates — persists across navigation (backend keeps running)
  useEffect(() => {
    fetchStatus()

    // Poll every 3s to keep state in sync with backend
    pollRef.current = window.setInterval(fetchStatus, 3000)

    return () => {
      if (pollRef.current) clearInterval(pollRef.current)
    }
  }, [fetchStatus])

  // Control functions
  const startDiscovery = useCallback(async () => {
    if (!config.disease.trim()) {
      alert('Please enter a disease to research')
      return
    }

    try {
      const response = await fetch(`${API_BASE}/orchestrator/start`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          disease: config.disease,
          focus_entities: config.focusEntities,
          discovery_type: config.discoveryType,
          max_agents: config.maxAgents,
          target_confidence: config.targetConfidence,
          external_factors: config.externalFactors,
        }),
      })

      if (response.ok) {
        setState('running')
        setShowConfig(false)
        setHypotheses([])
        setPaperMarkdown(null)
        logActivity({
          type: 'discovery',
          action: 'started',
          title: `Started ${config.discoveryType} discovery for ${config.disease}`,
          metadata: { disease: config.disease, discoveryType: config.discoveryType },
        })
      } else {
        let detail = `Server error (${response.status})`
        try {
          const error = await response.json()
          if (error.detail) detail = error.detail
          else if (error.message) detail = error.message
        } catch { /* non-JSON response */ }
        alert(`Failed to start: ${detail}`)
      }
    } catch (e) {
      console.error('Failed to start discovery:', e)
      alert('Failed to start discovery')
    }
  }, [config])

  const pauseDiscovery = useCallback(async () => {
    try {
      const response = await fetch(`${API_BASE}/orchestrator/pause`, { method: 'POST' })
      if (response.ok) setState('paused')
    } catch (e) {
      console.error('Failed to pause:', e)
    }
  }, [])

  const resumeDiscovery = useCallback(async () => {
    try {
      const response = await fetch(`${API_BASE}/orchestrator/resume`, { method: 'POST' })
      if (response.ok) setState('running')
    } catch (e) {
      console.error('Failed to resume:', e)
    }
  }, [])

  const stopDiscovery = useCallback(async () => {
    try {
      const response = await fetch(`${API_BASE}/orchestrator/stop`, { method: 'POST' })
      if (response.ok) setState('stopping')
    } catch (e) {
      console.error('Failed to stop:', e)
    }
  }, [])

  const generatePaper = useCallback(async () => {
    setGeneratingPaper(true)
    try {
      const response = await fetch(`${API_BASE}/orchestrator/generate-paper/markdown`, { method: 'POST' })
      if (response.ok) {
        const text = await response.text()
        setPaperMarkdown(text)
      } else {
        const error = await response.json()
        alert(`Paper generation failed: ${error.detail}`)
      }
    } catch (e) {
      console.error('Failed to generate paper:', e)
      alert('Failed to generate paper')
    } finally {
      setGeneratingPaper(false)
    }
  }, [])

  const downloadPaperMd = useCallback(() => {
    if (!paperMarkdown) return
    const blob = new Blob([paperMarkdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `humanovo-research-${config.disease.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.md`
    a.click()
    URL.revokeObjectURL(url)
  }, [paperMarkdown, config.disease])

  const downloadPaperHtml = useCallback(() => {
    if (!paperMarkdown) return
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    const titleMatch = paperMarkdown.match(/^#\s+(.+)$/m)
    const paperTitle = titleMatch ? titleMatch[1] : `${config.disease} — Research Report`

    // Convert markdown to simple HTML
    const bodyHtml = paperMarkdown
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
      .replace(/^\d+\.\s+(.+)$/gm, '<li>$1</li>')
      .replace(/\n{2,}/g, '</p><p>')
      .replace(/\n/g, '<br/>')

    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>${paperTitle}</title>
<style>
  @page { margin: 1in; size: A4; }
  body { font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a2e; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 40px; }
  .cover-page { display: flex; flex-direction: column; justify-content: center; align-items: center; min-height: 90vh; text-align: center; page-break-after: always; border: 3px solid #1a1a2e; padding: 60px 40px; margin-bottom: 40px; }
  .cover-logo { font-size: 14px; letter-spacing: 8px; text-transform: uppercase; color: #6c63ff; margin-bottom: 80px; font-weight: 700; }
  .cover-title { font-size: 32px; font-weight: 700; color: #1a1a2e; margin-bottom: 24px; line-height: 1.3; }
  .cover-subtitle { font-size: 16px; color: #555; margin-bottom: 60px; }
  .cover-author { font-size: 18px; font-weight: 600; color: #1a1a2e; margin-bottom: 8px; }
  .cover-affiliation { font-size: 14px; color: #6c63ff; letter-spacing: 3px; text-transform: uppercase; margin-bottom: 40px; }
  .cover-date { font-size: 14px; color: #777; }
  .cover-line { width: 60px; height: 3px; background: #6c63ff; margin: 20px auto; }
  h1 { font-size: 24px; color: #1a1a2e; border-bottom: 2px solid #6c63ff; padding-bottom: 8px; margin-top: 40px; }
  h2 { font-size: 20px; color: #2d2d5e; margin-top: 32px; }
  h3 { font-size: 16px; color: #3d3d7e; margin-top: 24px; }
  p { margin-bottom: 12px; }
  ul, ol { padding-left: 24px; margin-bottom: 12px; }
  li { margin-bottom: 6px; }
  strong { color: #1a1a2e; }
  .footer { text-align: center; margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
</style></head>
<body>
  <div class="cover-page">
    <div class="cover-logo">humanovo</div>
    <div class="cover-line"></div>
    <div class="cover-title">${paperTitle}</div>
    <div class="cover-subtitle">${config.discoveryType.charAt(0).toUpperCase() + config.discoveryType.slice(1)} Discovery Report</div>
    <div class="cover-line"></div>
    <div class="cover-author">By humanovo</div>
    <div class="cover-affiliation">AI-Driven Biomedical Research Platform</div>
    <div class="cover-date">${date}</div>
  </div>
  <div class="content"><p>${bodyHtml}</p></div>
  <div class="footer">Generated by humanovo &mdash; Multi-Model Parallel AI Discovery System &mdash; ${date}</div>
</body></html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `humanovo-research-${config.disease.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.html`
    a.click()
    URL.revokeObjectURL(url)
  }, [paperMarkdown, config.disease, config.discoveryType])

  const addFocusEntity = useCallback(() => {
    if (focusEntityInput.trim() && !config.focusEntities.includes(focusEntityInput.trim())) {
      setConfig(prev => ({
        ...prev,
        focusEntities: [...prev.focusEntities, focusEntityInput.trim()],
      }))
      setFocusEntityInput('')
    }
  }, [focusEntityInput, config.focusEntities])

  const removeFocusEntity = useCallback((entity: string) => {
    setConfig(prev => ({
      ...prev,
      focusEntities: prev.focusEntities.filter(e => e !== entity),
    }))
  }, [])

  const addExternalFactor = useCallback(() => {
    if (factorName.trim()) {
      setConfig(prev => ({
        ...prev,
        externalFactors: [...prev.externalFactors, {
          name: factorName.trim(),
          category: factorCategory,
          interaction: factorInteraction.trim(),
        }],
      }))
      setFactorName('')
      setFactorInteraction('')
    }
  }, [factorName, factorCategory, factorInteraction])

  const removeExternalFactor = useCallback((index: number) => {
    setConfig(prev => ({
      ...prev,
      externalFactors: prev.externalFactors.filter((_, i) => i !== index),
    }))
  }, [])

  const formatTime = (seconds: number) => {
    const hrs = Math.floor(seconds / 3600)
    const mins = Math.floor((seconds % 3600) / 60)
    const secs = Math.floor(seconds % 60)
    if (hrs > 0) return `${hrs}h ${mins}m ${secs}s`
    if (mins > 0) return `${mins}m ${secs}s`
    return `${secs}s`
  }

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.8) return 'text-green-400'
    if (confidence >= 0.6) return 'text-yellow-400'
    if (confidence >= 0.4) return 'text-orange-400'
    return 'text-red-400'
  }

  const getStateColor = () => {
    switch (state) {
      case 'running': return 'bg-green-500'
      case 'paused': return 'bg-yellow-500'
      case 'stopping': return 'bg-orange-500'
      default: return 'bg-gray-500'
    }
  }

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* Header */}
      <div className="p-4 border-b border-[var(--color-border)]">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className={clsx('w-3 h-3 rounded-full', getStateColor())} />
            <div>
              <h1 className="text-xl font-semibold">Discovery</h1>
              <p className="text-xs text-[var(--color-text-muted)] mt-0.5">
                4 parallel agents &middot; multi-model pipeline
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* AI Pipeline Status — real connection check */}
            <div className={clsx(
              'flex items-center gap-1.5 px-2 py-1 rounded text-xs',
              aiConnected ? 'bg-green-500/20 text-green-400' : 'bg-yellow-500/20 text-yellow-400'
            )}>
              <div className={clsx(
                'w-2 h-2 rounded-full',
                aiConnected ? 'bg-green-500' : 'bg-yellow-500 animate-pulse'
              )} />
              {aiConnected ? `${connectedAgents}/${totalAgents} Agents` : 'Connecting...'}
            </div>

            {/* Generate Paper Button */}
            {(state === 'idle' || state === 'paused') && hypotheses.length > 0 && (
              <button
                onClick={generatePaper}
                disabled={generatingPaper}
                className="btn bg-purple-500 text-white hover:bg-purple-600 disabled:opacity-50"
              >
                {generatingPaper ? (
                  <FiRefreshCw className="w-4 h-4 animate-spin" />
                ) : (
                  <FiFileText className="w-4 h-4" />
                )}
                {generatingPaper ? 'Generating...' : 'Generate Paper'}
              </button>
            )}

            {/* Control Buttons */}
            {state === 'idle' && (
              <button
                onClick={startDiscovery}
                disabled={!config.disease.trim()}
                className="btn bg-green-500 text-white hover:bg-green-600 disabled:opacity-50"
              >
                <FiPlay className="w-4 h-4" />
                Start Discovery
              </button>
            )}

            {state === 'running' && (
              <>
                <button
                  onClick={pauseDiscovery}
                  className="btn bg-yellow-500 text-white hover:bg-yellow-600"
                >
                  <FiPause className="w-4 h-4" />
                  Pause
                </button>
                <button
                  onClick={stopDiscovery}
                  className="btn bg-red-500 text-white hover:bg-red-600"
                >
                  <FiSquare className="w-4 h-4" />
                  Stop
                </button>
              </>
            )}

            {state === 'paused' && (
              <>
                <button
                  onClick={resumeDiscovery}
                  className="btn bg-green-500 text-white hover:bg-green-600"
                >
                  <FiPlay className="w-4 h-4" />
                  Resume
                </button>
                <button
                  onClick={stopDiscovery}
                  className="btn bg-red-500 text-white hover:bg-red-600"
                >
                  <FiSquare className="w-4 h-4" />
                  Stop
                </button>
              </>
            )}

            {state === 'stopping' && (
              <div className="flex items-center gap-2 text-orange-400">
                <FiRefreshCw className="w-4 h-4 animate-spin" />
                Stopping...
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Left Panel - Configuration & Stats */}
        <div className="w-80 border-r border-[var(--color-border)] overflow-y-auto">
          {/* Configuration Section */}
          <div className="border-b border-[var(--color-border)]">
            <button
              onClick={() => setShowConfig(!showConfig)}
              className="w-full p-3 flex items-center justify-between hover:bg-[var(--color-bg)]"
            >
              <div className="flex items-center gap-2">
                <FiSettings className="w-4 h-4 text-[var(--color-text-muted)]" />
                <span className="text-sm font-medium">Configuration</span>
              </div>
              {showConfig ? <FiChevronUp className="w-4 h-4" /> : <FiChevronDown className="w-4 h-4" />}
            </button>

            {showConfig && (
              <div className="p-3 space-y-4">
                {/* Disease Input */}
                <div>
                  <label className="text-xs text-[var(--color-text-muted)] block mb-1">
                    Target Disease
                  </label>
                  <input
                    type="text"
                    value={config.disease}
                    onChange={(e) => setConfig(prev => ({ ...prev, disease: e.target.value }))}
                    placeholder="e.g., Alzheimer's Disease"
                    className="w-full px-3 py-2 bg-[var(--color-bg)] border border-[var(--color-border)] rounded text-sm"
                    disabled={state !== 'idle'}
                  />
                </div>

                {/* Discovery Type */}
                <div>
                  <label className="text-xs text-[var(--color-text-muted)] block mb-1">
                    Discovery Type
                  </label>
                  <select
                    value={config.discoveryType}
                    onChange={(e) => setConfig(prev => ({ ...prev, discoveryType: e.target.value as DiscoveryConfig['discoveryType'] }))}
                    className="w-full px-3 py-2 bg-[var(--color-bg)] border border-[var(--color-border)] rounded text-sm"
                    disabled={state !== 'idle'}
                  >
                    {discoveryTypes.map(type => (
                      <option key={type.value} value={type.value}>{type.label}</option>
                    ))}
                  </select>
                </div>

                {/* Focus Entities */}
                <div>
                  <label className="text-xs text-[var(--color-text-muted)] block mb-1">
                    Focus Entities (optional)
                  </label>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={focusEntityInput}
                      onChange={(e) => setFocusEntityInput(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && addFocusEntity()}
                      placeholder="e.g., BRCA1, Amyloid-beta"
                      className="flex-1 px-3 py-2 bg-[var(--color-bg)] border border-[var(--color-border)] rounded text-sm"
                      disabled={state !== 'idle'}
                    />
                    <button
                      onClick={addFocusEntity}
                      className="btn btn-sm bg-[var(--color-border)]"
                      disabled={state !== 'idle'}
                    >
                      Add
                    </button>
                  </div>
                  {config.focusEntities.length > 0 && (
                    <div className="flex flex-wrap gap-1 mt-2">
                      {config.focusEntities.map(entity => (
                        <span
                          key={entity}
                          className="inline-flex items-center gap-1 px-2 py-0.5 bg-primary-500/20 text-primary-400 rounded text-xs"
                        >
                          {entity}
                          <button
                            onClick={() => removeFocusEntity(entity)}
                            className="hover:text-red-400"
                            disabled={state !== 'idle'}
                          >
                            <FiX className="w-3 h-3" />
                          </button>
                        </span>
                      ))}
                    </div>
                  )}
                </div>

                {/* External Factors */}
                <div>
                  <button
                    onClick={() => setShowFactors(!showFactors)}
                    className="text-xs text-[var(--color-text-muted)] flex items-center gap-1 mb-1"
                  >
                    {showFactors ? <FiChevronUp className="w-3 h-3" /> : <FiChevronDown className="w-3 h-3" />}
                    External Factors ({config.externalFactors.length})
                  </button>

                  {showFactors && (
                    <div className="space-y-2 p-2 bg-[var(--color-bg)] rounded border border-[var(--color-border)]">
                      <input
                        type="text"
                        value={factorName}
                        onChange={(e) => setFactorName(e.target.value)}
                        placeholder="Factor name (e.g., Vitamin D)"
                        className="w-full px-2 py-1.5 bg-[var(--color-bg-elevated)] border border-[var(--color-border)] rounded text-xs"
                        disabled={state !== 'idle'}
                      />
                      <select
                        value={factorCategory}
                        onChange={(e) => setFactorCategory(e.target.value as ExternalFactor['category'])}
                        className="w-full px-2 py-1.5 bg-[var(--color-bg-elevated)] border border-[var(--color-border)] rounded text-xs"
                        disabled={state !== 'idle'}
                      >
                        {factorCategories.map(cat => (
                          <option key={cat} value={cat}>{cat.charAt(0).toUpperCase() + cat.slice(1)}</option>
                        ))}
                      </select>
                      <input
                        type="text"
                        value={factorInteraction}
                        onChange={(e) => setFactorInteraction(e.target.value)}
                        placeholder="Known interaction (optional)"
                        className="w-full px-2 py-1.5 bg-[var(--color-bg-elevated)] border border-[var(--color-border)] rounded text-xs"
                        disabled={state !== 'idle'}
                      />
                      <button
                        onClick={addExternalFactor}
                        className="btn btn-sm w-full bg-[var(--color-border)] text-xs"
                        disabled={state !== 'idle' || !factorName.trim()}
                      >
                        <FiPlus className="w-3 h-3" /> Add Factor
                      </button>

                      {config.externalFactors.length > 0 && (
                        <div className="space-y-1 mt-2 max-h-32 overflow-y-auto">
                          {config.externalFactors.map((factor, i) => (
                            <div key={i} className="flex items-center justify-between text-xs py-1 px-1.5 bg-[var(--color-bg-elevated)] rounded">
                              <span>
                                <span className="font-medium">{factor.name}</span>
                                <span className="text-[var(--color-text-muted)] ml-1">({factor.category})</span>
                              </span>
                              <button
                                onClick={() => removeExternalFactor(i)}
                                className="text-red-400 hover:text-red-300"
                                disabled={state !== 'idle'}
                              >
                                <FiX className="w-3 h-3" />
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                </div>

                {/* Agent Count */}
                <div>
                  <label className="text-xs text-[var(--color-text-muted)] block mb-1">
                    Max Agents: {config.maxAgents.toLocaleString()}
                  </label>
                  <input
                    type="range"
                    min="100"
                    max="10000"
                    step="100"
                    value={config.maxAgents}
                    onChange={(e) => setConfig(prev => ({ ...prev, maxAgents: parseInt(e.target.value) }))}
                    className="w-full"
                    disabled={state !== 'idle'}
                  />
                </div>

                {/* Target Confidence */}
                <div>
                  <label className="text-xs text-[var(--color-text-muted)] block mb-1">
                    Target Confidence: {(config.targetConfidence * 100).toFixed(0)}%
                  </label>
                  <input
                    type="range"
                    min="0.5"
                    max="0.99"
                    step="0.01"
                    value={config.targetConfidence}
                    onChange={(e) => setConfig(prev => ({ ...prev, targetConfidence: parseFloat(e.target.value) }))}
                    className="w-full"
                    disabled={state !== 'idle'}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Live Stats */}
          {stats && (
            <div className="p-3 border-b border-[var(--color-border)]">
              <h3 className="text-xs font-medium text-[var(--color-text-muted)] uppercase mb-3">
                Live Statistics
              </h3>

              <div className="grid grid-cols-2 gap-2">
                <div className="card p-2">
                  <div className="text-lg font-bold">{stats.total_agents}</div>
                  <div className="text-xxs text-[var(--color-text-muted)]">Total Agents</div>
                </div>
                <div className="card p-2">
                  <div className="text-lg font-bold text-green-400">{stats.active_agents}</div>
                  <div className="text-xxs text-[var(--color-text-muted)]">Active</div>
                </div>
                <div className="card p-2">
                  <div className="text-lg font-bold">{stats.paths_explored.toLocaleString()}</div>
                  <div className="text-xxs text-[var(--color-text-muted)]">Paths Explored</div>
                </div>
                <div className="card p-2">
                  <div className="text-lg font-bold text-purple-400">{stats.hypotheses_found}</div>
                  <div className="text-xxs text-[var(--color-text-muted)]">Hypotheses</div>
                </div>
              </div>

              {/* Best Confidence */}
              <div className="mt-3 card p-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs text-[var(--color-text-muted)]">Best Confidence</span>
                  <span className={clsx('text-lg font-bold', getConfidenceColor(stats.current_best_confidence))}>
                    {(stats.current_best_confidence * 100).toFixed(1)}%
                  </span>
                </div>
                <div className="h-2 bg-[var(--color-border)] rounded-full overflow-hidden">
                  <div
                    className={clsx(
                      'h-full rounded-full transition-all duration-500',
                      stats.current_best_confidence >= 0.8 ? 'bg-green-500' :
                      stats.current_best_confidence >= 0.6 ? 'bg-yellow-500' :
                      stats.current_best_confidence >= 0.4 ? 'bg-orange-500' : 'bg-red-500'
                    )}
                    style={{ width: `${stats.current_best_confidence * 100}%` }}
                  />
                </div>
                <div className="flex justify-between mt-1">
                  <span className="text-xxs text-[var(--color-text-muted)]">0%</span>
                  <span className="text-xxs text-[var(--color-text-muted)]">Target: {(config.targetConfidence * 100).toFixed(0)}%</span>
                </div>
              </div>

              {/* Runtime */}
              <div className="mt-3 flex items-center justify-between text-sm">
                <span className="text-[var(--color-text-muted)]">Runtime</span>
                <span className="font-mono">{formatTime(stats.runtime_seconds)}</span>
              </div>

              {/* High Confidence Discoveries */}
              <div className="mt-2 flex items-center justify-between text-sm">
                <span className="text-[var(--color-text-muted)]">High Confidence</span>
                <span className="text-green-400 font-bold">{stats.high_confidence_discoveries}</span>
              </div>
            </div>
          )}

          {/* Learning Stats */}
          {stats?.learning_stats && (
            <div className="p-3 border-b border-[var(--color-border)]">
              <h3 className="text-xs font-medium text-[var(--color-text-muted)] uppercase mb-3">
                Learning Progress
              </h3>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-[var(--color-text-muted)]">Paths Learned</span>
                  <span>{stats.learning_stats.total_explored.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-[var(--color-text-muted)]">Low Value (skipped)</span>
                  <span className="text-red-400">{stats.learning_stats.low_value_paths}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-[var(--color-text-muted)]">High Value</span>
                  <span className="text-green-400">{stats.learning_stats.high_value_paths}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-[var(--color-text-muted)]">Avg Score</span>
                  <span>{(stats.learning_stats.avg_relation_score * 100).toFixed(1)}%</span>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Main Content - Hypotheses or Paper */}
        <div className="flex-1 overflow-y-auto">
          {/* Paper View — visual doc with cover page */}
          {paperMarkdown ? (
            <div className="p-4">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-sm font-medium text-[var(--color-text-muted)] uppercase">
                  Generated Research Paper
                </h2>
                <div className="flex items-center gap-2">
                  <button
                    onClick={downloadPaperHtml}
                    className="btn btn-sm bg-purple-500/20 text-purple-400"
                  >
                    <FiDownload className="w-3.5 h-3.5" />
                    Download Visual Doc
                  </button>
                  <button
                    onClick={downloadPaperMd}
                    className="btn btn-sm bg-[var(--color-border)]"
                  >
                    <FiDownload className="w-3.5 h-3.5" />
                    Markdown
                  </button>
                  <button
                    onClick={() => setPaperMarkdown(null)}
                    className="btn btn-sm bg-[var(--color-border)]"
                  >
                    Back to Hypotheses
                  </button>
                </div>
              </div>

              {/* Visual Cover Page */}
              <div className="card mb-4 overflow-hidden">
                <div className="flex flex-col items-center justify-center py-16 px-8 text-center border-b-2 border-purple-500/30 bg-gradient-to-b from-[var(--color-surface)] to-[var(--color-bg)]">
                  <div className="text-xs tracking-[0.3em] uppercase text-purple-400 font-bold mb-8">humanovo</div>
                  <div className="w-12 h-0.5 bg-purple-500 mb-8" />
                  <h1 className="text-2xl font-bold mb-3 max-w-lg leading-snug">
                    {paperMarkdown.match(/^#\s+(.+)$/m)?.[1] || `${config.disease} — Research Report`}
                  </h1>
                  <p className="text-sm text-[var(--color-text-muted)] mb-8">
                    {config.discoveryType.charAt(0).toUpperCase() + config.discoveryType.slice(1)} Discovery Report
                  </p>
                  <div className="w-12 h-0.5 bg-purple-500 mb-8" />
                  <p className="text-sm font-semibold mb-1">By humanovo</p>
                  <p className="text-xs tracking-[0.2em] uppercase text-purple-400 mb-6">AI-Driven Biomedical Research Platform</p>
                  <p className="text-xs text-[var(--color-text-muted)]">
                    {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                  </p>
                </div>

                {/* Paper Content */}
                <div className="p-6 prose prose-invert max-w-none">
                  <pre className="whitespace-pre-wrap text-sm font-mono leading-relaxed">{paperMarkdown}</pre>
                </div>

                {/* Footer */}
                <div className="px-6 py-4 border-t border-[var(--color-border)] text-center text-xs text-[var(--color-text-muted)]">
                  Generated by humanovo — Multi-Model Parallel AI Discovery System — {new Date().toLocaleDateString()}
                </div>
              </div>
            </div>
          ) : hypotheses.length > 0 ? (
            <div className="p-4 space-y-3">
              <h2 className="text-sm font-medium text-[var(--color-text-muted)] uppercase">
                Discovered Hypotheses ({hypotheses.length})
              </h2>

              {hypotheses.map((hypothesis, index) => (
                <button
                  key={hypothesis.id}
                  onClick={() => setSelectedHypothesis(hypothesis)}
                  className={clsx(
                    'w-full text-left card hover:border-[var(--color-border-strong)] transition-colors',
                    selectedHypothesis?.id === hypothesis.id && 'border-primary-500'
                  )}
                >
                  <div className="flex items-start gap-3">
                    <div className={clsx(
                      'w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold',
                      hypothesis.confidence >= 0.8 ? 'bg-green-500/20 text-green-400' :
                      hypothesis.confidence >= 0.6 ? 'bg-yellow-500/20 text-yellow-400' :
                      'bg-orange-500/20 text-orange-400'
                    )}>
                      {index + 1}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2">
                        <span className="font-medium truncate">{hypothesis.title}</span>
                        <span className={clsx(
                          'text-sm font-bold',
                          getConfidenceColor(hypothesis.confidence)
                        )}>
                          {(hypothesis.confidence * 100).toFixed(1)}%
                        </span>
                      </div>
                      <p className="text-sm text-[var(--color-text-muted)] mt-1 line-clamp-2">
                        {hypothesis.description}
                      </p>
                      <div className="flex items-center gap-2 mt-2">
                        {hypothesis.validated && (
                          <span className="text-xxs px-1.5 py-0.5 bg-green-500/20 text-green-400 rounded flex items-center gap-1">
                            <FiCheckCircle className="w-3 h-3" />
                            Validated
                          </span>
                        )}
                        {hypothesis.external_factors && hypothesis.external_factors.length > 0 && (
                          <span className="text-xxs px-1.5 py-0.5 bg-purple-500/20 text-purple-400 rounded">
                            +{hypothesis.external_factors.length} factors
                          </span>
                        )}
                        <span className="text-xxs px-1.5 py-0.5 bg-blue-500/20 text-blue-400 rounded flex items-center gap-1">
                          <FiSend className="w-3 h-3" />
                          Saved to Project
                        </span>
                      </div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          ) : state === 'running' || state === 'paused' ? (
            <div className="flex items-center justify-center h-full p-8">
              <div className="w-full max-w-lg space-y-8">
                {/* Animated Progress Ring */}
                <div className="flex flex-col items-center">
                  <div className="relative w-40 h-40 mb-4">
                    {/* Background ring */}
                    <svg className="w-full h-full -rotate-90" viewBox="0 0 120 120">
                      <circle cx="60" cy="60" r="52" fill="none" stroke="var(--color-border)" strokeWidth="6" />
                      {/* Progress arc */}
                      <circle
                        cx="60" cy="60" r="52" fill="none"
                        stroke={state === 'paused' ? '#eab308' : '#8b5cf6'}
                        strokeWidth="6"
                        strokeLinecap="round"
                        strokeDasharray={`${2 * Math.PI * 52}`}
                        strokeDashoffset={`${2 * Math.PI * 52 * (1 - (stats ? (stats.current_round || 0) / Math.max(stats.total_rounds || 1, 1) : 0))}`}
                        className="transition-all duration-1000 ease-out"
                      />
                      {/* Animated sweep for running state */}
                      {state === 'running' && (
                        <circle
                          cx="60" cy="60" r="52" fill="none"
                          stroke="#8b5cf6"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeDasharray={`${2 * Math.PI * 52 * 0.15} ${2 * Math.PI * 52 * 0.85}`}
                          className="animate-spin origin-center"
                          style={{ animationDuration: '2s' }}
                          opacity="0.4"
                        />
                      )}
                    </svg>
                    {/* Center text */}
                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <span className="text-3xl font-bold tabular-nums">
                        {stats ? Math.round(((stats.current_round || 0) / Math.max(stats.total_rounds || 1, 1)) * 100) : 0}%
                      </span>
                      <span className="text-xs text-[var(--color-text-muted)]">
                        {state === 'paused' ? 'Paused' : stats ? `Round ${stats.current_round || 0}/${stats.total_rounds || '?'}` : 'Starting...'}
                      </span>
                    </div>
                  </div>
                  <p className="text-sm font-medium">
                    {state === 'paused' ? 'Discovery Paused' : 'Agents Exploring...'}
                  </p>
                  <p className="text-xs text-[var(--color-text-muted)] mt-1">
                    {config.disease} &middot; {config.discoveryType}
                  </p>
                </div>

                {/* Live Confidence Score */}
                <div className="card p-4">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-medium text-[var(--color-text-muted)] uppercase tracking-wide">Best Confidence</span>
                    <span className={clsx(
                      'text-2xl font-bold tabular-nums transition-all duration-500',
                      getConfidenceColor(stats?.current_best_confidence || 0)
                    )}>
                      {((stats?.current_best_confidence || 0) * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="h-3 bg-[var(--color-border)] rounded-full overflow-hidden">
                    <div
                      className={clsx(
                        'h-full rounded-full transition-all duration-1000 ease-out',
                        (stats?.current_best_confidence || 0) >= 0.8 ? 'bg-green-500' :
                        (stats?.current_best_confidence || 0) >= 0.6 ? 'bg-yellow-500' :
                        (stats?.current_best_confidence || 0) >= 0.4 ? 'bg-orange-500' : 'bg-red-500'
                      )}
                      style={{ width: `${(stats?.current_best_confidence || 0) * 100}%` }}
                    />
                  </div>
                  <div className="flex justify-between mt-1.5">
                    <span className="text-xxs text-[var(--color-text-muted)]">0%</span>
                    <span className="text-xxs text-[var(--color-text-muted)]">Target: {(config.targetConfidence * 100).toFixed(0)}%</span>
                  </div>
                </div>

                {/* Agent Activity Grid */}
                <div className="grid grid-cols-2 gap-3">
                  {['Explorer', 'Reasoner', 'Synthesizer', 'Critic'].map((role, i) => (
                    <div key={role} className="card p-3 relative overflow-hidden">
                      {state === 'running' && (
                        <div
                          className="absolute inset-0 bg-purple-500/5 animate-pulse"
                          style={{ animationDelay: `${i * 0.3}s`, animationDuration: '2s' }}
                        />
                      )}
                      <div className="relative flex items-center gap-2">
                        <div className={clsx(
                          'w-2 h-2 rounded-full',
                          state === 'running' ? 'bg-green-500 animate-pulse' :
                          state === 'paused' ? 'bg-yellow-500' : 'bg-gray-500'
                        )} style={{ animationDelay: `${i * 0.2}s` }} />
                        <span className="text-xs font-medium">{role}</span>
                      </div>
                      <div className="relative text-xxs text-[var(--color-text-muted)] mt-1 ml-4">
                        {state === 'running' ? 'Analyzing...' : state === 'paused' ? 'Paused' : 'Idle'}
                      </div>
                    </div>
                  ))}
                </div>

                {/* Live Counters */}
                <div className="grid grid-cols-3 gap-3">
                  <div className="card p-3 text-center">
                    <div className="text-xl font-bold tabular-nums text-purple-400">
                      {stats?.hypotheses_found || 0}
                    </div>
                    <div className="text-xxs text-[var(--color-text-muted)]">Hypotheses</div>
                  </div>
                  <div className="card p-3 text-center">
                    <div className="text-xl font-bold tabular-nums">
                      {stats?.paths_explored?.toLocaleString() || 0}
                    </div>
                    <div className="text-xxs text-[var(--color-text-muted)]">Paths</div>
                  </div>
                  <div className="card p-3 text-center">
                    <div className="text-xl font-bold tabular-nums text-green-400">
                      {stats?.high_confidence_discoveries || 0}
                    </div>
                    <div className="text-xxs text-[var(--color-text-muted)]">High Conf.</div>
                  </div>
                </div>

                {/* Runtime */}
                {stats && (
                  <div className="text-center text-sm text-[var(--color-text-muted)]">
                    Runtime: <span className="font-mono">{formatTime(stats.runtime_seconds)}</span>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-full">
              <div className="text-center">
                <FiTarget className="w-12 h-12 text-[var(--color-border)] mx-auto mb-4" />
                <p className="text-[var(--color-text-muted)]">No hypotheses yet</p>
                <p className="text-xs text-[var(--color-text-muted)] mt-2">
                  Configure and start a discovery to see results
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Right Panel - Hypothesis Detail */}
        {selectedHypothesis && !paperMarkdown && (
          <div className="w-96 border-l border-[var(--color-border)] overflow-y-auto">
            <div className="p-4">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-2">
                  <FiAward className={clsx(
                    'w-5 h-5',
                    getConfidenceColor(selectedHypothesis.confidence)
                  )} />
                  <span className={clsx(
                    'text-xl font-bold',
                    getConfidenceColor(selectedHypothesis.confidence)
                  )}>
                    {(selectedHypothesis.confidence * 100).toFixed(1)}%
                  </span>
                </div>
                <button
                  onClick={() => setSelectedHypothesis(null)}
                  className="text-[var(--color-text-muted)] hover:text-[var(--color-text)]"
                >
                  <FiX className="w-4 h-4" />
                </button>
              </div>

              <h3 className="text-lg font-semibold mb-2">{selectedHypothesis.title}</h3>

              <div className="space-y-4">
                <div>
                  <h4 className="text-xs font-medium text-[var(--color-text-muted)] uppercase mb-1">
                    Description
                  </h4>
                  <p className="text-sm">{selectedHypothesis.description}</p>
                </div>

                <div>
                  <h4 className="text-xs font-medium text-[var(--color-text-muted)] uppercase mb-1">
                    Mechanism of Action
                  </h4>
                  <p className="text-sm">{selectedHypothesis.mechanism || 'Not specified'}</p>
                </div>

                {selectedHypothesis.external_factors && selectedHypothesis.external_factors.length > 0 && (
                  <div>
                    <h4 className="text-xs font-medium text-[var(--color-text-muted)] uppercase mb-1">
                      External Factor Interactions
                    </h4>
                    <div className="space-y-1">
                      {selectedHypothesis.external_factors.map((factor, i) => (
                        <div key={i} className="text-xs p-1.5 bg-purple-500/10 border border-purple-500/20 rounded">
                          {typeof factor === 'string' ? factor : JSON.stringify(factor)}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {selectedHypothesis.validated && (
                  <div className="p-3 bg-green-500/10 border border-green-500/30 rounded">
                    <div className="flex items-center gap-2 text-green-400">
                      <FiCheckCircle className="w-4 h-4" />
                      <span className="font-medium">Validated</span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
