import { useState, useCallback, useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { FiZap, FiCheck, FiAlertTriangle, FiClock, FiDownload, FiRefreshCw } from 'react-icons/fi'
import { api, Hypothesis } from '../services/api'
import { persistGet } from '../utils/persistence'
import clsx from 'clsx'

// Build a self-contained HTML document for a hypothesis that can be printed to PDF
function buildHypothesisPdfHtml(h: {
  title: string
  description?: string
  mechanism?: string
  confidence: number
  disease?: string
  tags?: string[]
}): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${h.title}</title>
<style>
  @page { size: A4; margin: 2cm; }
  body { font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a2e; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 40px; }
  .cover { text-align: center; padding: 60px 0 40px; border-bottom: 3px double #333; margin-bottom: 40px; }
  .cover h1 { font-size: 24px; margin-bottom: 16px; color: #1a1a2e; }
  .cover .meta { color: #666; font-size: 14px; }
  .badge { display: inline-block; padding: 4px 12px; border-radius: 4px; font-size: 13px; font-weight: 600; }
  .badge-high { background: #dcfce7; color: #166534; }
  .badge-med { background: #fef9c3; color: #854d0e; }
  .badge-low { background: #fed7aa; color: #9a3412; }
  h2 { font-size: 18px; color: #1a1a2e; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-top: 32px; }
  .section { margin-bottom: 24px; }
  .section p { text-align: justify; }
  .tags { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 8px; }
  .tag { background: #f3f4f6; padding: 3px 10px; border-radius: 3px; font-size: 12px; color: #4b5563; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
</style></head><body>
<div class="cover">
  <h1>${h.title}</h1>
  <div class="meta">
    <p>Generated by Humanovo AI Discovery Platform</p>
    <p>${date}</p>
    <p style="margin-top:12px">
      <span class="badge ${h.confidence >= 0.7 ? 'badge-high' : h.confidence >= 0.5 ? 'badge-med' : 'badge-low'}">
        ${(h.confidence * 100).toFixed(1)}% Confidence
      </span>
      ${h.disease ? `&nbsp;&nbsp;<span class="badge" style="background:#e0e7ff;color:#3730a3">${h.disease}</span>` : ''}
    </p>
  </div>
</div>

${h.description ? `<div class="section"><h2>Description</h2><p>${h.description}</p></div>` : ''}
${h.mechanism ? `<div class="section"><h2>Mechanism of Action</h2><p>${h.mechanism}</p></div>` : ''}

<div class="section">
  <h2>Confidence Analysis</h2>
  <p>This hypothesis has a confidence score of <strong>${(h.confidence * 100).toFixed(1)}%</strong>,
  placing it in the <strong>${h.confidence >= 0.8 ? 'very high' : h.confidence >= 0.7 ? 'high' : h.confidence >= 0.5 ? 'moderate' : 'preliminary'}</strong>
  confidence tier. ${h.confidence >= 0.7 ? 'This level of confidence suggests strong supporting evidence from multiple sources.' :
  h.confidence >= 0.5 ? 'Further validation through experimental studies is recommended.' :
  'Additional evidence gathering and validation is needed before proceeding to experimental stages.'}</p>
</div>

${h.tags && h.tags.length > 0 ? `<div class="section"><h2>Tags</h2><div class="tags">${h.tags.map(t => `<span class="tag">${t}</span>`).join('')}</div></div>` : ''}

<div class="footer">
  <p>Humanovo &mdash; AI-Powered Biomedical Discovery Platform</p>
  <p>This document was generated on ${date}</p>
</div>
</body></html>`
}

function downloadHypothesisPdf(title: string, htmlContent: string) {
  // Open in new window and trigger print (browser's Save as PDF)
  const win = window.open('', '_blank')
  if (!win) {
    // Fallback: download as HTML
    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `humanovo-${title.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 50)}.html`
    a.click()
    URL.revokeObjectURL(url)
    return
  }
  win.document.write(htmlContent)
  win.document.close()
  // Delay to let styles render, then trigger print dialog
  setTimeout(() => win.print(), 500)
}

interface LocalHypothesis {
  id: string
  title: string
  description: string
  mechanism: string
  confidence: number
  tags: string[]
  disease?: string
  discovery_type?: string
  project_id?: string
  created_at: string
}

function HypothesisCard({ hypothesis }: { hypothesis: Hypothesis }) {
  const [exporting, setExporting] = useState(false)

  const statusConfig = {
    draft: { icon: FiClock, color: 'text-secondary-400', bg: 'bg-secondary-600/20' },
    generating: { icon: FiClock, color: 'text-yellow-400', bg: 'bg-yellow-600/20' },
    active: { icon: FiZap, color: 'text-blue-400', bg: 'bg-blue-600/20' },
    validated: { icon: FiCheck, color: 'text-green-400', bg: 'bg-green-600/20' },
    rejected: { icon: FiAlertTriangle, color: 'text-red-400', bg: 'bg-red-600/20' },
    archived: { icon: FiClock, color: 'text-secondary-400', bg: 'bg-secondary-600/20' },
  }

  const status = statusConfig[hypothesis.status] || statusConfig.draft
  const StatusIcon = status.icon

  const handleExportPdf = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setExporting(true)
    try {
      const html = buildHypothesisPdfHtml({
        title: hypothesis.statement,
        description: hypothesis.rationale || hypothesis.mechanism || '',
        mechanism: hypothesis.mechanism || '',
        confidence: hypothesis.confidence_score,
        tags: hypothesis.tags,
      })
      downloadHypothesisPdf(hypothesis.statement, html)
    } finally {
      setTimeout(() => setExporting(false), 1000)
    }
  }, [hypothesis])

  return (
    <Link
      to={`/hypotheses/${hypothesis.id}`}
      className="card hover:border-primary-600/50 transition-colors"
    >
      <div className="flex items-start space-x-4">
        <div className={clsx('p-2 rounded-lg', status.bg)}>
          <StatusIcon className={clsx('w-5 h-5', status.color)} />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-white font-medium line-clamp-2">{hypothesis.statement}</p>
          {hypothesis.mechanism && (
            <p className="text-secondary-400 text-sm mt-1 line-clamp-1">
              {hypothesis.mechanism}
            </p>
          )}
        </div>
      </div>

      <div className="mt-4 flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <span className={clsx('badge', {
            'badge-success': hypothesis.status === 'validated',
            'badge-warning': hypothesis.status === 'generating',
            'badge-error': hypothesis.status === 'rejected',
            'badge-info': hypothesis.status === 'active',
          })}>
            {hypothesis.status}
          </span>
          <span className="text-secondary-400 text-sm">
            {Math.round(hypothesis.confidence_score * 100)}% confidence
          </span>
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={handleExportPdf}
            disabled={exporting}
            className="flex items-center gap-1 px-2 py-1 rounded text-xs bg-purple-500/20 text-purple-400 hover:bg-purple-500/30 disabled:opacity-50 transition-colors"
            title="Export as PDF"
          >
            {exporting ? (
              <FiRefreshCw className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <FiDownload className="w-3.5 h-3.5" />
            )}
            {exporting ? 'Exporting...' : 'Export PDF'}
          </button>
          <span className="text-secondary-500 text-xs">
            v{hypothesis.version}
          </span>
        </div>
      </div>

      <div className="mt-3 flex items-center space-x-4 text-sm">
        <span className="text-green-400">
          {hypothesis.supporting_count} supporting
        </span>
        <span className="text-red-400">
          {hypothesis.contradiction_count} contradicting
        </span>
      </div>
    </Link>
  )
}

// Card for locally-saved hypotheses (from discovery, stored in localStorage)
function LocalHypothesisCard({ hypothesis }: { hypothesis: LocalHypothesis }) {
  const [exporting, setExporting] = useState(false)

  const handleExportPdf = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setExporting(true)
    try {
      const html = buildHypothesisPdfHtml({
        title: hypothesis.title,
        description: hypothesis.description,
        mechanism: hypothesis.mechanism,
        confidence: hypothesis.confidence,
        disease: hypothesis.disease,
        tags: hypothesis.tags,
      })
      downloadHypothesisPdf(hypothesis.title, html)
    } finally {
      setTimeout(() => setExporting(false), 1000)
    }
  }, [hypothesis])

  return (
    <div className="card hover:border-primary-600/50 transition-colors">
      <div className="flex items-start space-x-4">
        <div className="p-2 rounded-lg bg-yellow-600/20">
          <FiZap className="w-5 h-5 text-yellow-400" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-white font-medium line-clamp-2">{hypothesis.title}</p>
          {hypothesis.mechanism && (
            <p className="text-secondary-400 text-sm mt-1 line-clamp-1">
              {hypothesis.mechanism}
            </p>
          )}
          {hypothesis.description && !hypothesis.mechanism && (
            <p className="text-secondary-400 text-sm mt-1 line-clamp-2">
              {hypothesis.description}
            </p>
          )}
        </div>
      </div>

      <div className="mt-4 flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <span className={clsx(
            'px-2 py-0.5 rounded text-xs font-medium',
            hypothesis.confidence >= 0.7 ? 'bg-green-500/20 text-green-400' :
            hypothesis.confidence >= 0.5 ? 'bg-yellow-500/20 text-yellow-400' : 'bg-orange-500/20 text-orange-400'
          )}>
            {Math.round(hypothesis.confidence * 100)}% confidence
          </span>
          {hypothesis.disease && (
            <span className="text-secondary-500 text-xs">{hypothesis.disease}</span>
          )}
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={handleExportPdf}
            disabled={exporting}
            className="flex items-center gap-1 px-2 py-1 rounded text-xs bg-purple-500/20 text-purple-400 hover:bg-purple-500/30 disabled:opacity-50 transition-colors"
            title="Export as PDF"
          >
            {exporting ? (
              <FiRefreshCw className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <FiDownload className="w-3.5 h-3.5" />
            )}
            {exporting ? 'Exporting...' : 'Export PDF'}
          </button>
        </div>
      </div>

      {hypothesis.tags && hypothesis.tags.length > 0 && (
        <div className="mt-3 flex flex-wrap gap-1">
          {hypothesis.tags.slice(0, 5).map(tag => (
            <span key={tag} className="text-xxs px-1.5 py-0.5 rounded bg-secondary-700 text-secondary-400">{tag}</span>
          ))}
        </div>
      )}
    </div>
  )
}

export default function Hypotheses() {
  const { data, isLoading, isError } = useQuery({
    queryKey: ['hypotheses'],
    queryFn: () => api.getHypotheses({ page: 1, page_size: 50 }),
    retry: 1,
  })

  // Load hypotheses from localStorage as fallback when API is down
  const localHypotheses = useMemo(() => {
    return persistGet<LocalHypothesis[]>('hypotheses', [])
  }, [])

  const apiHypotheses = data?.items || []
  const showLocal = (isError || (!isLoading && apiHypotheses.length === 0)) && localHypotheses.length > 0

  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-white">Hypotheses</h1>
          <p className="text-secondary-400 mt-1">AI-generated biomedical hypotheses</p>
        </div>
        <Link to="/agents" className="btn btn-primary flex items-center space-x-2">
          <FiZap className="w-4 h-4" />
          <span>Generate New</span>
        </Link>
      </div>

      {isError && localHypotheses.length === 0 && (
        <div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-sm text-red-400">
          Backend is offline. No locally-saved hypotheses found. Run a discovery from the Agents page first.
        </div>
      )}

      {showLocal && (
        <div className="mb-4 p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-lg text-sm text-yellow-400">
          Showing {localHypotheses.length} locally-saved hypotheses (backend is offline).
        </div>
      )}

      {isLoading ? (
        <div className="space-y-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="animate-pulse bg-secondary-800 h-32 rounded-lg" />
          ))}
        </div>
      ) : apiHypotheses.length > 0 ? (
        <div className="space-y-4">
          {apiHypotheses.map((hypothesis) => (
            <HypothesisCard key={hypothesis.id} hypothesis={hypothesis} />
          ))}
        </div>
      ) : showLocal ? (
        <div className="space-y-4">
          {localHypotheses.map((hypothesis) => (
            <LocalHypothesisCard key={hypothesis.id} hypothesis={hypothesis} />
          ))}
        </div>
      ) : (
        <div className="text-center py-16">
          <FiZap className="w-12 h-12 text-secondary-600 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-white mb-2">No hypotheses yet</h3>
          <p className="text-secondary-400 mb-6">
            Generate your first AI-powered hypothesis from the Discovery page
          </p>
          <Link to="/agents" className="btn btn-primary">Start Discovery</Link>
        </div>
      )}
    </div>
  )
}
