import { useState, useCallback, useEffect, useRef, useMemo } from 'react'
import { useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import {
  FiArrowLeft, FiFileText, FiRefreshCw, FiX, FiDownload,
} from 'react-icons/fi'
import clsx from 'clsx'
import { api } from '../services/api'
import { persistGet } from '../utils/persistence'

const API_BASE = '/api/v1'

const PAPER_PHASES = [
  { label: 'Initializing 8-model pipeline...', duration: 3000 },
  { label: 'Phase 1: Generating abstract & introduction...', duration: 12000 },
  { label: 'Phase 2: Core sections — literature, methods, results...', duration: 25000 },
  { label: 'Phase 3: Synthesis — discussion, mechanisms, conclusion...', duration: 20000 },
  { label: 'Phase 4: QA & review...', duration: 15000 },
  { label: 'Rendering PDF...', duration: 8000 },
]

// Build a self-contained HTML paper for a hypothesis (client-side fallback)
function buildHypothesisPaperHtml(h: {
  title: string; description?: string; mechanism?: string; confidence: number; disease?: string; tags?: string[];
}): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${h.title}</title>
<style>
  @page { size: A4; margin: 2cm; }
  body { font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a2e; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 40px; }
  .cover { text-align: center; padding: 60px 0 40px; border-bottom: 3px double #333; margin-bottom: 40px; }
  .cover h1 { font-size: 24px; margin-bottom: 16px; }
  .cover .meta { color: #666; font-size: 14px; }
  .badge { display: inline-block; padding: 4px 12px; border-radius: 4px; font-size: 13px; font-weight: 600; }
  .badge-high { background: #dcfce7; color: #166534; }
  .badge-med { background: #fef9c3; color: #854d0e; }
  .badge-low { background: #fed7aa; color: #9a3412; }
  h2 { font-size: 18px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-top: 32px; }
  .section p { text-align: justify; }
  .tags { display: flex; gap: 8px; flex-wrap: wrap; }
  .tag { background: #f3f4f6; padding: 3px 10px; border-radius: 3px; font-size: 12px; color: #4b5563; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
</style></head><body>
<div class="cover">
  <h1>${h.title}</h1>
  <div class="meta">
    <p>Generated by Humanovo AI Discovery Platform</p>
    <p>${date}</p>
    <p style="margin-top:12px">
      <span class="badge ${h.confidence >= 0.7 ? 'badge-high' : h.confidence >= 0.5 ? 'badge-med' : 'badge-low'}">
        ${(h.confidence * 100).toFixed(1)}% Confidence
      </span>
      ${h.disease ? `&nbsp;&nbsp;<span class="badge" style="background:#e0e7ff;color:#3730a3">${h.disease}</span>` : ''}
    </p>
  </div>
</div>
${h.description ? `<div class="section"><h2>Description</h2><p>${h.description}</p></div>` : ''}
${h.mechanism ? `<div class="section"><h2>Mechanism of Action</h2><p>${h.mechanism}</p></div>` : ''}
<div class="section"><h2>Confidence Analysis</h2>
<p>This hypothesis has a confidence score of <strong>${(h.confidence * 100).toFixed(1)}%</strong>,
placing it in the <strong>${h.confidence >= 0.8 ? 'very high' : h.confidence >= 0.7 ? 'high' : h.confidence >= 0.5 ? 'moderate' : 'preliminary'}</strong>
confidence tier. ${h.confidence >= 0.7 ? 'This level suggests strong supporting evidence.' : 'Further validation is recommended.'}</p></div>
${h.tags && h.tags.length > 0 ? `<div class="section"><h2>Tags</h2><div class="tags">${h.tags.map(t => `<span class="tag">${t}</span>`).join('')}</div></div>` : ''}
<div class="footer"><p>Humanovo &mdash; AI-Powered Biomedical Discovery Platform</p><p>${date}</p></div>
</body></html>`
}

interface LocalHypothesis {
  id: string; title: string; description: string; mechanism: string;
  confidence: number; tags: string[]; disease?: string;
}

export default function HypothesisDetail() {
  const { hypothesisId } = useParams<{ hypothesisId: string }>()

  const [generatingPaper, setGeneratingPaper] = useState(false)
  const [paperHtml, setPaperHtml] = useState<string | null>(null)
  const [paperError, setPaperError] = useState<string | null>(null)
  const [currentPhase, setCurrentPhase] = useState(0)
  const [phaseProgress, setPhaseProgress] = useState(0)
  const progressTimerRef = useRef<number | null>(null)

  const { data: apiHypothesis, isLoading, isError } = useQuery({
    queryKey: ['hypothesis', hypothesisId],
    queryFn: () => api.getHypothesis(hypothesisId!),
    enabled: !!hypothesisId,
    retry: 1,
  })

  // Fallback: load from localStorage when API is down
  const localHypothesis = useMemo(() => {
    if (apiHypothesis) return null
    const saved = persistGet<LocalHypothesis[]>('hypotheses', [])
    return saved.find(h => h.id === hypothesisId) || null
  }, [apiHypothesis, hypothesisId])

  // Merged hypothesis data (API or local)
  const hypothesis = apiHypothesis || (localHypothesis ? {
    id: localHypothesis.id,
    project_id: '',
    statement: localHypothesis.title,
    mechanism: localHypothesis.mechanism,
    rationale: localHypothesis.description,
    status: 'active' as const,
    confidence_score: localHypothesis.confidence,
    novelty_score: 0,
    evidence_refs: [],
    contradiction_count: 0,
    supporting_count: 0,
    tags: localHypothesis.tags || [],
    version: 1,
    created_at: '',
    updated_at: '',
  } : null)

  useEffect(() => {
    return () => { if (progressTimerRef.current) clearInterval(progressTimerRef.current) }
  }, [])

  const startPhaseAnimation = useCallback(() => {
    setCurrentPhase(0)
    setPhaseProgress(0)
    let phaseIdx = 0
    let elapsed = 0
    const TICK = 200
    if (progressTimerRef.current) clearInterval(progressTimerRef.current)
    progressTimerRef.current = window.setInterval(() => {
      elapsed += TICK
      const phaseDuration = PAPER_PHASES[phaseIdx]?.duration || 10000
      const pct = Math.min((elapsed / phaseDuration) * 100, 100)
      setPhaseProgress(pct)
      if (elapsed >= phaseDuration && phaseIdx < PAPER_PHASES.length - 1) {
        phaseIdx++
        elapsed = 0
        setCurrentPhase(phaseIdx)
        setPhaseProgress(0)
      }
    }, TICK)
  }, [])

  const stopPhaseAnimation = useCallback(() => {
    if (progressTimerRef.current) { clearInterval(progressTimerRef.current); progressTimerRef.current = null }
  }, [])

  const generatePaper = useCallback(async () => {
    if (!hypothesisId || !hypothesis) return
    setGeneratingPaper(true)
    setPaperError(null)
    setPaperHtml(null)
    startPhaseAnimation()

    // Helper: generate client-side HTML paper
    const generateClientSide = () => {
      setTimeout(() => {
        const html = buildHypothesisPaperHtml({
          title: hypothesis.statement || '',
          description: hypothesis.rationale || hypothesis.mechanism || '',
          mechanism: hypothesis.mechanism || '',
          confidence: hypothesis.confidence_score || 0,
          disease: localHypothesis?.disease || 'Unknown',
          tags: hypothesis.tags || [],
        })
        stopPhaseAnimation()
        setPaperHtml(html)
        setGeneratingPaper(false)
      }, 1500)
    }

    // Try backend first
    try {
      const res = await fetch(`${API_BASE}/documents/hypothesis/${hypothesisId}/html`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: hypothesis.statement || '',
          description: hypothesis.rationale || hypothesis.mechanism || '',
          mechanism: hypothesis.mechanism || '',
          confidence: hypothesis.confidence_score || 0,
          disease: localHypothesis?.disease || 'Unknown',
          discovery_type: 'treatment',
          model_used: 'unknown',
          tags: hypothesis.tags || [],
          external_factors: [],
        }),
      })

      if (res.ok) {
        const htmlContent = await res.text()
        if (htmlContent && htmlContent.length > 100) {
          stopPhaseAnimation()
          setPaperHtml(htmlContent)
          setGeneratingPaper(false)
          return
        }
      }

      // Backend failed — fall back to client-side
      generateClientSide()
    } catch {
      // Backend unreachable — fall back to client-side
      generateClientSide()
    }
  }, [hypothesisId, hypothesis, localHypothesis, startPhaseAnimation, stopPhaseAnimation])

  const downloadPaper = useCallback(() => {
    if (!paperHtml) return
    const win = window.open('', '_blank')
    if (!win) {
      // Fallback: download as HTML
      const blob = new Blob([paperHtml], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `humanovo-hypothesis-${hypothesisId}.html`
      a.click()
      URL.revokeObjectURL(url)
      return
    }
    win.document.write(paperHtml)
    win.document.close()
    setTimeout(() => win.print(), 500)
  }, [paperHtml, hypothesisId])

  if (isLoading && !localHypothesis) {
    return (
      <div className="p-8">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-secondary-800 rounded w-2/3" />
          <div className="h-4 bg-secondary-800 rounded w-1/2" />
        </div>
      </div>
    )
  }

  if (!hypothesis) {
    return (
      <div className="p-8">
        <p className="text-secondary-400">Hypothesis not found</p>
      </div>
    )
  }

  return (
    <div className="h-full flex flex-col">
      <div className="px-4 py-2 border-b border-secondary-700 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-2">
          <button
            onClick={() => window.history.back()}
            className="text-primary-400 hover:text-primary-300 text-sm"
          >
            <FiArrowLeft className="w-3.5 h-3.5 inline mr-1" />Back
          </button>
          <span className="text-secondary-600">/</span>
          <span className="text-secondary-400 text-sm truncate">{hypothesis.statement}</span>
        </div>
        <div className="flex items-center gap-2">
          {!paperHtml && !generatingPaper && (
            <button onClick={generatePaper} className="btn btn-sm bg-purple-500 text-white hover:bg-purple-600">
              <FiFileText className="w-3.5 h-3.5" />
              Generate Research Paper
            </button>
          )}
          {paperHtml && (
            <>
              <button onClick={downloadPaper} className="btn btn-sm bg-purple-500/20 text-purple-400 hover:bg-purple-500/30">
                <FiDownload className="w-3.5 h-3.5" />
                Export PDF
              </button>
              <button onClick={() => setPaperHtml(null)} className="btn btn-sm bg-secondary-700 text-secondary-400">
                Back
              </button>
            </>
          )}
        </div>
      </div>

      <div className="flex-1 min-h-0 relative">
        {/* Loading animation with phases */}
        {generatingPaper && (
          <div className="absolute inset-0 flex flex-col items-center justify-center bg-secondary-900 z-10">
            <div className="relative w-24 h-24 mb-6">
              <div className="absolute inset-0 rounded-full border-4 border-secondary-700" />
              <div className="absolute inset-0 rounded-full border-4 border-t-purple-500 animate-spin" />
              <FiFileText className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 text-purple-400" />
            </div>
            <h3 className="text-lg font-semibold text-white mb-2">Generating Research Paper</h3>
            <div className="mt-4 w-full max-w-lg px-8">
              <p className="text-purple-300 text-sm font-medium text-center mb-1">
                {PAPER_PHASES[currentPhase]?.label || 'Processing...'}
              </p>
              <p className="text-secondary-500 text-xs text-center mb-3">
                Step {currentPhase + 1} of {PAPER_PHASES.length}
              </p>
              <div className="h-2 bg-secondary-700 rounded-full overflow-hidden mb-2">
                <div
                  className="h-full bg-purple-500 rounded-full transition-all duration-200 ease-linear"
                  style={{ width: `${((currentPhase + phaseProgress / 100) / PAPER_PHASES.length) * 100}%` }}
                />
              </div>
              <div className="flex justify-between px-1">
                {PAPER_PHASES.map((_, idx) => (
                  <div
                    key={idx}
                    className={clsx(
                      'w-2 h-2 rounded-full transition-colors',
                      idx < currentPhase ? 'bg-purple-500' :
                      idx === currentPhase ? 'bg-purple-400 animate-pulse' : 'bg-secondary-600'
                    )}
                  />
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Error */}
        {paperError && !generatingPaper && (
          <div className="absolute inset-0 flex flex-col items-center justify-center bg-secondary-900 z-10">
            <FiX className="w-12 h-12 text-red-400 mb-4" />
            <h3 className="text-lg font-semibold text-white mb-2">Generation Failed</h3>
            <p className="text-red-400 text-sm mb-4 max-w-md text-center">{paperError}</p>
            <button onClick={generatePaper} className="btn bg-purple-500 text-white hover:bg-purple-600">
              <FiRefreshCw className="w-4 h-4" /> Retry
            </button>
          </div>
        )}

        {/* Paper viewer — HTML rendered in iframe */}
        {paperHtml && !generatingPaper && (
          <iframe
            srcDoc={paperHtml}
            className="w-full h-full"
            title="Research Paper"
            sandbox="allow-same-origin"
          />
        )}

        {/* Default: show hypothesis content */}
        {!generatingPaper && !paperHtml && !paperError && (
          <div className="overflow-y-auto p-8">
            <div className="max-w-4xl mx-auto">
              {isError && localHypothesis && (
                <div className="mb-4 p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-lg text-sm text-yellow-400">
                  Loaded from local cache (backend is offline).
                </div>
              )}
              <h1 className="text-2xl font-bold text-white mb-4">{hypothesis.statement}</h1>
              <div className="flex items-center gap-3 mb-6">
                <span className={clsx(
                  'px-3 py-1 rounded-full text-sm font-bold',
                  (hypothesis.confidence_score || 0) >= 0.7 ? 'bg-green-500/20 text-green-400' :
                  (hypothesis.confidence_score || 0) >= 0.5 ? 'bg-yellow-500/20 text-yellow-400' : 'bg-orange-500/20 text-orange-400'
                )}>
                  {((hypothesis.confidence_score || 0) * 100).toFixed(1)}% Confidence
                </span>
              </div>
              {hypothesis.rationale && (
                <div className="mb-6">
                  <h2 className="text-xs font-semibold text-secondary-400 uppercase tracking-wider mb-2">Rationale</h2>
                  <p className="text-secondary-200 leading-relaxed whitespace-pre-wrap">{hypothesis.rationale}</p>
                </div>
              )}
              {hypothesis.mechanism && (
                <div className="mb-6">
                  <h2 className="text-xs font-semibold text-secondary-400 uppercase tracking-wider mb-2">Mechanism</h2>
                  <div className="bg-secondary-800 border border-secondary-700 rounded-lg p-4">
                    <p className="text-secondary-200 leading-relaxed whitespace-pre-wrap">{hypothesis.mechanism}</p>
                  </div>
                </div>
              )}

              {/* Generate Paper CTA */}
              <div className="mt-8 p-6 bg-purple-500/10 border border-purple-500/30 rounded-lg text-center">
                <FiFileText className="w-8 h-8 text-purple-400 mx-auto mb-3" />
                <h3 className="text-white font-semibold mb-1">Generate Research Paper</h3>
                <p className="text-secondary-400 text-sm mb-4">
                  Professional document with cover page, confidence analysis, and mechanism details.
                </p>
                <button onClick={generatePaper} className="btn bg-purple-500 text-white hover:bg-purple-600">
                  <FiFileText className="w-4 h-4" />
                  Generate Research Paper
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
